/**
 * Accessibility matrix (WCAG 2.2 AA): the per-component status block on
 * Docs pages and the full table on Design System/Accessibility. Data comes
 * from spec/a11y.json, generated by scripts/build-a11y.mjs from the code
 * (axe coverage, keyboard play tests, motion, forced colors, the traits
 * that decide which criteria apply) and from a11y/manual.json
 * (screen-reader passes, manual reviews, accepted deviations).
 */
import { useMemo, useState, type ReactNode } from 'react';
import matrix from '../../spec/a11y.json';
import { Badge } from '../components/ui/badge';
import type { StatusTone } from '../components/ui/status-dot';
import { TextField } from '../components/ui/text-field';
import { ToggleGroup, ToggleGroupItem } from '../components/ui/toggle-group';
import { cn } from '../lib/utils';

interface ScreenReaderPass {
  at: string;
  browser?: string;
  date: string;
  result: 'pass' | 'issues';
  notes?: string;
}

export interface A11yRow {
  name: string;
  title: string | null;
  axe: { stories: number; themes: string[]; exclusions: { story: string; rules: string[] }[] };
  keyboard: { tested: number; playTests: number };
  reducedMotion: 'none' | 'respected' | 'unguarded';
  moving?: string[];
  forcedColors: 'component' | 'global';
  screenReader: ScreenReaderPass[];
  deviations: { criterion: string; note: string }[];
  traits: string[];
  wcag: Record<string, CriterionStatus>;
  autoFindings?: Record<string, string[]>;
}

export type CriterionStatus = 'verified' | 'partial' | 'untested' | 'deviation' | 'fails' | 'n/a' | 'library' | 'product';

interface Criterion {
  id: string;
  level: 'A' | 'AA';
  name: string;
  scope: 'component' | 'library' | 'product';
  note?: string;
  evidence?: string[];
  counts: Partial<Record<CriterionStatus, number>>;
}

const ROWS = matrix.components as A11yRow[];
const CRITERIA = matrix.criteria as Criterion[];
const CRITERION = new Map(CRITERIA.map((c) => [c.id, c]));

const EVIDENCE_LABEL: Record<string, string> = {
  axe: 'axe (CI)',
  keyboard: 'keyboard play test',
  reflow360: '360px overflow check (local run, not in CI yet)',
  auto: 'browser check (a11y-auto, local run)',
  reducedMotion: 'reduced-motion guard',
  screenReader: 'screen-reader pass',
  review: 'manual review',
};

/** Order and tone of the cell states, best first. */
const STATUS: { key: CriterionStatus; label: string; tone: StatusTone }[] = [
  { key: 'verified', label: 'Verified', tone: 'success' },
  { key: 'partial', label: 'Partly verified', tone: 'info' },
  { key: 'fails', label: 'Fails', tone: 'danger' },
  { key: 'deviation', label: 'Accepted deviation', tone: 'warning' },
  { key: 'untested', label: 'Not verified yet', tone: 'neutral' },
];

/** Storybook id of a title (same sanitizing Storybook uses). */
const sbId = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
/** Link from inside the preview iframe to a Storybook page: iframe.html sits next to the manager's index, so ./?path= reaches it; _top leaves the iframe. */
function SbLink({ path, children }: { path: string; children: ReactNode }) {
  return (
    <a className="text-[var(--color-text-text-link)] underline" href={`./?path=${path}`} target="_top">
      {children}
    </a>
  );
}

type Cell = { tone: StatusTone; label: string; detail?: ReactNode };

function axeCell(r: A11yRow): Cell {
  const ex = r.axe.exclusions.flatMap((e) => e.rules.map((rule) => `${rule} (${e.story === '*' ? 'all stories' : e.story})`));
  return {
    tone: ex.length ? 'warning' : 'success',
    label: `${r.axe.stories} × light + dark`,
    detail: ex.length ? <>Rule switched off, with the reason in the story: {ex.join(', ')}</> : 'Every story, both themes, no violations allowed (CI).',
  };
}
function keyboardCell(r: A11yRow): Cell {
  if (r.keyboard.tested) return { tone: 'success', label: `${r.keyboard.tested} play test${r.keyboard.tested > 1 ? 's' : ''}`, detail: `${r.keyboard.tested} of ${r.keyboard.playTests} interaction tests drive the keyboard.` };
  if (r.keyboard.playTests) return { tone: 'neutral', label: 'Pointer only', detail: `${r.keyboard.playTests} interaction test${r.keyboard.playTests > 1 ? 's' : ''}, none uses the keyboard.` };
  return { tone: 'neutral', label: 'No play test', detail: 'Rendered and checked by axe only.' };
}
function motionCell(r: A11yRow): Cell {
  if (r.reducedMotion === 'respected') return { tone: 'success', label: 'Respected', detail: 'Movement stops with prefers-reduced-motion.' };
  if (r.reducedMotion === 'unguarded') return { tone: 'danger', label: 'Not guarded', detail: <>Moves without a reduced-motion guard: {r.moving?.join(', ')}</> };
  return { tone: 'neutral', label: 'No motion', detail: 'Nothing moves in its own styles (color fades and the loading spinner aside).' };
}
function forcedCell(r: A11yRow): Cell {
  return r.forcedColors === 'component'
    ? { tone: 'success', label: 'Own rules', detail: 'Component-level forced-colors rules on top of the global ones.' }
    : { tone: 'success', label: 'Global rules', detail: 'Covered by the shared high-contrast stylesheet (focus, edges, selected states).' };
}
function srCell(r: A11yRow): Cell {
  if (!r.screenReader.length) return { tone: 'neutral', label: 'Not tested yet', detail: 'Roles and names are checked by axe; no pass with a real screen reader is recorded.' };
  const issues = r.screenReader.some((p) => p.result === 'issues');
  return {
    tone: issues ? 'warning' : 'success',
    label: r.screenReader.map((p) => p.at).join(', '),
    detail: r.screenReader.map((p) => `${p.at}${p.browser ? ` + ${p.browser}` : ''}, ${p.date}: ${p.result}${p.notes ? ` — ${p.notes}` : ''}`).join('; '),
  };
}
function deviationCell(r: A11yRow): Cell {
  if (!r.deviations.length) return { tone: 'success', label: 'None' };
  return { tone: 'warning', label: r.deviations.map((d) => d.criterion).join(', '), detail: r.deviations.map((d) => `${d.criterion}: ${d.note}`).join(' ') };
}

/** "12 verified · 6 partly · 9 not yet" over the criteria that apply to this component. */
function criteriaCell(r: A11yRow): Cell {
  const ids = Object.keys(r.wcag).filter((id) => STATUS.some((s) => s.key === r.wcag[id]));
  const count = (k: CriterionStatus) => ids.filter((id) => r.wcag[id] === k).length;
  const open = ids.filter((id) => r.wcag[id] === 'partial' || r.wcag[id] === 'untested' || r.wcag[id] === 'fails');
  return {
    tone: ids.some((id) => r.wcag[id] === 'fails') ? 'danger' : open.length ? 'neutral' : 'success',
    label: `${count('verified')} of ${ids.length} verified`,
    detail: open.length ? (
      <>
        Apply to this component: {ids.length} of 55. Still open:{' '}
        {open.map((id, i) => (
          <span key={id}>
            {i > 0 && ', '}
            {id} {CRITERION.get(id)?.name}
            {r.wcag[id] === 'partial' ? ' (partly)' : r.wcag[id] === 'fails' ? ` (fails: ${r.autoFindings?.[id]?.slice(0, 2).join('; ')})` : ''}
          </span>
        ))}
        .
      </>
    ) : (
      `All ${ids.length} criteria that apply are verified or listed as accepted deviations.`
    ),
  };
}

const COLUMNS: { key: string; label: string; cell: (r: A11yRow) => Cell }[] = [
  { key: 'criteria', label: 'WCAG 2.2 criteria', cell: criteriaCell },
  { key: 'axe', label: 'Automated (axe)', cell: axeCell },
  { key: 'keyboard', label: 'Keyboard', cell: keyboardCell },
  { key: 'motion', label: 'Reduced motion', cell: motionCell },
  { key: 'forced', label: 'High contrast', cell: forcedCell },
  { key: 'sr', label: 'Screen reader', cell: srCell },
  { key: 'deviations', label: 'Known deviations', cell: deviationCell },
];

/** Status block for one component's Docs page (by its Storybook title). */
export function A11yStatus({ title }: { title: string }) {
  const row = ROWS.find((r) => r.title === title);
  if (!row) return null;
  return (
    <div className="flex flex-col gap-2">
      <p className="m-0 font-body text-body-s text-[var(--color-text-text-subtle)]">
        Status against WCAG 2.2 AA, generated from the tests and the code. Full table:{' '}
        <SbLink path="/story/design-system-accessibility--matrix">Design System / Accessibility</SbLink>
        .
      </p>
      <dl className="m-0 grid grid-cols-1 gap-x-6 gap-y-3 sm:grid-cols-[max-content_1fr]">
        {COLUMNS.map((c) => {
          const v = c.cell(row);
          return (
            <div key={c.key} className="contents">
              <dt className="font-body text-body-m font-semibold text-[var(--color-text-text)]">{c.label}</dt>
              <dd className="m-0 flex min-w-0 flex-col items-start gap-1">
                <Badge tone={v.tone}>{v.label}</Badge>
                {v.detail && <span className="font-body text-body-s text-[var(--color-text-text-subtle)]">{v.detail}</span>}
              </dd>
            </div>
          );
        })}
      </dl>
    </div>
  );
}

type Filter = 'all' | 'deviations' | 'no-keyboard' | 'sr';

/** Full matrix: every component, one row each. */
export function A11yMatrixPage() {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<Filter>('all');
  const rows = useMemo(
    () =>
      ROWS.filter((r) => r.name.toLowerCase().includes(query.trim().toLowerCase())).filter((r) =>
        filter === 'deviations' ? r.deviations.length > 0 : filter === 'no-keyboard' ? r.keyboard.tested === 0 : filter === 'sr' ? r.screenReader.length > 0 : true,
      ),
    [query, filter],
  );
  const totals = {
    stories: ROWS.reduce((n, r) => n + r.axe.stories, 0),
    keyboard: ROWS.filter((r) => r.keyboard.tested > 0).length,
    deviations: ROWS.filter((r) => r.deviations.length > 0).length,
    sr: ROWS.filter((r) => r.screenReader.length > 0).length,
    unguarded: ROWS.filter((r) => r.reducedMotion === 'unguarded').length,
  };

  return (
    <div className="sb-unstyled flex max-w-[72rem] flex-col gap-6 font-body text-[var(--color-text-text)]">
      <header className="flex flex-col gap-2">
        <h1 className="m-0 font-heading text-heading-l">Accessibility</h1>
        <p className="m-0 max-w-[65ch] text-body-m text-[var(--color-text-text-subtle)]">
          Target: <strong>WCAG 2.2 AA</strong>, with accepted deviations listed below. The table is generated from the tests and the code on every
          change (<code>pnpm a11y</code>), so it can’t claim more than CI checks. Screen-reader passes and manual reviews are recorded by hand.
        </p>
        <p className="m-0 max-w-[65ch] text-body-m text-[var(--color-text-text-subtle)]">
          WCAG conformance belongs to a page or a product, not to a library: Theya’s components are built and tested to <em>support</em> WCAG 2.2 AA.
          Of the 55 A and AA criteria, the ones marked <em>Product</em> below are properties of the app (page titles, captions, navigation across pages)
          that a component can only help with.
        </p>
      </header>

      <dl className="m-0 grid grid-cols-2 gap-3 sm:grid-cols-5">
        {[
          [String(ROWS.length), 'components'],
          [`${totals.stories} × 2`, 'stories checked by axe, light + dark'],
          [`${totals.keyboard}`, 'with keyboard play tests'],
          [`${totals.deviations}`, 'with an accepted deviation'],
          [`${totals.sr}`, 'tested with a screen reader'],
        ].map(([n, l]) => (
          <div key={l} className="flex flex-col gap-0.5 rounded-[var(--size-border-radius-border-radius-xl)] border border-solid border-[var(--color-border-border-subtler)] p-3">
            <dt className="order-2 text-body-s text-[var(--color-text-text-subtle)]">{l}</dt>
            <dd className="order-1 m-0 font-heading text-heading-s tabular-nums">{n}</dd>
          </div>
        ))}
      </dl>

      <section className="flex flex-col gap-2">
        <h2 className="m-0 font-heading text-heading-xs">Library-wide</h2>
        <ul className="m-0 flex list-disc flex-col gap-1 pl-5 text-body-m">
          <li>
            <strong>Focus ring (1.4.11), accepted deviation.</strong> The soft ring is 1.53:1 on white and ~1.9:1 on dark surfaces (needs 3:1). Where it is the only
            visible focus change, the component lists 1.4.11. Fields, menus and outlined/ghost buttons also change border or background on focus and pass.
          </li>
          <li>
            <strong>Out of scope for a component library:</strong> page language and titles, consistent navigation, session timing — they need a real product around
            the components.
          </li>
          <li>
            <strong>Target size (2.5.8):</strong> controls are 28px and up (24px in compact density). axe’s target-size rule, off by default, is
            switched on in the test runner, so every story is measured.
          </li>
          {totals.unguarded > 0 && <li><strong>{totals.unguarded}</strong> component(s) still move without a reduced-motion guard — see the table.</li>}
        </ul>
      </section>

      <CriteriaTable />

      <h2 className="m-0 font-heading text-heading-xs">By component</h2>
      <div className="flex flex-wrap items-end gap-3">
        <TextField label="Find a component" value={query} onChange={(e) => setQuery(e.target.value)} className="w-64 max-w-full" />
        {/* The four filters are wider than a phone: the group wraps. */}
        <ToggleGroup type="single" appearance="outlined" size="sm" aria-label="Show" value={filter} onValueChange={(v) => v && setFilter(v as Filter)} className="max-w-full flex-wrap">
          <ToggleGroupItem value="all">All</ToggleGroupItem>
          <ToggleGroupItem value="deviations">With deviations</ToggleGroupItem>
          <ToggleGroupItem value="no-keyboard">No keyboard test</ToggleGroupItem>
          <ToggleGroupItem value="sr">Screen reader tested</ToggleGroupItem>
        </ToggleGroup>
      </div>

      <div className="overflow-x-auto rounded-[var(--size-border-radius-border-radius-2xl)] border border-solid border-[var(--color-border-border)]" role="region" aria-label="Accessibility matrix" tabIndex={0}>
        <table className="w-full border-collapse text-left text-body-s">
          <caption className="sr-only">Accessibility status per component, {rows.length} shown</caption>
          <thead>
            <tr className="bg-[var(--color-bg-neutral-bg-neutral-subtler)]">
              <th scope="col" className="px-3 py-2 font-semibold">Component</th>
              {COLUMNS.map((c) => (
                <th key={c.key} scope="col" className="px-3 py-2 font-semibold">{c.label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.name} className="border-t border-solid border-[var(--color-border-border-subtler)] align-top">
                <th scope="row" className="px-3 py-2 font-medium">
                  {r.title ? (
                    <SbLink path={`/docs/${sbId(r.title)}--docs`}>{r.name}</SbLink>
                  ) : (
                    r.name
                  )}
                </th>
                {COLUMNS.map((c) => {
                  const v = c.cell(r);
                  return (
                    <td key={c.key} className="px-3 py-2">
                      <Badge tone={v.tone} title={typeof v.detail === 'string' ? v.detail : undefined}>{v.label}</Badge>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className={cn('m-0 text-body-s text-[var(--color-text-text-subtle)]')}>
        Details for each cell are on the component’s Docs page, under Accessibility.
      </p>
    </div>
  );
}

/** One row per WCAG 2.2 A/AA criterion: how many components it applies to, and how far each is verified. */
function CriteriaTable() {
  const scopeLabel = { component: 'Per component', library: 'Library-wide', product: 'Product' } as const;
  return (
    <section className="flex flex-col gap-2">
      <h2 className="m-0 font-heading text-heading-xs">By criterion</h2>
      <p className="m-0 max-w-[65ch] text-body-s text-[var(--color-text-text-subtle)]">
        A cell counts as verified only when every kind of evidence the criterion needs exists; some of it makes it partly verified. Which criteria apply
        to a component is read from its code (inputs, overlays, timers, drag…).
      </p>
      <div className="overflow-x-auto rounded-[var(--size-border-radius-border-radius-2xl)] border border-solid border-[var(--color-border-border)]" role="region" aria-label="WCAG criteria" tabIndex={0}>
        <table className="w-full border-collapse text-left text-body-s">
          <caption className="sr-only">WCAG 2.2 A and AA criteria and how far Theya's components are verified against each</caption>
          <thead>
            <tr className="bg-[var(--color-bg-neutral-bg-neutral-subtler)]">
              <th scope="col" className="px-3 py-2 font-semibold">Criterion</th>
              <th scope="col" className="px-3 py-2 font-semibold">Level</th>
              <th scope="col" className="px-3 py-2 font-semibold">Scope</th>
              <th scope="col" className="px-3 py-2 font-semibold">Components</th>
              <th scope="col" className="px-3 py-2 font-semibold">Evidence it needs</th>
            </tr>
          </thead>
          <tbody>
            {CRITERIA.map((c) => {
              const applies = STATUS.reduce((n, s) => n + (c.counts[s.key] ?? 0), 0);
              return (
                <tr key={c.id} className="border-t border-solid border-[var(--color-border-border-subtler)] align-top">
                  <th scope="row" className="px-3 py-2 font-medium">
                    <span className="tabular-nums">{c.id}</span> {c.name}
                  </th>
                  <td className="px-3 py-2">{c.level}</td>
                  <td className="px-3 py-2">{scopeLabel[c.scope]}</td>
                  <td className="px-3 py-2">
                    {c.scope === 'component' ? (
                      <div className="flex flex-wrap gap-1">
                        {STATUS.filter((s) => c.counts[s.key]).map((s) => (
                          <Badge key={s.key} tone={s.tone}>
                            {s.label}: {c.counts[s.key]}
                          </Badge>
                        ))}
                        <span className="self-center text-[var(--color-text-text-subtle)]">of {applies}</span>
                      </div>
                    ) : (
                      <span className="text-[var(--color-text-text-subtle)]">{c.note}</span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-[var(--color-text-text-subtle)]">
                    {c.evidence?.length ? c.evidence.map((e) => EVIDENCE_LABEL[e] ?? e).join(' + ') : c.scope === 'component' ? 'Nothing automated yet' : '—'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}
