// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/accordion"

import * as AccordionPrimitive from '@radix-ui/react-accordion';
export interface AccordionSingleProps extends Omit<React.ComponentProps<typeof AccordionPrimitive.Root>, 'type'> {
    type: 'single';
    collapsible?: boolean;
}
export interface AccordionMultipleProps extends Omit<React.ComponentProps<typeof AccordionPrimitive.Root>, 'type'> {
    type: 'multiple';
}
export type AccordionProps = AccordionSingleProps | AccordionMultipleProps;
export declare function Accordion(props: AccordionProps): import("react").JSX.Element;
export declare function AccordionItem({ className, ...props }: React.ComponentProps<typeof AccordionPrimitive.Item>): import("react").JSX.Element;
export declare function AccordionTrigger({ className, children, ...props }: React.ComponentProps<typeof AccordionPrimitive.Trigger>): import("react").JSX.Element;
export declare function AccordionContent({ className, children, ...props }: React.ComponentProps<typeof AccordionPrimitive.Content>): import("react").JSX.Element;
