// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/alert"

export type AlertTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type AlertIndicator = 'none' | 'stripe';
export interface AlertProps extends React.ComponentProps<'div'> {
    tone?: AlertTone;
    indicator?: AlertIndicator;
    shadow?: boolean;
    live?: 'polite' | 'assertive';
    dismissible?: boolean;
    dismissLabel?: string;
    onDismiss?: () => void;
}
export declare function Alert({ className, tone, indicator, shadow, live, dismissible, dismissLabel, onDismiss, children, ...props }: AlertProps): import("react").JSX.Element;
export declare function AlertTitle({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function AlertDescription({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function AlertActions({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;

// Defaults
// Alert.dismissLabel = Dismiss (localized: alert.dismiss)
// Alert.dismissible = false
// Alert.indicator = none
// Alert.shadow = false
// Alert.tone = neutral
