// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/alert-dialog"

import * as AlertDialogPrimitive from '@radix-ui/react-alert-dialog';
import { type ButtonProps } from './button';
interface AlertDialogLayoutProps {
    titleSize?: 'md' | 'lg';
    showHeaderDivider?: boolean;
    showFooterDivider?: boolean;
    contentGap?: 'md' | 'sm' | 'none';
}
export declare function AlertDialog({ titleSize, showHeaderDivider, showFooterDivider, contentGap, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Root> & AlertDialogLayoutProps): import("react").JSX.Element;
export declare const AlertDialogTrigger: import("react").ForwardRefExoticComponent<AlertDialogPrimitive.AlertDialogTriggerProps & import("react").RefAttributes<HTMLButtonElement>>;
export declare const AlertDialogPortal: import("react").FC<AlertDialogPrimitive.AlertDialogPortalProps>;
export declare const AlertDialogOverlay: import("react").ForwardRefExoticComponent<Omit<AlertDialogPrimitive.AlertDialogOverlayProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("react").RefAttributes<HTMLDivElement>>;
export declare function AlertDialogContent({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Content>): import("react").JSX.Element;
export interface AlertDialogHeaderProps extends React.ComponentProps<'div'> {
    showDivider?: boolean;
    gap?: 'md' | 'sm' | 'none';
}
export declare function AlertDialogHeader({ className, showDivider, gap, ...props }: AlertDialogHeaderProps): import("react").JSX.Element;
export interface AlertDialogFooterProps extends React.ComponentProps<'div'> {
    showDivider?: boolean;
    gap?: 'md' | 'sm' | 'none';
}
export declare function AlertDialogFooter({ className, showDivider, gap, ...props }: AlertDialogFooterProps): import("react").JSX.Element;
export declare function AlertDialogTitle({ className, size, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Title> & {
    size?: 'md' | 'lg';
}): import("react").JSX.Element;
export interface AlertDialogBodyProps extends React.ComponentProps<'div'> {
    showDivider?: boolean;
}
export declare function AlertDialogBody({ className, showDivider, ...props }: AlertDialogBodyProps): import("react").JSX.Element;
export declare function AlertDialogDescription({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Description>): import("react").JSX.Element;
export declare function AlertDialogAction({ appearance, tone, ...props }: ButtonProps): import("react").JSX.Element;
export declare function AlertDialogCancel({ appearance, tone, ...props }: ButtonProps): import("react").JSX.Element;

// Defaults
// AlertDialog.contentGap = md
// AlertDialog.showFooterDivider = false
// AlertDialog.showHeaderDivider = false
// AlertDialog.titleSize = md
// AlertDialogAction.appearance = filled
// AlertDialogAction.tone = danger
// AlertDialogCancel.appearance = outlined
// AlertDialogCancel.tone = secondary
// AlertDialogFooter.gap = md
// AlertDialogHeader.gap = md
