// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/animated-icon"

export type AnimatedIconTrigger = 'hover' | 'active' | 'loop';
export interface AnimatedIconProps extends Omit<React.SVGProps<SVGSVGElement>, 'ref'> {
    trigger?: AnimatedIconTrigger;
    active?: boolean;
}
export declare const CheckAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const CopyAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const BellAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const SettingsAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const RefreshAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const TrashAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const EyeAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const ArrowRightAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const DownloadAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const UploadAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const PlusAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const HeartAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const MenuAnimated: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
export declare const ANIMATED_ICONS: {
    readonly Check: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Copy: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Bell: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Settings: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Refresh: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Trash: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Eye: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly ArrowRight: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Download: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Upload: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Plus: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Heart: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
    readonly Menu: import("react").ForwardRefExoticComponent<AnimatedIconProps & import("react").RefAttributes<SVGSVGElement>>;
};
export type AnimatedIconName = keyof typeof ANIMATED_ICONS;
export interface AnimatedIconByNameProps extends AnimatedIconProps {
    name: AnimatedIconName;
}
export declare const AnimatedIcon: import("react").ForwardRefExoticComponent<AnimatedIconByNameProps & import("react").RefAttributes<SVGSVGElement>>;

// Defaults
// AnimatedIcon.active = false
// AnimatedIcon.trigger = hover
// ArrowRightAnimated.active = false
// ArrowRightAnimated.trigger = hover
// BellAnimated.active = false
// BellAnimated.trigger = hover
// CheckAnimated.active = false
// CheckAnimated.trigger = hover
// CopyAnimated.active = false
// CopyAnimated.trigger = hover
// DownloadAnimated.active = false
// DownloadAnimated.trigger = hover
// EyeAnimated.active = false
// EyeAnimated.trigger = hover
// HeartAnimated.active = false
// HeartAnimated.trigger = hover
// MenuAnimated.active = false
// MenuAnimated.trigger = hover
// PlusAnimated.active = false
// PlusAnimated.trigger = hover
// RefreshAnimated.active = false
// RefreshAnimated.trigger = hover
// SettingsAnimated.active = false
// SettingsAnimated.trigger = hover
// TrashAnimated.active = false
// TrashAnimated.trigger = hover
// UploadAnimated.active = false
// UploadAnimated.trigger = hover
