// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/announcement-bar"

import { type ReactNode } from 'react';
export type AnnouncementBarTone = 'primary' | 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type AnnouncementBarAppearance = 'filled' | 'tonal';
export interface AnnouncementBarProps extends Omit<React.ComponentProps<'div'>, 'role'> {
    tone?: AnnouncementBarTone;
    appearance?: AnnouncementBarAppearance;
    icon?: ReactNode;
    dismissible?: boolean;
    dismissKey?: string;
    onDismiss?: () => void;
    dismissLabel?: string;
    sticky?: boolean;
    'aria-label'?: string;
}
export declare function AnnouncementBar({ tone, appearance, icon, dismissible, dismissKey, onDismiss, dismissLabel, sticky, className, children, 'aria-label': ariaLabel, ...props }: AnnouncementBarProps): import("react").JSX.Element | null;

// Defaults
// AnnouncementBar.appearance = filled
// AnnouncementBar.dismissLabel = Dismiss announcement (localized: announcementBar.dismiss)
// AnnouncementBar.dismissible = false
// AnnouncementBar.sticky = false
// AnnouncementBar.tone = primary
