// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/area-chart"

export interface AreaChartPoint {
    label: string;
    value: number;
}
export interface AreaChartSeries {
    key: string;
    name: string;
}
export type AreaChartMultiPoint = {
    label: string;
} & Record<string, string | number>;
export interface AreaChartProps {
    data: AreaChartPoint[] | AreaChartMultiPoint[];
    series?: AreaChartSeries[];
    stacked?: boolean;
    legend?: boolean;
    height?: number;
    yStep?: number;
    unit?: string;
    labelPrefix?: string;
    format?: (v: number) => string;
    showXAxis?: boolean;
    showYAxis?: boolean;
    floatingAxis?: boolean;
    loading?: boolean;
    ariaLabel?: string;
    className?: string;
}
export declare function AreaChart({ data, series, stacked, legend, height, yStep, unit, labelPrefix, format, showXAxis, showYAxis, floatingAxis, loading, ariaLabel, className, }: AreaChartProps): import("react").JSX.Element;

// Defaults
// AreaChart.floatingAxis = false
// AreaChart.height = 240
// AreaChart.labelPrefix = 
// AreaChart.legend = true
// AreaChart.loading = false
// AreaChart.showXAxis = true
// AreaChart.showYAxis = true
// AreaChart.stacked = true
// AreaChart.unit = 
// AreaChart.yStep = 1
