// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/aspect-ratio"

export interface AspectRatioProps extends React.ComponentProps<'div'> {
    ratio?: number;
}
export declare function AspectRatio({ ratio, className, style, children, ...props }: AspectRatioProps): import("react").JSX.Element;

// Defaults
// AspectRatio.ratio = 16 / 9
