// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/attachment"

import { type ReactNode } from 'react';
export declare const ATTACHMENT_MIME_LABELS: Record<string, string>;
export interface AttachmentProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'className' | 'onClick'> {
    onClick?: () => void;
    name: string;
    size?: number;
    metaText?: ReactNode;
    variant?: 'pill' | 'card' | 'row' | 'line';
    type?: string;
    error?: string;
    showKind?: boolean;
    showMeta?: boolean;
    selected?: boolean;
    previewUrl?: string;
    href?: string;
    mimeLabels?: Record<string, string>;
    onRemove?: () => void;
    removeLabel?: string;
    clickHint?: string;
    actions?: ReactNode;
    className?: string;
}
declare function humanSize(bytes: number): string;
export declare function Attachment({ name, size, metaText, variant, type, error, showKind, showMeta, selected, previewUrl, href, mimeLabels, onRemove, removeLabel, clickHint, actions, className, onClick, 'aria-pressed': ariaPressed, ...rest }: AttachmentProps): import("react").JSX.Element;
export { humanSize };

// Defaults
// Attachment.mimeLabels = {
  'image/png': 'PNG image',
  'image/jpeg': 'JPEG image',
  'application/pdf': 'PDF',
  'application/zip': 'ZIP archive',
  'text/plain': 'Text file',
  'video/mp4': 'MP4 video',
}
// Attachment.selected = false
// Attachment.showKind = false
// Attachment.showMeta = true
// Attachment.variant = pill
