// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/autocomplete"

import type { ReactNode } from 'react';
export interface AutocompleteOption {
    value: string;
    label: ReactNode;
    note?: ReactNode;
}
export interface AutocompleteProps {
    options: AutocompleteOption[];
    heightSize?: 'md' | 'sm';
    placeholder?: string;
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    emptyMessage?: string;
    loading?: boolean;
    loadingMessage?: string;
    disableFilter?: boolean;
    showClear?: boolean;
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    id?: string;
    name?: string;
    className?: string;
    contentClassName?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
}
export declare function Autocomplete({ options, heightSize, placeholder, value, defaultValue, onValueChange, emptyMessage, loading, loadingMessage, disableFilter, showClear, disabled, readOnly, required, id, name, className, contentClassName, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, 'aria-invalid': ariaInvalid, 'aria-describedby': ariaDescribedby, }: AutocompleteProps): import("react").JSX.Element;

// Defaults
// Autocomplete.disableFilter = false
// Autocomplete.emptyMessage = No results. (localized: common.noResults)
// Autocomplete.heightSize = md
// Autocomplete.loading = false
// Autocomplete.loadingMessage = Loading… (localized: common.loading)
// Autocomplete.showClear = true
