// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/avatar"

import * as AvatarPrimitive from '@radix-ui/react-avatar';
import type { ReactNode } from 'react';
import type { BadgeIndicatorProps } from './badge-indicator';
export type AvatarSize = 'sm' | 'md' | 'lg';
export type AvatarShape = 'circle' | 'square';
export type AvatarAppearance = 'tonal' | 'filled';
export type AvatarOutline = 'none' | 'solid' | 'gradient';
export type AvatarContentType = 'icon' | 'image' | 'text';
export interface AvatarProps extends React.ComponentProps<typeof AvatarPrimitive.Root> {
    size?: AvatarSize;
    shape?: AvatarShape;
    outline?: AvatarOutline;
    separator?: boolean;
    type?: AvatarContentType;
    initials?: ReactNode;
    icon?: ReactNode;
    src?: string;
    alt?: string;
    fallback?: ReactNode;
    appearance?: AvatarAppearance;
}
export declare function Avatar({ className, style, size, shape, outline, separator, type, initials, icon, src, alt, fallback, appearance, children, ...props }: AvatarProps): import("react").JSX.Element;
export declare function AvatarImage({ className, style, ...props }: React.ComponentProps<typeof AvatarPrimitive.Image>): import("react").JSX.Element;
export interface AvatarFallbackProps extends React.ComponentProps<typeof AvatarPrimitive.Fallback> {
    appearance?: AvatarAppearance;
}
export declare function AvatarFallback({ className, style, appearance, delayMs, ...props }: AvatarFallbackProps): import("react").JSX.Element;
export interface AvatarBadgeProps extends Omit<BadgeIndicatorProps, 'value'> {
    children?: ReactNode;
    value?: ReactNode;
    separator?: boolean;
}
export declare function AvatarBadge({ className, style, separator, size, appearance, shape, tone, children, value, ...props }: AvatarBadgeProps): import("react").JSX.Element;

// Defaults
// Avatar.appearance = tonal
// Avatar.outline = gradient
// Avatar.separator = true
// Avatar.shape = circle
// Avatar.size = sm
// AvatarBadge.appearance = filled
// AvatarBadge.separator = true
// AvatarBadge.shape = circle
// AvatarBadge.size = sm
// AvatarBadge.tone = danger
// AvatarFallback.appearance = tonal
