// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/avatar-group"

import type { AvatarSize } from './avatar';
export interface AvatarGroupProps extends React.ComponentProps<'div'> {
    max?: number;
    size?: AvatarSize;
}
export declare function AvatarGroup({ children, max, size, className, ...props }: AvatarGroupProps): import("react").JSX.Element;

// Defaults
// AvatarGroup.size = sm
