// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/badge-indicator"

import { type ReactNode } from 'react';
export type BadgeIndicatorTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type BadgeIndicatorAppearance = 'filled' | 'outlined';
export type BadgeIndicatorShape = 'circle' | 'square';
export type BadgeIndicatorSize = 'sm' | 'md';
export interface BadgeIndicatorProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'children'> {
    value?: ReactNode;
    dot?: boolean;
    icon?: ReactNode;
    appearance?: BadgeIndicatorAppearance;
    shape?: BadgeIndicatorShape;
    tone?: BadgeIndicatorTone;
    size?: BadgeIndicatorSize;
    pulse?: boolean;
    pulseKey?: string | number;
}
export declare function BadgeIndicator({ value, dot, icon, appearance, shape, tone, size, pulse, pulseKey, className, style, ...props }: BadgeIndicatorProps): import("react").JSX.Element;

// Defaults
// BadgeIndicator.appearance = filled
// BadgeIndicator.dot = false
// BadgeIndicator.pulse = false
// BadgeIndicator.shape = circle
// BadgeIndicator.size = sm
// BadgeIndicator.tone = neutral
