// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/badge"

import type { StatusTone } from './status-dot';
export type BadgeTone = StatusTone;
export type BadgeAppearance = 'tonal' | 'filled';
export type BadgeSize = 'sm' | 'md';
export interface BadgeProps extends React.ComponentProps<'span'> {
    tone?: BadgeTone;
    appearance?: BadgeAppearance;
    size?: BadgeSize;
    asChild?: boolean;
}
export declare function Badge({ className, tone, appearance, size, asChild, ...props }: BadgeProps): import("react").JSX.Element;
export declare function statusToneToBadgeTone(tone: StatusTone): BadgeTone;

// Defaults
// Badge.appearance = tonal
// Badge.asChild = false
// Badge.size = sm
// Badge.tone = neutral
