// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/bar-chart"

export interface BarChartPoint {
    label: string;
    value: number;
}
export interface BarChartProps {
    data: BarChartPoint[];
    orientation?: 'vertical' | 'horizontal';
    height?: number;
    valueStep?: number;
    unit?: string;
    labelPrefix?: string;
    format?: (v: number) => string;
    ariaLabel?: string;
    className?: string;
}
export declare function BarChart({ data, orientation, height, valueStep, unit, labelPrefix, format, ariaLabel, className }: BarChartProps): import("react").JSX.Element;

// Defaults
// BarChart.height = 240
// BarChart.labelPrefix = 
// BarChart.orientation = vertical
// BarChart.unit = 
// BarChart.valueStep = 1
