// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/breadcrumb"

import type { ReactNode } from 'react';
export declare function Breadcrumb(props: React.ComponentProps<'nav'>): import("react").JSX.Element;
export declare function BreadcrumbList({ className, ...props }: React.ComponentProps<'ol'>): import("react").JSX.Element;
export declare function BreadcrumbItem({ className, ...props }: React.ComponentProps<'li'>): import("react").JSX.Element;
export declare function BreadcrumbLink({ className, asChild, icon, children, ...props }: React.ComponentProps<'a'> & {
    asChild?: boolean;
    icon?: ReactNode;
}): import("react").JSX.Element;
export declare function BreadcrumbPage({ className, icon, children, ...props }: React.ComponentProps<'span'> & {
    icon?: ReactNode;
}): import("react").JSX.Element;
export declare function BreadcrumbSeparator({ children, className, ...props }: React.ComponentProps<'li'>): import("react").JSX.Element;
export interface BreadcrumbEllipsisProps extends React.ComponentProps<'span'> {
    items?: {
        label: string;
        href: string;
    }[];
}
export declare function BreadcrumbEllipsis({ className, items, ...props }: BreadcrumbEllipsisProps): import("react").JSX.Element;
