// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/button"

import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { type VariantProps } from 'class-variance-authority';
import { type BadgeIndicatorTone } from './badge-indicator';
export declare const buttonVariants: (props?: ({
    appearance?: "filled" | "outlined" | "tonal" | "ghost" | null | undefined;
    tone?: "warning" | "neutral" | "info" | "success" | "danger" | "primary" | "secondary" | null | undefined;
    size?: "sm" | "md" | "lg" | "xl" | "2xl" | null | undefined;
    fullWidth?: boolean | null | undefined;
    iconOnly?: boolean | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface ButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'color'>, VariantProps<typeof buttonVariants> {
    iconOnly?: boolean;
    leftIcon?: ReactNode;
    rightIcon?: ReactNode;
    asChild?: boolean;
    loading?: boolean;
    success?: boolean;
    softDisabled?: boolean;
    badge?: ReactNode | ButtonBadge;
    badgeLabel?: string;
    children?: ReactNode;
}
export interface ButtonBadge {
    value?: ReactNode;
    dot?: boolean;
    tone?: BadgeIndicatorTone;
}
export declare const Button: import("react").ForwardRefExoticComponent<ButtonProps & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// Button.appearance = filled
// Button.asChild = false
// Button.fullWidth = false
// Button.iconOnly = false
// Button.loading = false
// Button.size = xl
// Button.softDisabled = false
// Button.success = false
// Button.tone = primary
