// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/calendar"

import { DayPicker } from 'react-day-picker';
export declare function Calendar({ className, classNames, showOutsideDays, captionLayout, components, ...props }: React.ComponentProps<typeof DayPicker>): import("react").JSX.Element;
