// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/card"

import type { AvatarProps } from './avatar';
export type CardTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type CardSize = 'sm' | 'md' | 'lg';
export type CardPrimaryAction = {
    type: 'link';
    href: string;
    ariaLabel?: string;
} | {
    type: 'external-link';
    href: string;
    ariaLabel?: string;
} | {
    type: 'filter';
    active: boolean;
    onChange: (active: boolean) => void;
    ariaLabel: string;
};
export type CardSelectable = 'radio' | 'checkbox';
export type CardAppearance = 'outlined' | 'filled';
export interface CardProps extends React.ComponentProps<'div'> {
    size?: CardSize;
    tone?: CardTone;
    appearance?: CardAppearance;
    interactive?: boolean;
    action?: CardPrimaryAction;
    href?: string;
    disabled?: boolean;
    selectable?: CardSelectable;
    selected?: boolean;
    onSelectedChange?: (selected: boolean) => void;
    selectLabel?: string;
    effect?: CardEffect;
}
export type CardEffect = 'tilt' | 'spotlight' | 'lift';
export declare function Card({ className, size, tone: toneProp, appearance, action, href, interactive, disabled, selectable, selected, onSelectedChange, selectLabel, effect: effectProp, children, onPointerMove, onPointerLeave, ...props }: CardProps): import("react").JSX.Element;
export declare function CardHeader({ className, divider, size, ...props }: React.ComponentProps<'div'> & {
    divider?: boolean;
    size?: 'sm' | 'md';
}): import("react").JSX.Element;
export declare function CardTitle({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CardDescription({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export interface CardLinkProps extends React.ComponentProps<'a'> {
    asChild?: boolean;
}
export declare function CardLink({ className, asChild, ...props }: CardLinkProps): import("react").JSX.Element;
export declare function CardContent({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CardAction({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CardFooter({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export interface CardMediaProps extends React.ComponentProps<'img'> {
    height?: number | string;
}
export declare function CardMedia({ className, height, style, alt, ...props }: CardMediaProps): import("react").JSX.Element;
export interface CardAvatarProps extends AvatarProps {
}
export declare function CardAvatar({ className, size, outline, ...props }: CardAvatarProps): import("react").JSX.Element;

// Defaults
// Card.appearance = outlined
// Card.disabled = false
// Card.interactive = false
// Card.selected = false
// Card.tone = neutral
// CardAvatar.outline = solid
// CardAvatar.size = lg
// CardLink.asChild = false
// CardMedia.height = 180
