// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/card-stack"

export interface CardStackProps extends React.HTMLAttributes<HTMLDivElement> {
    interval?: number;
    depth?: number;
    hideControls?: boolean;
    layout?: 'stack' | 'fan';
}
export declare function CardStack({ interval, depth, hideControls, layout, className, children, onPointerEnter, onPointerLeave, onFocus, onBlur, ...props }: CardStackProps): import("react").JSX.Element;

// Defaults
// CardStack.depth = 2
// CardStack.hideControls = false
// CardStack.interval = 4000
// CardStack.layout = stack
