// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/card-fan"

export interface CardFanProps extends React.HTMLAttributes<HTMLDivElement> {
    spread?: number;
    offset?: number;
}
export declare function CardFan({ spread, offset, className, children, onPointerEnter, onPointerLeave, onFocus, onBlur, onClick, ...props }: CardFanProps): import("react").JSX.Element;

// Defaults
// CardFan.offset = 88
// CardFan.spread = 8
