// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/carousel"

import useEmblaCarousel, { type UseEmblaCarouselType } from 'embla-carousel-react';
import { Button } from './button';
export type CarouselApi = UseEmblaCarouselType[1];
type UseCarouselParameters = Parameters<typeof useEmblaCarousel>;
type CarouselOptions = UseCarouselParameters[0];
type CarouselPlugin = UseCarouselParameters[1];
export interface CarouselProps extends React.ComponentProps<'div'> {
    orientation?: 'horizontal' | 'vertical';
    opts?: CarouselOptions;
    plugins?: CarouselPlugin;
    setApi?: (api: CarouselApi) => void;
    peek?: boolean;
}
interface CarouselContextValue {
    carouselRef: UseEmblaCarouselType[0];
    api: CarouselApi;
    scrollPrev: () => void;
    scrollNext: () => void;
    canScrollPrev: boolean;
    canScrollNext: boolean;
    orientation: 'horizontal' | 'vertical';
    peek: boolean;
}
export declare function useCarousel(): CarouselContextValue;
export declare function Carousel({ orientation, opts, setApi, plugins, peek, className, children, ...props }: CarouselProps): import("react").JSX.Element;
export declare function CarouselContent({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CarouselItem({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CarouselPrevious({ className, ...props }: React.ComponentProps<typeof Button>): import("react").JSX.Element;
export interface CarouselIndicatorsProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    variant?: 'default' | 'on-dark';
}
export declare function CarouselIndicators({ className, variant, ...props }: CarouselIndicatorsProps): import("react").JSX.Element | null;
export declare function CarouselNext({ className, ...props }: React.ComponentProps<typeof Button>): import("react").JSX.Element;

// Defaults
// Carousel.orientation = horizontal
// Carousel.peek = false
// CarouselIndicators.variant = default
