// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/chart-range-selection"

import type { ReactElement, ReactNode } from 'react';
export interface ChartSelectionRange {
    from: string;
    to: string;
}
interface RechartsPointerState {
    activeLabel?: string | number;
}
interface SelectableChartProps {
    children?: ReactNode;
    onMouseDown?: (state: RechartsPointerState) => void;
    onMouseMove?: (state: RechartsPointerState) => void;
    onMouseUp?: () => void;
    onMouseLeave?: () => void;
}
export interface ChartRangeSelectionProps {
    children: ReactElement<SelectableChartProps>;
    labels: ReadonlyArray<string | number>;
    height?: number;
    selectedRange?: ChartSelectionRange | null;
    onRangeChange?: (range: ChartSelectionRange | null) => void;
    disabled?: boolean;
    'aria-label'?: string;
    className?: string;
}
export declare function ChartRangeSelection({ children, labels, height, selectedRange, onRangeChange, disabled, 'aria-label': ariaLabel, className, }: ChartRangeSelectionProps): import("react").JSX.Element;

// Defaults
// ChartRangeSelection.disabled = false
// ChartRangeSelection.height = 240
