// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/chat"

export declare function Chat({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function ChatMessages({ className, tabIndex, 'aria-label': ariaLabel, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function ChatTyping({ label, avatar, className, ...props }: React.ComponentProps<'div'> & {
    label?: string;
    avatar?: React.ReactNode;
}): import("react").JSX.Element;
