// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/checkbox-group"

import type { ReactNode } from 'react';
import { type CheckboxProps } from './checkbox';
export interface CheckboxGroupProps {
    defaultValue?: string[];
    value?: string[];
    onValueChange?: (value: string[]) => void;
    disabled?: boolean;
    size?: 'sm' | 'md';
    label?: ReactNode;
    children: ReactNode;
    className?: string;
}
export declare function CheckboxGroup({ defaultValue, value, onValueChange, disabled, size, label, children, className, }: CheckboxGroupProps): import("react").JSX.Element;
export interface CheckboxGroupItemProps extends Omit<CheckboxProps, 'checked' | 'onCheckedChange' | 'name'> {
    name: string;
}
export declare function CheckboxGroupItem({ name, disabled, size, ...props }: CheckboxGroupItemProps): import("react").JSX.Element;

// Defaults
// CheckboxGroup.size = md
