// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/checkbox"

import type { ComponentPropsWithoutRef, ReactNode } from 'react';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import { type VariantProps } from 'class-variance-authority';
declare const checkboxVariants: (props?: ({
    size?: "sm" | "md" | null | undefined;
    error?: boolean | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface CheckboxProps extends Omit<ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>, 'checked'>, VariantProps<typeof checkboxVariants> {
    indeterminate?: boolean;
    checked?: boolean | 'indeterminate';
    label?: ReactNode;
    description?: ReactNode;
}
export declare const Checkbox: import("react").ForwardRefExoticComponent<CheckboxProps & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// Checkbox.error = false
// Checkbox.indeterminate = false
// Checkbox.size = md
