// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/chip"

import type { ReactNode } from 'react';
import type { StatusTone } from './status-dot';
export type ChipTone = StatusTone;
export type ChipAppearance = 'tonal' | 'filled';
export type ChipSize = 'sm' | 'md' | 'lg';
export declare const SOLID_TONE_CLASS: Record<ChipTone, string>;
export interface ChipProps extends Omit<React.ComponentProps<'span'>, 'onClick' | 'onKeyDown'> {
    tone?: ChipTone;
    appearance?: ChipAppearance;
    bordered?: boolean;
    size?: ChipSize;
    icon?: ReactNode;
    interactive?: boolean;
    toggleable?: boolean;
    asChild?: boolean;
    pressed?: boolean;
    defaultPressed?: boolean;
    onPressedChange?: (pressed: boolean) => void;
    disabled?: boolean;
    onClick?: React.MouseEventHandler<HTMLElement>;
    onKeyDown?: React.KeyboardEventHandler<HTMLElement>;
}
export declare function Chip({ className, tone, appearance, bordered, size, icon, interactive, toggleable, pressed, defaultPressed, onPressedChange, asChild, disabled, onClick, onKeyDown, children, ...props }: ChipProps): import("react").JSX.Element;
export declare const ChipRemove: import("react").ForwardRefExoticComponent<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// Chip.appearance = tonal
// Chip.asChild = false
// Chip.bordered = false
// Chip.interactive = true
// Chip.size = md
// Chip.toggleable = true
// Chip.tone = neutral
