// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/code-block"

export interface CodeBlockProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    code: string;
    language?: string;
    filename?: string;
    copy?: boolean;
    copyLabel?: string;
}
export declare function CodeBlock({ code, language, filename, copy, copyLabel, className, ...props }: CodeBlockProps): import("react").JSX.Element;

// Defaults
// CodeBlock.copy = true
// CodeBlock.copyLabel = Copy code (localized: codeBlock.copy)
