// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/code-editor"

import { type Extension } from '@codemirror/state';
export interface CodeEditorProps extends Omit<React.ComponentProps<'div'>, 'onChange' | 'defaultValue' | 'value'> {
    value?: string;
    defaultValue?: string;
    onChange?: (value: string) => void;
    extensions?: Extension[];
    readOnly?: boolean;
    disabled?: boolean;
    placeholder?: string;
    minHeight?: string;
    maxHeight?: string;
    filename?: string;
    language?: string;
    copy?: boolean;
    copyLabel?: string;
    clearable?: boolean;
    clearLabel?: string;
    inverse?: boolean;
}
export declare function CodeEditor({ value, defaultValue, onChange, extensions, readOnly, disabled, placeholder, minHeight, maxHeight, id, filename, language, copy, copyLabel, clearable, clearLabel, inverse, className, 'aria-label': ariaLabel, ...props }: CodeEditorProps): import("react").JSX.Element;

// Defaults
// CodeEditor.clearLabel = Clear (localized: common.clear)
// CodeEditor.clearable = false
// CodeEditor.copy = false
// CodeEditor.copyLabel = Copy code (localized: codeBlock.copy)
// CodeEditor.disabled = false
// CodeEditor.extensions = []
// CodeEditor.inverse = false
// CodeEditor.minHeight = 8rem
// CodeEditor.readOnly = false
