// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/color-picker"

export interface Hsva {
    h: number;
    s: number;
    v: number;
    a: number;
}
interface Rgba {
    r: number;
    g: number;
    b: number;
    a: number;
}
export declare function parseHex(input: string): Rgba | null;
export type ColorFormat = 'hex' | 'rgb' | 'hsl';
export type ColorPickerView = 'palette' | 'photo' | 'custom';
export interface ColorPickerProps extends Omit<React.ComponentProps<'div'>, 'defaultValue' | 'onChange'> {
    value?: string;
    defaultValue?: string;
    onValueChange?: (hex: string) => void;
    onValueCommit?: (hex: string) => void;
    alpha?: boolean;
    formats?: ColorFormat[];
    defaultFormat?: ColorFormat;
    views?: ColorPickerView[];
    defaultView?: ColorPickerView;
    swatches?: string[];
    clearable?: boolean;
    photo?: string;
    eyeDropper?: boolean;
    viewLabels?: Partial<Record<ColorPickerView, string>>;
}
export declare function ColorPicker({ value, defaultValue, onValueChange, onValueCommit, alpha, formats, defaultFormat, views: viewsProp, defaultView, swatches, clearable, photo, eyeDropper, viewLabels, className, ...props }: ColorPickerProps): import("react").JSX.Element;
export interface ColorFieldProps extends Omit<ColorPickerProps, 'className'> {
    label?: React.ReactNode;
    description?: React.ReactNode;
    heightSize?: 'sm' | 'md' | 'lg';
    className?: string;
    disabled?: boolean;
    name?: string;
}
export declare function ColorField({ label, description, heightSize, className, disabled, name, value, defaultValue, onValueChange, onValueCommit, alpha, ...pickerProps }: ColorFieldProps): import("react").JSX.Element;

// Defaults
// ColorField.alpha = false
// ColorField.defaultValue = #3b6fd6
// ColorField.heightSize = md
// ColorPicker.alpha = false
// ColorPicker.clearable = false
// ColorPicker.defaultValue = #3b6fd6
// ColorPicker.eyeDropper = true
// ColorPicker.formats = ['hex', 'rgb', 'hsl']
