// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/column-page-dots"

export declare function ColumnPageDots({ pageCount, page, perPage, columnCount, onPageChange, className, }: {
    pageCount: number;
    page: number;
    perPage: number;
    columnCount: number;
    onPageChange: (page: number) => void;
    className?: string;
}): import("react").JSX.Element | null;
export declare function columnSwipeHandlers(page: number, pageCount: number, setPage: (page: number) => void): {
    onTouchStart: (event: React.TouchEvent) => void;
    onTouchEnd: (event: React.TouchEvent) => void;
};
