// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/combobox"

import type { ReactNode } from 'react';
export interface ComboboxOption {
    value: string;
    label: string;
    keywords?: string[];
    disabled?: boolean;
}
interface ComboboxCommonProps {
    options: ComboboxOption[];
    heightSize?: 'md' | 'sm';
    placeholder?: string;
    emptyMessage?: ReactNode;
    loading?: boolean;
    loadingMessage?: ReactNode;
    allowCreate?: boolean;
    createOnDelimiter?: boolean;
    createOptionLabel?: (query: string) => ReactNode;
    createOptionIcon?: ReactNode;
    clearLabel?: string;
    chevronLabel?: string;
    showClear?: boolean;
    showChevron?: boolean;
    disabled?: boolean;
    readOnly?: boolean;
    id?: string;
    className?: string;
    contentClassName?: string;
    renderOption?: (option: ComboboxOption) => ReactNode;
    renderChip?: (option: ComboboxOption) => ReactNode;
    filter?: (option: ComboboxOption, query: string) => boolean;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
}
export type ComboboxSingleProps = ComboboxCommonProps & {
    multiple?: false;
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
};
export type ComboboxMultipleProps = ComboboxCommonProps & {
    multiple: true;
    value?: string[];
    defaultValue?: string[];
    onValueChange?: (value: string[]) => void;
};
export type ComboboxProps = ComboboxSingleProps | ComboboxMultipleProps;
export declare function Combobox(props: ComboboxProps): import("react").JSX.Element;

// Defaults
// Combobox.chevronLabel = Open options (localized: combobox.open)
// Combobox.clearLabel = Clear selection (localized: combobox.clear)
// Combobox.createOptionLabel = localized: combobox.create
// Combobox.emptyMessage = No results. (localized: common.noResults)
// Combobox.loadingMessage = Loading… (localized: common.loading)
// Combobox.placeholder = Select… (localized: combobox.placeholder)
