// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/command"

import type { ReactNode } from 'react';
import { Dialog } from './dialog';
import type { StatusTone } from './status-dot';
export interface CommandProps extends Omit<React.ComponentProps<'div'>, 'onChange'> {
    label?: string;
    shouldFilter?: boolean;
    loading?: boolean;
}
export declare function Command({ className, label, shouldFilter, loading, children, ...props }: CommandProps): import("react").JSX.Element;
export interface CommandDialogProps extends Omit<React.ComponentProps<typeof Dialog>, 'children'> {
    title?: string;
    description?: string;
    className?: string;
    children?: ReactNode;
}
export declare function CommandDialog({ title, description, children, className, ...props }: CommandDialogProps): import("react").JSX.Element;
export interface CommandInputProps extends Omit<React.ComponentProps<'input'>, 'value' | 'onChange'> {
    value?: string;
    onValueChange?: (value: string) => void;
}
export declare function CommandInput({ className, value, onValueChange, ...props }: CommandInputProps): import("react").JSX.Element;
export declare function CommandList({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function CommandEmpty({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element | null;
export declare function CommandLoading({ className, children, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element | null;
export interface CommandGroupProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    heading?: ReactNode;
    children?: ReactNode;
}
export declare function CommandGroup({ className, heading, children, ...props }: CommandGroupProps): import("react").JSX.Element;
export declare function CommandSeparator({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export interface CommandItemProps extends Omit<React.ComponentProps<'div'>, 'value' | 'onClick' | 'onSelect'> {
    value?: string;
    keywords?: string[];
    onSelect?: (value: string) => void;
    disabled?: boolean;
    icon?: ReactNode;
    toneIcon?: {
        tone: StatusTone;
        icon?: ReactNode;
        shape?: 'circle' | 'square';
    };
    description?: ReactNode;
    breadcrumb?: ReactNode;
}
export declare function CommandItem({ className, value, keywords, onSelect, disabled, icon, toneIcon, description, breadcrumb, children, ...props }: CommandItemProps): import("react").JSX.Element | null;
export declare function CommandShortcut({ className, ...props }: React.ComponentProps<'span'>): import("react").JSX.Element;
export declare function CommandFooter({ className, children, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;

// Defaults
// Command.loading = false
// Command.shouldFilter = true
// CommandDialog.description = Search for pages and actions, or run a command. (localized: command.description)
// CommandDialog.title = Command palette (localized: command.title)
// CommandItem.description = Search for pages and actions, or run a command. (localized: command.description)
