// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/confirm-dialog"

import type { ReactNode } from 'react';
export interface ConfirmDialogProps {
    title: ReactNode;
    titleSize?: 'md' | 'lg';
    description?: ReactNode;
    showHeaderDivider?: boolean;
    showFooterDivider?: boolean;
    contentGap?: 'md' | 'sm' | 'none';
    confirmValue?: string;
    confirmValueMono?: boolean;
    confirmLabel?: string;
    cancelLabel?: string;
    tone?: 'danger' | 'neutral';
    confirmIcon?: ReactNode;
    onConfirm?: () => void;
    trigger?: ReactNode;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    children?: ReactNode;
}
export declare function ConfirmDialog({ title, titleSize, description, showHeaderDivider, showFooterDivider, contentGap, confirmValue, confirmValueMono, confirmLabel, cancelLabel, tone, confirmIcon, onConfirm, trigger, open, onOpenChange, children, }: ConfirmDialogProps): import("react").JSX.Element;

// Defaults
// ConfirmDialog.cancelLabel = Cancel (localized: common.cancel)
// ConfirmDialog.confirmLabel = Delete (localized: confirmDialog.confirm)
// ConfirmDialog.confirmValueMono = true
// ConfirmDialog.contentGap = md
// ConfirmDialog.titleSize = md
// ConfirmDialog.tone = danger
