// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/copy-button"

import type { ReactNode } from 'react';
import { type ButtonProps } from './button';
export interface CopyButtonProps extends Omit<ButtonProps, 'children' | 'loading' | 'leftIcon' | 'rightIcon'> {
    value: string;
    label?: ReactNode;
    copiedLabel?: ReactNode;
    resetDelay?: number;
    onCopied?: (value: string) => void;
    onCopyError?: (error: unknown) => void;
}
export declare const CopyButton: import("react").ForwardRefExoticComponent<CopyButtonProps & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// CopyButton.appearance = tonal
// CopyButton.copiedLabel = Copied (localized: copyButton.copied)
// CopyButton.label = Copy (localized: copyButton.copy)
// CopyButton.resetDelay = 1500
// CopyButton.size = md
// CopyButton.tone = neutral
