// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/count-up"

export interface CountUpProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'children'> {
    to: number;
    from?: number;
    duration?: number;
    format?: Intl.NumberFormatOptions;
    prefix?: string;
    suffix?: string;
}
export declare function CountUp({ to, from, duration, format, prefix, suffix, className, ...props }: CountUpProps): import("react").JSX.Element;

// Defaults
// CountUp.duration = 1400
// CountUp.from = 0
// CountUp.prefix = 
// CountUp.suffix = 
