// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/countdown"

import { type VariantProps } from 'class-variance-authority';
export type CountdownUnit = 'days' | 'hours' | 'minutes' | 'seconds';
export interface CountdownParts {
    total: number;
    days: number;
    hours: number;
    minutes: number;
    seconds: number;
    done: boolean;
}
export interface UseCountdownOptions {
    precision?: 'seconds' | 'minutes';
    onComplete?: () => void;
    paused?: boolean;
}
export declare function useCountdown(target: Date | string | number, { precision, onComplete, paused }?: UseCountdownOptions): CountdownParts;
declare const tileVariants: (props?: ({
    size?: "sm" | "md" | "lg" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface CountdownProps extends Omit<React.ComponentProps<'span'>, 'children'>, VariantProps<typeof tileVariants>, UseCountdownOptions {
    to: Date | string | number;
    appearance?: 'inline' | 'blocks' | 'ring';
    from?: Date | string | number;
    format?: 'clock' | 'compact';
    trimLeading?: boolean;
    urgentBelow?: number;
    completed?: React.ReactNode;
    labels?: Partial<Record<CountdownUnit, [string, string]>>;
    srText?: (remaining: string) => string;
}
export declare function Countdown({ to, appearance, format, size, precision, trimLeading, urgentBelow, completed, labels: labelsProp, srText, onComplete, paused, from, className, ...props }: CountdownProps): import("react").JSX.Element;

// Defaults
// Countdown.appearance = inline
// Countdown.format = clock
// Countdown.precision = seconds
// Countdown.trimLeading = true
