// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/data-table-toolbar"

import type { ReactNode } from 'react';
import type { ColumnFiltersState, Table as TanstackTable } from '@tanstack/react-table';
import { type ButtonProps } from './button';
export interface DataTableBulkAction<TData> {
    label: string;
    icon?: ReactNode;
    appearance?: ButtonProps['appearance'];
    tone?: 'neutral' | 'danger';
    onSelect?: (rows: TData[]) => void;
    onSelectIds?: (ids: string[]) => void | Promise<void>;
    onSelectAllExcept?: (excludeIds: string[]) => void | Promise<void>;
    disabled?: (rows: TData[]) => boolean;
    disabledReason?: (rows: TData[]) => ReactNode;
    confirm?: {
        title: (count: number) => ReactNode;
        body?: (count: number) => ReactNode;
        description?: (count: number) => ReactNode;
        confirmLabel?: string;
        cancelLabel?: string;
        typeToConfirm?: string;
        confirmIcon?: ReactNode;
        onConfirm?: (rows: TData[]) => void;
        undo?: {
            title: (count: number) => string;
            description?: (count: number) => string;
            icon?: ReactNode;
            onUndo?: () => void;
        };
    };
}
export interface DataTableToolbarProps<TData> extends Omit<React.ComponentProps<'div'>, 'children'> {
    table: TanstackTable<TData>;
    actions?: DataTableBulkAction<TData>[];
    maxVisible?: number;
    selectAllLabel?: ReactNode;
    selectAllTooltip?: ReactNode;
    minTrailingWidth?: number;
    clearLabel?: string;
    idleLeft?: ReactNode;
    children?: ReactNode;
    embedded?: boolean;
    resolveAllRowIds?: (filters: ColumnFiltersState) => Promise<string[]>;
    allRowsCount?: number;
    selectAllScope?: {
        excludeIds: string[];
    } | null;
    onSelectAllScopeChange?: (scope: {
        excludeIds: string[];
    } | null) => void;
}
export declare const SELECT_COLUMN_ID = "select";
export declare function DataTableToolbar<TData>({ table, actions, maxVisible, selectAllLabel, selectAllTooltip, minTrailingWidth, clearLabel, idleLeft, children, embedded, resolveAllRowIds, allRowsCount, selectAllScope, onSelectAllScopeChange, className, ...props }: DataTableToolbarProps<TData>): import("react").JSX.Element | null;

// Defaults
// DataTableToolbar.actions = []
// DataTableToolbar.clearLabel = Clear selection (localized: dataTable.clearSelection)
// DataTableToolbar.embedded = false
// DataTableToolbar.minTrailingWidth = 160
// DataTableToolbar.selectAllLabel = Select all (localized: dataTable.selectAll)
// DataTableToolbar.selectAllTooltip = Select All (localized: dataTable.selectAllTooltip)
