// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/data-table"

import type { ReactNode, ElementType } from 'react';
import { type Column, type ColumnDef, type ColumnFiltersState, type OnChangeFn, type PaginationState, type RowData, type SortingState, type RowSelectionState, type Table as TanstackTable } from '@tanstack/react-table';
import { type DataTableCellKind } from './data-table-cell';
declare module '@tanstack/react-table' {
    interface ColumnMeta<TData extends RowData, TValue> {
        primary?: boolean;
        control?: boolean;
        align?: 'right';
        hideBelow?: 'sm' | 'md' | 'lg';
        label?: string;
        pin?: 'left' | 'right';
        kind?: DataTableCellKind;
        headClassName?: string;
        cellClassName?: string;
    }
}
declare function DataTableColumnHeader<TData, TValue>({ column, title, className }: {
    column: Column<TData, TValue>;
    title: string;
    className?: string;
}): import("react").JSX.Element;
export type DataTableRowMenuItem<TData> = {
    type: 'content';
    id: string;
    content: ReactNode;
} | {
    type?: 'item';
    id: string;
    label: ReactNode;
    icon?: ReactNode;
    trailing?: ReactNode;
    tone?: 'neutral' | 'danger';
    disabled?: boolean | ((row: TData) => boolean);
    onSelect: (row: TData) => void;
} | {
    type: 'submenu';
    id: string;
    label: ReactNode;
    disabled?: boolean | ((row: TData) => boolean);
    items: DataTableRowMenuItem<TData>[];
} | {
    type: 'group';
    id: string;
    label: ReactNode;
    items: DataTableRowMenuItem<TData>[];
} | {
    type: 'separator';
};
export interface DataTableRowMenu<TData> {
    contextual?: boolean;
    label?: string | ((row: TData) => string);
    items: DataTableRowMenuItem<TData>[] | ((row: TData) => DataTableRowMenuItem<TData>[]);
}
export interface DataTableProps<TData> {
    columns: ColumnDef<TData, unknown>[];
    data: TData[];
    rowMenu?: DataTableRowMenu<TData>;
    getRowId?: (row: TData) => string;
    loading?: boolean;
    skeletonRows?: number;
    enableSelection?: boolean;
    pinSelection?: boolean;
    selectAll?: 'header' | 'toolbar' | 'none';
    selectAllTooltip?: ReactNode;
    lines?: 1 | 2;
    hideHeader?: boolean;
    hideFooter?: boolean;
    pageSize?: number;
    stickyHeader?: boolean;
    maxHeight?: number | string;
    fillViewport?: boolean;
    getRowHref?: (row: TData) => string;
    onRowClick?: (row: TData) => void;
    linkComponent?: ElementType;
    getRowLabel?: (row: TData) => string;
    emptyMessage?: ReactNode;
    emptyState?: (table: TanstackTable<TData>) => ReactNode;
    ariaLabel?: string;
    toolbar?: (table: TanstackTable<TData>) => ReactNode;
    manualSorting?: boolean;
    manualFiltering?: boolean;
    manualPagination?: boolean;
    pageCount?: number;
    rowCount?: number;
    sorting?: SortingState;
    onSortingChange?: OnChangeFn<SortingState>;
    columnFilters?: ColumnFiltersState;
    onColumnFiltersChange?: OnChangeFn<ColumnFiltersState>;
    pagination?: PaginationState;
    onPaginationChange?: OnChangeFn<PaginationState>;
    rowSelection?: RowSelectionState;
    onRowSelectionChange?: OnChangeFn<RowSelectionState>;
    onLoadMore?: () => void;
    hasMore?: boolean;
    loadingMore?: boolean;
    virtualized?: boolean;
    estimateRowHeight?: number;
    overscan?: number;
    mobileLayout?: 'stack' | 'paged' | 'scroll';
    columnsPerPage?: number;
    embedded?: boolean;
    embeddedBottomRounded?: boolean;
    className?: string;
}
export declare function DataTable<TData>({ columns, data, rowMenu, loading, skeletonRows, enableSelection, pinSelection, selectAll, selectAllTooltip, lines, hideHeader, hideFooter, pageSize, stickyHeader, maxHeight, fillViewport, getRowId, getRowHref, onRowClick, linkComponent, getRowLabel, emptyMessage, emptyState, ariaLabel, toolbar, mobileLayout, columnsPerPage, manualSorting, manualFiltering, manualPagination, pageCount, rowCount, sorting: sortingProp, onSortingChange, columnFilters: columnFiltersProp, onColumnFiltersChange, pagination: paginationProp, onPaginationChange, rowSelection: rowSelectionProp, onRowSelectionChange, onLoadMore, hasMore, loadingMore, virtualized, estimateRowHeight, overscan, embedded, embeddedBottomRounded, className, }: DataTableProps<TData>): import("react").JSX.Element;
export { DataTableColumnHeader };

// Defaults
// DataTable.columnsPerPage = 2
// DataTable.embedded = false
// DataTable.embeddedBottomRounded = false
// DataTable.emptyMessage = No results. (localized: common.noResults)
// DataTable.enableSelection = false
// DataTable.estimateRowHeight = 48
// DataTable.fillViewport = false
// DataTable.hasMore = false
// DataTable.hideFooter = false
// DataTable.hideHeader = false
// DataTable.lines = 1
// DataTable.loading = false
// DataTable.loadingMore = false
// DataTable.manualFiltering = false
// DataTable.manualPagination = false
// DataTable.manualSorting = false
// DataTable.mobileLayout = stack
// DataTable.overscan = 8
// DataTable.pageSize = 10
// DataTable.pinSelection = false
// DataTable.selectAll = header
// DataTable.selectAllTooltip = Select All (localized: dataTable.selectAllTooltip)
// DataTable.stickyHeader = true
// DataTable.virtualized = false
