// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/data-table-cell"

import type { ReactNode } from 'react';
import { type AutocompleteOption } from './autocomplete';
import { type BadgeTone, type BadgeSize } from './badge';
import { type ButtonProps } from './button';
import { type ComboboxOption } from './combobox';
import { type DateRangePickerProps } from './date-range-picker';
import type { DateRange } from 'react-day-picker';
import { type SparklineTone } from './sparkline';
import { type StatusTone } from './status-dot';
export type DataTableCellKind = 'text' | 'mono' | 'primary' | 'status' | 'badge' | 'usage' | 'sparkline' | 'input' | 'textarea' | 'number' | 'select' | 'combobox' | 'autocomplete' | 'tags' | 'date-range' | 'switch' | 'slider' | 'selector' | 'menu' | 'custom';
export interface CellBoxProps {
    lines?: 1 | 2;
    grow?: boolean;
    loading?: boolean;
}
export interface SecondLineProps {
    secondary?: ReactNode;
    secondaryMono?: boolean;
}
export interface TextCellProps extends CellBoxProps, SecondLineProps {
    kind?: 'text';
    value: ReactNode;
    mono?: boolean;
    muted?: boolean;
}
export interface MonoCellProps extends CellBoxProps, SecondLineProps {
    kind: 'mono';
    value: ReactNode;
    muted?: boolean;
}
export interface PrimaryCellProps extends CellBoxProps, SecondLineProps {
    kind: 'primary';
    value: ReactNode;
    leading?: ReactNode;
    mono?: boolean;
    below?: ReactNode;
}
export interface StatusCellProps extends CellBoxProps {
    kind: 'status';
    tone?: StatusTone;
    label: ReactNode;
}
export interface BadgeCellBadge {
    label: ReactNode;
    tone?: BadgeTone;
}
export interface BadgeCellSingle extends CellBoxProps {
    kind: 'badge';
    tone?: BadgeTone;
    size?: BadgeSize;
    label: ReactNode;
    badges?: undefined;
    collapsedLabel?: undefined;
}
export interface BadgeCellMultiple extends CellBoxProps {
    kind: 'badge';
    badges: BadgeCellBadge[];
    size?: BadgeSize;
    collapsedLabel?: string;
    label?: undefined;
    tone?: undefined;
}
export type BadgeCellProps = BadgeCellSingle | BadgeCellMultiple;
export interface UsageCellProps extends CellBoxProps {
    kind: 'usage';
    value: number;
    total: number | null;
    label?: ReactNode;
    header?: string;
}
export interface SparklineCellProps extends CellBoxProps {
    kind: 'sparkline';
    data: number[];
    tone?: SparklineTone;
    area?: boolean;
    label?: ReactNode;
    ariaLabel: string;
    width?: number;
    height?: number;
}
export type EditableNameProps = {
    label: string;
    labelledBy?: undefined;
} | {
    label?: undefined;
    labelledBy: string;
};
export type EditableCellProps = EditableNameProps & {
    id?: string;
    describedBy?: string;
    disabled?: boolean;
    readOnly?: boolean;
    invalid?: boolean;
    errorMessage?: string;
};
export type InputCellProps = CellBoxProps & EditableCellProps & {
    kind: 'input';
    value: string;
    onValueChange?: (value: string) => void;
    onBlur?: React.FocusEventHandler<HTMLInputElement>;
    placeholder?: string;
    type?: 'text' | 'number' | 'email' | 'url' | 'tel';
    mono?: boolean;
};
export type TextareaCellProps = CellBoxProps & EditableCellProps & {
    kind: 'textarea';
    value: string;
    onValueChange?: (value: string) => void;
    onBlur?: React.FocusEventHandler<HTMLTextAreaElement>;
    placeholder?: string;
    rows?: number;
};
export type NumberCellProps = CellBoxProps & EditableCellProps & {
    kind: 'number';
    value: number | null;
    onValueChange?: (value: number | null) => void;
    min?: number;
    max?: number;
    step?: number;
    placeholder?: string;
};
export type SelectCellProps = CellBoxProps & EditableCellProps & {
    kind: 'select';
    value: string;
    onValueChange?: (value: string) => void;
    options: {
        value: string;
        label: ReactNode;
        disabled?: boolean;
    }[];
    placeholder?: string;
};
export type ComboboxCellProps = CellBoxProps & EditableCellProps & {
    kind: 'combobox';
    value: string;
    onValueChange?: (value: string) => void;
    options: ComboboxOption[];
    placeholder?: string;
    emptyMessage?: ReactNode;
};
export type AutocompleteCellProps = CellBoxProps & EditableCellProps & {
    kind: 'autocomplete';
    value: string;
    onValueChange?: (value: string) => void;
    options: AutocompleteOption[];
    placeholder?: string;
};
export type TagsCellProps = CellBoxProps & EditableCellProps & {
    kind: 'tags';
    value: string[];
    onValueChange?: (value: string[]) => void;
    options?: string[];
    placeholder?: string;
    max?: number;
};
export type DateRangeCellProps = CellBoxProps & EditableCellProps & {
    kind: 'date-range';
    value: DateRange | undefined;
    onValueChange?: (value: DateRange | undefined) => void;
    placeholder?: string;
    numberOfMonths?: number;
    calendarProps?: DateRangePickerProps['calendarProps'];
};
export type SwitchCellProps = CellBoxProps & EditableCellProps & {
    kind: 'switch';
    checked: boolean;
    onCheckedChange?: (checked: boolean) => void;
};
export type SliderCellProps = CellBoxProps & EditableCellProps & {
    kind: 'slider';
    value: number;
    onValueChange?: (value: number) => void;
    min?: number;
    max?: number;
    step?: number;
    formatValue?: (value: number) => string;
};
export interface SelectorCellProps extends CellBoxProps {
    kind: 'selector';
    checked: boolean | 'indeterminate';
    onCheckedChange?: (checked: boolean) => void;
    disabled?: boolean;
    label: string;
}
export interface MenuCellProps extends CellBoxProps {
    kind: 'menu';
    children: ReactNode;
    revealOnHover?: boolean;
}
export interface CustomCellProps extends CellBoxProps {
    kind: 'custom';
    children: ReactNode;
}
export type DataTableCellValueProps = TextCellProps | MonoCellProps | PrimaryCellProps | StatusCellProps | BadgeCellProps | UsageCellProps | SparklineCellProps | InputCellProps | TextareaCellProps | NumberCellProps | SelectCellProps | ComboboxCellProps | AutocompleteCellProps | TagsCellProps | DateRangeCellProps | SwitchCellProps | SliderCellProps | SelectorCellProps | MenuCellProps | CustomCellProps;
export interface LoadingCellProps extends CellBoxProps {
    kind?: DataTableCellKind;
    loading: true;
    leading?: ReactNode;
    secondary?: ReactNode;
}
export type DataTableCellProps = DataTableCellValueProps | LoadingCellProps;
export declare const DataTableCellMenuTrigger: import("react").ForwardRefExoticComponent<ButtonProps & {
    label: string;
} & import("react").RefAttributes<HTMLButtonElement>>;
export declare function DataTableCell(props: DataTableCellProps): import("react").JSX.Element;
