// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/date-time-picker"

import { DatePicker } from './date-picker';
export interface DateTimePickerProps {
    value?: Date;
    defaultValue?: Date;
    onChange?: (value: Date | undefined, meta: {
        timeSet: boolean;
    }) => void;
    step?: number;
    hourCycle?: 12 | 24;
    datePlaceholder?: string;
    timePlaceholder?: string;
    showClear?: boolean;
    disabled?: boolean;
    id?: string;
    className?: string;
    dateClassName?: string;
    timeClassName?: string;
    calendarProps?: React.ComponentProps<typeof DatePicker>['calendarProps'];
    'aria-label'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
}
export declare function DateTimePicker({ value, defaultValue, onChange, step, hourCycle, datePlaceholder, timePlaceholder, showClear, disabled, id, className, dateClassName, timeClassName, calendarProps, 'aria-label': ariaLabel, 'aria-invalid': ariaInvalid, 'aria-describedby': ariaDescribedby, }: DateTimePickerProps): import("react").JSX.Element;

// Defaults
// DateTimePicker.datePlaceholder = Pick a date (localized: datePicker.placeholder)
// DateTimePicker.hourCycle = 12
// DateTimePicker.showClear = false
// DateTimePicker.step = 30
// DateTimePicker.timePlaceholder = Select time (localized: timeField.placeholder)
