// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/date-picker"

import { Calendar } from './calendar';
export declare const dateFieldTriggerClassName: string;
export interface DatePickerProps {
    value?: Date;
    defaultValue?: Date;
    onChange?: (date: Date | undefined) => void;
    placeholder?: string;
    showClear?: boolean;
    disabled?: boolean;
    id?: string;
    className?: string;
    'aria-label'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
    calendarProps?: Omit<React.ComponentProps<typeof Calendar>, 'mode' | 'selected' | 'onSelect'>;
}
export declare function DatePicker({ value, defaultValue, onChange, placeholder, showClear, disabled, id, className, 'aria-label': ariaLabel, 'aria-invalid': ariaInvalid, 'aria-describedby': ariaDescribedby, calendarProps, }: DatePickerProps): import("react").JSX.Element;

// Defaults
// DatePicker.placeholder = Pick a date (localized: datePicker.placeholder)
// DatePicker.showClear = false
