// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/date-range-picker"

import type { DateRange } from 'react-day-picker';
import { Calendar } from './calendar';
export interface DateRangePickerProps {
    value?: DateRange;
    defaultValue?: DateRange;
    onChange?: (range: DateRange | undefined) => void;
    placeholder?: string;
    showClear?: boolean;
    numberOfMonths?: number;
    disabled?: boolean;
    id?: string;
    className?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
    calendarProps?: Omit<React.ComponentProps<typeof Calendar>, 'mode' | 'selected' | 'onSelect' | 'numberOfMonths'>;
}
export declare function DateRangePicker({ value, defaultValue, onChange, placeholder, showClear, numberOfMonths, disabled, id, className, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, 'aria-invalid': ariaInvalid, 'aria-describedby': ariaDescribedby, calendarProps, }: DateRangePickerProps): import("react").JSX.Element;

// Defaults
// DateRangePicker.numberOfMonths = 2
// DateRangePicker.placeholder = Pick a date range (localized: dateRangePicker.placeholder)
// DateRangePicker.showClear = false
