// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/density-toggle"

import { type Density } from './use-density';
export interface DensityToggleProps extends Omit<React.ComponentPropsWithoutRef<'div'>, 'defaultValue' | 'dir'> {
    value?: Density;
    onValueChange?: (density: Density) => void;
    size?: 'sm' | 'md';
}
export declare function DensityToggle({ value, onValueChange, size, className, ...props }: DensityToggleProps): import("react").JSX.Element;

// Defaults
// DensityToggle.size = sm
