// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/description-list"

export declare function DescriptionList({ className, ...props }: React.ComponentProps<'dl'>): import("react").JSX.Element;
export declare function DescriptionItem({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function DescriptionTerm({ className, ...props }: React.ComponentProps<'dt'>): import("react").JSX.Element;
export declare function DescriptionDetails({ className, ...props }: React.ComponentProps<'dd'>): import("react").JSX.Element;
