// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/dialog"

import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { type VariantProps } from 'class-variance-authority';
export declare const Dialog: React.FC<DialogPrimitive.DialogProps>;
export declare const DialogTrigger: React.ForwardRefExoticComponent<DialogPrimitive.DialogTriggerProps & React.RefAttributes<HTMLButtonElement>>;
export declare const DialogClose: React.ForwardRefExoticComponent<DialogPrimitive.DialogCloseProps & React.RefAttributes<HTMLButtonElement>>;
export declare const DialogPortal: React.FC<DialogPrimitive.DialogPortalProps>;
export declare const DialogOverlay: React.ForwardRefExoticComponent<Omit<DialogPrimitive.DialogOverlayProps & React.RefAttributes<HTMLDivElement>, "ref"> & React.RefAttributes<HTMLDivElement>>;
declare const dialogContentVariants: (props?: ({
    size?: "md" | "full" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface DialogContentProps extends React.ComponentProps<typeof DialogPrimitive.Content>, VariantProps<typeof dialogContentVariants> {
    showCloseButton?: boolean;
    gap?: 'md' | 'sm' | 'none';
}
export declare function DialogContent({ className, children, showCloseButton, size, gap, ...props }: DialogContentProps): React.JSX.Element;
export interface DialogHeaderProps extends React.ComponentProps<'div'> {
    showDivider?: boolean;
}
export declare function DialogHeader({ className, showDivider, ...props }: DialogHeaderProps): React.JSX.Element;
export declare function DialogBody({ className, showDivider, ...props }: React.ComponentProps<'div'> & {
    showDivider?: boolean;
}): React.JSX.Element;
export interface DialogFooterProps extends React.ComponentProps<'div'> {
    showDivider?: boolean;
}
export declare function DialogFooter({ className, showDivider, ...props }: DialogFooterProps): React.JSX.Element;
export declare function DialogTitle({ className, size, ...props }: React.ComponentProps<typeof DialogPrimitive.Title> & {
    size?: 'md' | 'lg';
}): React.JSX.Element;
export declare function DialogDescription({ className, ...props }: React.ComponentProps<typeof DialogPrimitive.Description>): React.JSX.Element;

// Defaults
// DialogContent.gap = md
// DialogContent.showCloseButton = true
// DialogFooter.showDivider = true
// DialogHeader.showDivider = true
// DialogTitle.size = md
