// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/diff-viewer"

export type DiffView = 'unified' | 'split';
export interface DiffViewerProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    oldValue: string;
    newValue: string;
    view?: DiffView;
    defaultView?: DiffView;
    onViewChange?: (view: DiffView) => void;
    viewToggle?: boolean;
    filename?: string;
    oldFilename?: string;
    language?: string;
    context?: number;
    wordDiff?: boolean;
    lineNumbers?: boolean;
    stats?: boolean;
    wrap?: boolean;
    actions?: React.ReactNode;
    label?: string;
    expandLabel?: (hiddenCount: number) => string;
    emptyMessage?: React.ReactNode;
}
export declare function DiffViewer({ oldValue, newValue, view: viewProp, defaultView, onViewChange, viewToggle, filename, oldFilename, language, context, wordDiff, lineNumbers, stats, wrap: wrapProp, actions, label, expandLabel, emptyMessage, className, ...props }: DiffViewerProps): import("react").JSX.Element;

// Defaults
// DiffViewer.context = 3
// DiffViewer.defaultView = unified
// DiffViewer.emptyMessage = No changes (localized: diffViewer.empty)
// DiffViewer.expandLabel = localized: diffViewer.expand
// DiffViewer.lineNumbers = true
// DiffViewer.stats = true
// DiffViewer.viewToggle = false
// DiffViewer.wordDiff = true
