// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/donut-chart"

export interface DonutChartSlice {
    label: string;
    value: number;
}
export interface DonutChartProps {
    data: DonutChartSlice[];
    height?: number;
    unit?: string;
    format?: (v: number) => string;
    centerLabel?: string;
    centerValue?: string;
    showCenter?: boolean;
    legend?: boolean;
    thickness?: 'default' | 'thin';
    layout?: 'vertical' | 'horizontal';
    loading?: boolean;
    ariaLabel?: string;
    className?: string;
}
export declare function DonutChart({ data, height, unit, format, centerLabel, centerValue, showCenter, legend, thickness, layout, loading, ariaLabel, className, }: DonutChartProps): import("react").JSX.Element;

// Defaults
// DonutChart.centerLabel = Total (localized: chart.total)
// DonutChart.height = 200
// DonutChart.layout = vertical
// DonutChart.legend = true
// DonutChart.loading = false
// DonutChart.showCenter = true
// DonutChart.thickness = default
// DonutChart.unit = 
