// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/dot-separator"

export declare function DotSeparator({ className, ...props }: React.ComponentProps<'span'>): import("react").JSX.Element;
