// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/drawer"

import { Drawer as DrawerPrimitive } from 'vaul';
export type DrawerDirection = 'top' | 'bottom' | 'left' | 'right' | 'start' | 'end';
export declare function Drawer({ direction, autoFocus, onOpenChange, ...props }: Omit<React.ComponentProps<typeof DrawerPrimitive.Root>, 'direction'> & {
    direction?: DrawerDirection;
}): import("react").JSX.Element;
export declare const DrawerTrigger: import("react").ForwardRefExoticComponent<import("@radix-ui/react-dialog").DialogTriggerProps & import("react").RefAttributes<HTMLButtonElement>>;
export declare const DrawerPortal: typeof import("vaul").Portal;
export declare const DrawerClose: import("react").ForwardRefExoticComponent<import("@radix-ui/react-dialog").DialogCloseProps & import("react").RefAttributes<HTMLButtonElement>>;
export declare const DrawerOverlay: import("react").ForwardRefExoticComponent<Omit<Omit<import("@radix-ui/react-dialog").DialogOverlayProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("react").RefAttributes<HTMLDivElement>>;
export interface DrawerContentProps extends React.ComponentProps<typeof DrawerPrimitive.Content> {
    width?: 'full' | 'fixed';
}
export declare function DrawerContent({ className, children, width, ...props }: DrawerContentProps): import("react").JSX.Element;
export declare function DrawerHeader({ className, onPointerDown, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function DrawerBody({ className, onPointerDown, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function DrawerFooter({ className, onPointerDown, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function DrawerTitle({ className, ...props }: React.ComponentProps<typeof DrawerPrimitive.Title>): import("react").JSX.Element;
export declare function DrawerDescription({ className, ...props }: React.ComponentProps<typeof DrawerPrimitive.Description>): import("react").JSX.Element;

// Defaults
// Drawer.direction = bottom
// DrawerContent.width = full
