// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/dropzone"

export interface StagedFile {
    name: string;
    size: number;
    error?: string;
}
export interface DropzoneProps {
    onFiles: (files: File[]) => void;
    accept?: string;
    onReject?: (files: File[]) => void;
    multiple?: boolean;
    disabled?: boolean;
    hint?: string;
    error?: string;
    successFile?: {
        name: string;
        uploadedAt: string;
    };
    loading?: boolean;
    files?: StagedFile[];
    onRemove?: (index: number) => void;
    'aria-label'?: string;
    className?: string;
}
declare function humanSize(bytes: number): string;
declare function Dropzone({ onFiles, accept, onReject, multiple, disabled, hint, error, successFile, loading, files, onRemove, className, 'aria-label': ariaLabel, }: DropzoneProps): import("react").JSX.Element;
export { Dropzone, humanSize };

// Defaults
// Dropzone.disabled = false
// Dropzone.loading = false
// Dropzone.multiple = true
