// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/empty-state"

import type { ElementType, ReactNode, CSSProperties } from 'react';
export interface EmptyStateProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    icon?: ReactNode;
    title: ReactNode;
    description?: ReactNode;
    action?: ReactNode;
    titleAs?: ElementType;
    filtered?: boolean;
    filteredIcon?: ReactNode;
    filteredTitle?: ReactNode;
    filteredDescription?: ReactNode;
    filteredAction?: ReactNode;
    height?: 'container' | CSSProperties['height'];
}
export declare function EmptyState({ className, icon, title, description, action, titleAs, filtered, filteredIcon, filteredTitle, filteredDescription, filteredAction, height, style, children, ...props }: EmptyStateProps): import("react").JSX.Element;
export declare function EmptyStateIcon({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export interface EmptyStateTitleProps extends React.ComponentProps<'p'> {
    as?: ElementType;
    asChild?: boolean;
}
export declare function EmptyStateTitle({ className, as, asChild, ...props }: EmptyStateTitleProps): import("react").JSX.Element;
export declare function EmptyStateDescription({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
export declare function EmptyStateActions({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;

// Defaults
// EmptyState.filtered = false
// EmptyStateTitle.asChild = false
