// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/fab"

import { type ReactNode, type RefObject } from 'react';
export type FabSize = 'sm' | 'md' | 'lg';
export type FabTone = 'primary' | 'secondary' | 'neutral';
export type FabAppearance = 'filled' | 'tonal';
export type FabPosition = 'bottom-end' | 'bottom-start' | 'bottom-center' | 'none';
export interface FabProps extends Omit<React.ComponentProps<'button'>, 'children'> {
    icon: ReactNode;
    label?: ReactNode;
    size?: FabSize;
    tone?: FabTone;
    appearance?: FabAppearance;
    position?: FabPosition;
    collapseOnScroll?: boolean;
    scrollContainer?: RefObject<HTMLElement | null>;
    collapsed?: boolean;
}
export declare const Fab: import("react").ForwardRefExoticComponent<Omit<FabProps, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;
export interface FabSpeedDialAction {
    label: string;
    icon: ReactNode;
    onSelect?: () => void;
    disabled?: boolean;
}
export interface FabSpeedDialProps {
    actions: FabSpeedDialAction[];
    icon?: ReactNode;
    openLabel?: string;
    closeLabel?: string;
    size?: FabSize;
    tone?: FabTone;
    position?: FabPosition;
    className?: string;
}
export declare function FabSpeedDial({ actions, icon, openLabel, closeLabel, size, tone, position, className }: FabSpeedDialProps): import("react").JSX.Element;

// Defaults
// Fab.appearance = filled
// Fab.collapseOnScroll = false
// Fab.position = bottom-end
// Fab.size = md
// Fab.tone = primary
// FabSpeedDial.position = bottom-end
// FabSpeedDial.size = md
// FabSpeedDial.tone = primary
