// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/feedback-widget"

export type FeedbackVote = 'yes' | 'no';
export interface FeedbackDetails {
    vote: FeedbackVote;
    reasons: string[];
    comment: string;
}
export interface FeedbackWidgetProps {
    question?: string;
    yesLabel?: string;
    noLabel?: string;
    reasons?: string[];
    positiveReasons?: string[];
    askOnPositive?: boolean;
    onVote?: (vote: FeedbackVote) => void;
    onSubmit?: (details: FeedbackDetails) => void;
    thankYou?: string;
    size?: 'sm' | 'md';
    className?: string;
}
export declare function FeedbackWidget({ question, yesLabel, noLabel, reasons, positiveReasons, askOnPositive, onVote, onSubmit, thankYou, size, className, }: FeedbackWidgetProps): import("react").JSX.Element;

// Defaults
// FeedbackWidget.askOnPositive = false
// FeedbackWidget.noLabel = No (localized: feedbackWidget.no)
// FeedbackWidget.positiveReasons = ['Accurate', 'Easy to follow', 'Solved my problem']
// FeedbackWidget.question = Was this page helpful? (localized: feedbackWidget.question)
// FeedbackWidget.reasons = ['Inaccurate', 'Hard to understand', 'Missing information', 'Didn’t solve my problem']
// FeedbackWidget.size = md
// FeedbackWidget.thankYou = Thanks for your feedback. (localized: feedbackWidget.thanks)
// FeedbackWidget.yesLabel = Yes (localized: feedbackWidget.yes)
