// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/field"

export declare function Field({ className, invalid, required, disabled, ...props }: React.ComponentProps<'div'> & {
    invalid?: boolean;
    required?: boolean;
    disabled?: boolean;
}): import("react").JSX.Element;
export declare function FieldDescription({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
export declare function FieldError({ className, children, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element | null;
