// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/fieldset"

import type { ReactNode } from 'react';
export interface FieldsetProps extends React.ComponentProps<'fieldset'> {
    legend?: ReactNode;
    description?: ReactNode;
}
declare function Fieldset({ legend, description, className, children, ...props }: FieldsetProps): import("react").JSX.Element;
export { Fieldset };
