// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/file"

import type { ReactNode } from 'react';
import { type AttachmentProps } from './attachment';
export interface FileProps extends Pick<AttachmentProps, 'variant' | 'type' | 'error' | 'showKind' | 'showMeta' | 'selected' | 'previewUrl' | 'href' | 'mimeLabels' | 'actions'> {
    name?: string;
    size?: number;
    meta?: ReactNode;
    empty?: boolean;
    pickLabel?: string;
    pickHint?: ReactNode;
    replaceLabel?: string;
    readOnly?: boolean;
    disabled?: boolean;
    accept?: string;
    onFileChange?: (file: File | null) => void;
    inputProps?: React.InputHTMLAttributes<HTMLInputElement>;
    className?: string;
}
export declare function File({ name: initialName, size: initialSize, meta: initialMeta, empty, pickLabel, pickHint, replaceLabel, readOnly, disabled, accept, onFileChange, inputProps, variant, type: initialType, error, showKind, showMeta, selected, previewUrl: initialPreviewUrl, href, mimeLabels, actions, className, }: FileProps): import("react").JSX.Element | null;

// Defaults
// File.disabled = false
// File.empty = false
// File.pickLabel = Add file (localized: file.pick)
// File.readOnly = false
// File.replaceLabel = Replace file (localized: file.replace)
// File.variant = card
