// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/filter"

export interface FilterOption {
    value: string;
    label: string;
    count?: number;
}
export interface FilterProps extends Omit<React.ComponentProps<'button'>, 'value' | 'defaultValue' | 'children'> {
    label: string;
    options: FilterOption[];
    value?: string[];
    defaultValue?: string[];
    onValueChange?: (value: string[]) => void;
    searchable?: boolean;
    align?: 'start' | 'center' | 'end';
    heightSize?: 'sm' | 'md' | 'lg';
}
export declare function Filter({ label, options, value, defaultValue, onValueChange, searchable, align, heightSize, className, disabled, ...props }: FilterProps): import("react").JSX.Element;

// Defaults
// Filter.align = start
// Filter.heightSize = md
// Filter.searchable = false
