// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/filter-field"

import type { ReactNode } from 'react';
import { type StatusTone } from './status-dot';
export interface FilterFieldOption {
    value: string;
    label: string;
    tone?: StatusTone;
}
export type FilterAttribute = {
    key: string;
    label: string;
    type: 'text';
    placeholder?: string;
    operators?: boolean;
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'select';
    options: FilterFieldOption[];
    multiple?: boolean;
    searchable?: boolean;
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'date';
    range?: boolean;
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'number';
    icon?: ReactNode;
};
export interface AppliedFilter {
    key: string;
    value: string;
    operator?: TextFilterOperator;
}
export type TextFilterOperator = 'contains' | 'equals' | 'is-present' | 'is-missing';
export declare const FILTER_FIELD_SEARCH_KEY = "__search__";
export declare function parseFilterDate(value: string): {
    from: Date;
    to: Date;
} | undefined;
export declare function parseFilterNumber(value: string): {
    min: number | undefined;
    max: number | undefined;
};
export interface FilterFieldProps {
    attributes: FilterAttribute[];
    value?: AppliedFilter[];
    defaultValue?: AppliedFilter[];
    onValueChange?: (value: AppliedFilter[]) => void;
    query?: string;
    defaultQuery?: string;
    onQueryChange?: (query: string) => void;
    placeholder?: string;
    addLabel?: string;
    attributeLabel?: string;
    emptyMessage?: string;
    searchLabel?: string;
    applyLabel?: string;
    disabled?: boolean;
    align?: 'start' | 'center' | 'end';
    id?: string;
    className?: string;
    inputClassName?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
}
export declare function FilterField({ attributes, value, defaultValue, onValueChange, query, defaultQuery, onQueryChange, placeholder, addLabel, attributeLabel, emptyMessage, searchLabel, applyLabel, disabled, align, id, className, inputClassName, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, 'aria-describedby': ariaDescribedby, }: FilterFieldProps): import("react").JSX.Element;

// Defaults
// FilterField.addLabel = Add filter (localized: filterField.add)
// FilterField.align = start
// FilterField.applyLabel = Apply (localized: filterField.apply)
// FilterField.attributeLabel = Filter by… (localized: filterField.attribute)
// FilterField.emptyMessage = No attributes. (localized: filterField.noAttributes)
// FilterField.placeholder = Filter or search… (localized: filterField.placeholder)
// FilterField.searchLabel = Search for (localized: filterField.searchFor)
