// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/form"

import { Slot } from '@radix-ui/react-slot';
import { type ControllerProps, type FieldPath, type FieldValues } from 'react-hook-form';
import { Label } from './label';
declare const Form: <TFieldValues extends FieldValues, TContext = any, TTransformedValues = TFieldValues>({ children, watch, getValues, getFieldState, setError, clearErrors, setValue, setValues, trigger, formState, resetField, reset, resetDefaultValues, handleSubmit, unregister, control, register, setFocus, subscribe, }: import("react-hook-form").FormProviderProps<TFieldValues, TContext, TTransformedValues>) => React.JSX.Element;
declare function FormField<TFieldValues extends FieldValues = FieldValues, TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>>(props: ControllerProps<TFieldValues, TName>): import("react").JSX.Element;
declare function useFormField(): {
    invalid: boolean;
    isDirty: boolean;
    isTouched: boolean;
    isValidating: boolean;
    error?: import("react-hook-form").FieldError | undefined;
    id: string;
    name: string;
    formItemId: string;
    formDescriptionId: string;
    formMessageId: string;
};
declare function FormItem({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
declare function FormLabel({ className, ...props }: React.ComponentProps<typeof Label>): import("react").JSX.Element;
declare function FormControl(props: React.ComponentProps<typeof Slot>): import("react").JSX.Element;
declare function FormDescription({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
declare function FormMessage({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element | null;
export { useFormField, Form, FormItem, FormLabel, FormControl, FormDescription, FormMessage, FormField };
