// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/help-icon"

import type { ReactNode } from 'react';
import { type VariantProps } from 'class-variance-authority';
import { TooltipContent } from './tooltip';
declare const helpIconVariants: (props?: ({
    size?: "sm" | "md" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface HelpIconProps extends React.ComponentProps<'button'>, VariantProps<typeof helpIconVariants> {
    children?: ReactNode;
    label?: string;
    icon?: ReactNode;
    contentClassName?: string;
    side?: React.ComponentProps<typeof TooltipContent>['side'];
    align?: React.ComponentProps<typeof TooltipContent>['align'];
    sideOffset?: React.ComponentProps<typeof TooltipContent>['sideOffset'];
}
export declare function HelpIcon({ children, className, contentClassName, label, icon, size, side, align, sideOffset, ...props }: HelpIconProps): import("react").JSX.Element;
export { helpIconVariants };

// Defaults
// HelpIcon.icon = <HelpCircle />
// HelpIcon.side = top
