// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/hold-to-talk"

export interface HoldToTalkProps extends Omit<React.ComponentProps<'button'>, 'onClick' | 'children'> {
    onHoldStart?: () => void;
    onHoldEnd?: () => void;
    onCancel?: () => void;
    label?: string;
}
export declare function HoldToTalk({ onHoldStart, onHoldEnd, onCancel, label, disabled, className, ...props }: HoldToTalkProps): import("react").JSX.Element;
