// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/hover-card"

import * as HoverCardPrimitive from '@radix-ui/react-hover-card';
export declare const HoverCard: import("react").FC<HoverCardPrimitive.HoverCardProps>;
export declare const HoverCardTrigger: import("react").ForwardRefExoticComponent<HoverCardPrimitive.HoverCardTriggerProps & import("react").RefAttributes<HTMLAnchorElement>>;
export declare function HoverCardContent({ className, align, sideOffset, ...props }: React.ComponentProps<typeof HoverCardPrimitive.Content>): import("react").JSX.Element;
