// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/image-cropper"

export interface CropArea {
    x: number;
    y: number;
    width: number;
    height: number;
}
export interface CropState {
    area: CropArea;
    zoom: number;
    rotation: number;
}
export interface ImageCropperProps extends Omit<React.ComponentProps<'div'>, 'onChange'> {
    src: string;
    aspect?: number;
    shape?: 'rect' | 'circle';
    minZoom?: number;
    maxZoom?: number;
    defaultZoom?: number;
    controls?: boolean;
    rotatable?: boolean;
    grid?: 'always' | 'interaction' | 'never';
    onCropChange?: (crop: CropState) => void;
    label?: string;
}
export declare function ImageCropper({ src, aspect, shape, minZoom, maxZoom, defaultZoom, controls, rotatable, grid, onCropChange, label, className, ...props }: ImageCropperProps): import("react").JSX.Element;
export interface GetCroppedImageOptions {
    width?: number;
    type?: 'image/png' | 'image/jpeg' | 'image/webp';
    quality?: number;
}
export declare function getCroppedImage(src: string, { area, rotation }: Pick<CropState, 'area' | 'rotation'>, options?: GetCroppedImageOptions): Promise<Blob>;

// Defaults
// ImageCropper.aspect = 1
// ImageCropper.controls = true
// ImageCropper.defaultZoom = 1
// ImageCropper.grid = interaction
// ImageCropper.label = Crop area (localized: imageCropper.label)
// ImageCropper.maxZoom = 4
// ImageCropper.minZoom = 1
// ImageCropper.rotatable = true
// ImageCropper.shape = rect
