// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/inline-edit"

export type InlineEditSize = 'sm' | 'md';
export interface InlineEditProps {
    label: string;
    value?: string;
    defaultValue?: string;
    onSave?: (value: string) => void | Promise<void>;
    validate?: (value: string) => string | undefined;
    placeholder?: string;
    saveOnBlur?: boolean;
    size?: InlineEditSize;
    multiline?: boolean;
    inheritFont?: boolean;
    readOnly?: boolean;
    disabled?: boolean;
    autoComplete?: string;
    className?: string;
}
export declare function InlineEdit({ label, value: valueProp, defaultValue, onSave, validate, placeholder, saveOnBlur, size, multiline, inheritFont, readOnly, disabled, autoComplete, className, }: InlineEditProps): import("react").JSX.Element;

// Defaults
// InlineEdit.defaultValue = 
// InlineEdit.disabled = false
// InlineEdit.inheritFont = false
// InlineEdit.multiline = false
// InlineEdit.placeholder = Add a value (localized: inlineEdit.placeholder)
// InlineEdit.readOnly = false
// InlineEdit.saveOnBlur = true
// InlineEdit.size = md
