// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/input-group"

declare function InputGroup({ className, onMouseDown, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export interface InputGroupAddonProps extends React.ComponentProps<'div'> {
    position?: 'start' | 'end';
    divider?: boolean;
}
declare function InputGroupAddon({ className, position, divider, ...props }: InputGroupAddonProps): import("react").JSX.Element;
declare const InputGroupInput: import("react").ForwardRefExoticComponent<Omit<import("react").DetailedHTMLProps<import("react").InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, "ref"> & import("react").RefAttributes<HTMLInputElement>>;
export { InputGroup, InputGroupAddon, InputGroupInput };

// Defaults
// InputGroupAddon.divider = true
// InputGroupAddon.position = start
