// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/input-otp"

import { OTPInput } from 'input-otp';
declare function InputOTP({ className, containerClassName, ...props }: React.ComponentProps<typeof OTPInput> & {
    containerClassName?: string;
}): import("react").JSX.Element;
declare function InputOTPGroup({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
declare function InputOTPSlot({ index, className, ...props }: React.ComponentProps<'div'> & {
    index: number;
}): import("react").JSX.Element;
declare function InputOTPSeparator({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export { InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator };
