// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/kanban"

import { type StatusTone } from './status-dot';
export interface KanbanColumn {
    id: string;
    title: string;
    tone?: StatusTone;
    limit?: number;
}
export interface KanbanItem {
    id: string;
    columnId: string;
}
export interface KanbanMove {
    itemId: string;
    fromColumnId: string;
    toColumnId: string;
    index: number;
}
export interface KanbanProps<T extends KanbanItem> extends Omit<React.ComponentProps<'div'>, 'children'> {
    columns: KanbanColumn[];
    items: T[];
    onItemsChange?: (items: T[], move: KanbanMove) => void;
    renderItem: (item: T, state: {
        overlay: boolean;
    }) => React.ReactNode;
    getItemLabel?: (item: T) => string;
    renderColumnActions?: (column: KanbanColumn) => React.ReactNode;
    renderColumnFooter?: (column: KanbanColumn) => React.ReactNode;
    emptyMessage?: React.ReactNode;
    columnWidth?: number | string;
    label?: string;
}
export declare function Kanban<T extends KanbanItem>({ columns, items, onItemsChange, renderItem, getItemLabel, renderColumnActions, renderColumnFooter, emptyMessage, columnWidth, label, className, ...props }: KanbanProps<T>): import("react").JSX.Element;
export interface KanbanCardProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    title: React.ReactNode;
    description?: React.ReactNode;
    eyebrow?: React.ReactNode;
    footer?: React.ReactNode;
}
export declare function KanbanCard({ title, description, eyebrow, footer, className, ...props }: KanbanCardProps): import("react").JSX.Element;

// Defaults
// Kanban.columnWidth = 288
// Kanban.emptyMessage = No items (localized: kanban.empty)
// Kanban.getItemLabel = (item) => item.id
// Kanban.label = Board (localized: kanban.label)
