// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/kbd"

export declare function Kbd({ className, ...props }: React.ComponentProps<'kbd'>): import("react").JSX.Element;
