// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/kebab-icon"

export type KebabIconSize = 'sm' | 'md' | 'lg';
export interface KebabIconProps {
    className?: string;
    size?: KebabIconSize;
}
export declare function KebabIconVertical({ className, size }: KebabIconProps): import("react").JSX.Element;
export declare function KebabIconHorizontal({ className, size }: KebabIconProps): import("react").JSX.Element;

// Defaults
// KebabIconHorizontal.size = md
// KebabIconVertical.size = md
