// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/keyboard-shortcuts"

import type { ReactNode, ReactElement, RefObject } from 'react';
import { DialogContent } from './dialog';
export interface Shortcut {
    keys: string[];
    description: string;
}
export interface ShortcutGroup {
    heading?: string;
    shortcuts: Shortcut[];
}
export interface KeyboardShortcutsProps extends Omit<React.ComponentProps<typeof DialogContent>, 'children' | 'title'> {
    groups: ShortcutGroup[];
    title?: ReactNode;
    description?: ReactNode;
    trigger?: ReactElement;
    hotkey?: string;
    scopeRef?: RefObject<HTMLElement | null>;
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (open: boolean) => void;
}
export declare function KeyboardShortcuts({ groups, title, description, trigger, hotkey, scopeRef, open, defaultOpen, onOpenChange, className, ...props }: KeyboardShortcutsProps): import("react").JSX.Element;

// Defaults
// KeyboardShortcuts.title = Keyboard shortcuts (localized: keyboardShortcuts.title)
