// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/label"

import * as LabelPrimitive from '@radix-ui/react-label';
export declare function OptionalMark(): import("react").JSX.Element;
declare function Label({ className, required, optional, children, ...props }: React.ComponentProps<typeof LabelPrimitive.Root> & {
    'data-error'?: boolean;
    required?: boolean;
    optional?: boolean;
}): import("react").JSX.Element;
export { Label };
