// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/lightbox"

import { type ReactNode } from 'react';
export interface LightboxImage {
    src: string;
    alt: string;
    caption?: ReactNode;
}
export interface LightboxProps {
    images: LightboxImage[];
    open: boolean;
    onOpenChange: (open: boolean) => void;
    index?: number;
    onIndexChange?: (index: number) => void;
    defaultIndex?: number;
    thumbnails?: boolean;
    title?: string;
}
export declare function Lightbox({ images, open, onOpenChange, index: indexProp, onIndexChange, defaultIndex, thumbnails, title }: LightboxProps): import("react").JSX.Element | null;

// Defaults
// Lightbox.defaultIndex = 0
// Lightbox.title = Image viewer (localized: lightbox.title)
