// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/line-chart"

export interface LineChartSeries {
    key: string;
    name: string;
}
export type LineChartPoint = {
    label: string;
} & Record<string, string | number>;
export interface LineChartProps {
    data: LineChartPoint[];
    series: LineChartSeries[];
    height?: number;
    yStep?: number;
    unit?: string;
    labelPrefix?: string;
    format?: (v: number) => string;
    legend?: boolean;
    showXAxis?: boolean;
    showYAxis?: boolean;
    ariaLabel?: string;
    className?: string;
}
export declare function LineChart({ data, series, height, yStep, unit, labelPrefix, format, legend, showXAxis, showYAxis, ariaLabel, className }: LineChartProps): import("react").JSX.Element;

// Defaults
// LineChart.height = 260
// LineChart.labelPrefix = 
// LineChart.legend = true
// LineChart.showXAxis = true
// LineChart.showYAxis = true
// LineChart.unit = 
// LineChart.yStep = 1
