// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/link"

import * as React from 'react';
export type LinkSize = 'xs' | 'sm' | 'md' | 'lg';
export interface LinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
    size?: 'xs' | 'sm' | 'md' | 'lg';
    underline?: boolean;
    inverse?: boolean;
    asChild?: boolean;
}
export declare const Link: React.ForwardRefExoticComponent<LinkProps & React.RefAttributes<HTMLAnchorElement>>;

// Defaults
// Link.asChild = false
// Link.inverse = false
// Link.underline = false
