// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/list-item"

import type { ReactNode, MouseEventHandler, KeyboardEventHandler } from 'react';
export type ListItemSize = 'sm' | 'md' | 'lg';
export interface ListItemProps extends Omit<React.ComponentProps<'div'>, 'title' | 'onClick' | 'onKeyDown'> {
    size?: ListItemSize;
    onClick?: MouseEventHandler<HTMLElement>;
    onKeyDown?: KeyboardEventHandler<HTMLElement>;
    leading?: ReactNode;
    title?: ReactNode;
    description?: ReactNode;
    trailing?: ReactNode;
    href?: string;
    interactive?: boolean;
    selected?: boolean;
    disabled?: boolean;
}
export declare function ListItem({ className, size, leading, title, description, trailing, href, interactive, selected, disabled, onClick, onKeyDown, children, ...props }: ListItemProps): import("react").JSX.Element;

// Defaults
// ListItem.disabled = false
// ListItem.interactive = false
// ListItem.size = md
