// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/marquee-columns"

import type { ReactNode } from 'react';
export interface MarqueeColumnsProps extends React.HTMLAttributes<HTMLDivElement> {
    columns: ReactNode[][];
    duration?: number;
    gap?: string;
    pauseButton?: boolean;
}
export declare function MarqueeColumns({ columns, duration, gap, pauseButton, className, style, ...props }: MarqueeColumnsProps): import("react").JSX.Element;

// Defaults
// MarqueeColumns.duration = 40
// MarqueeColumns.gap = 1rem
// MarqueeColumns.pauseButton = true
