// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/marquee"

import { type ReactNode } from 'react';
export interface MarqueeProps extends React.HTMLAttributes<HTMLDivElement> {
    duration?: number;
    reverse?: boolean;
    gap?: string;
    pauseButton?: boolean;
    fade?: boolean;
    children: ReactNode;
}
export declare function Marquee({ duration, reverse, gap, pauseButton, fade, className, style, children, ...props }: MarqueeProps): import("react").JSX.Element;

// Defaults
// Marquee.duration = 30
// Marquee.fade = true
// Marquee.gap = 2.5rem
// Marquee.pauseButton = true
// Marquee.reverse = false
