// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/masked-input"

export interface MaskedInputModifyResult {
    mask?: string;
    replacement?: Record<string, RegExp>;
    showMask?: boolean;
}
export type MaskedInputTrack = (rawInput: string) => string;
export type MaskedInputModify = (rawInput: string) => MaskedInputModifyResult;
export interface MaskedInputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue' | 'onChange'> {
    mask: string;
    replacement?: Record<string, RegExp> | string;
    showMask?: boolean;
    track?: MaskedInputTrack;
    modify?: MaskedInputModify;
    value?: string;
    defaultValue?: string;
    onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onUnmaskedChange?: (raw: string) => void;
    error?: boolean | React.ReactNode;
}
export declare const MaskedInput: import("react").ForwardRefExoticComponent<MaskedInputProps & import("react").RefAttributes<HTMLInputElement>>;

// Defaults
// MaskedInput.showMask = false
