// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/menubar"

import * as MenubarPrimitive from '@radix-ui/react-menubar';
export interface MenubarProps extends React.ComponentProps<typeof MenubarPrimitive.Root> {
    bordered?: boolean;
}
export declare const Menubar: ({ className, bordered, ...props }: MenubarProps) => import("react").JSX.Element;
export declare const MenubarMenu: typeof MenubarPrimitive.Menu;
export declare const MenubarGroup: import("react").ForwardRefExoticComponent<MenubarPrimitive.MenubarGroupProps & import("react").RefAttributes<HTMLDivElement>>;
export declare const MenubarRadioGroup: import("react").ForwardRefExoticComponent<MenubarPrimitive.MenubarRadioGroupProps & import("react").RefAttributes<HTMLDivElement>>;
export declare const MenubarPortal: import("react").FC<MenubarPrimitive.MenubarPortalProps>;
export declare const MenubarSub: import("react").FC<MenubarPrimitive.MenubarSubProps>;
export declare function MenubarTrigger({ className, ...props }: React.ComponentProps<typeof MenubarPrimitive.Trigger>): import("react").JSX.Element;
export declare function MenubarContent({ className, align, alignOffset, sideOffset, ...props }: React.ComponentProps<typeof MenubarPrimitive.Content>): import("react").JSX.Element;
export interface MenubarItemProps extends React.ComponentProps<typeof MenubarPrimitive.Item> {
    inset?: boolean;
    tone?: 'neutral' | 'danger';
}
export declare function MenubarItem({ className, inset, tone, ...props }: MenubarItemProps): import("react").JSX.Element;
export declare function MenubarCheckboxItem({ className, children, checked, ...props }: React.ComponentProps<typeof MenubarPrimitive.CheckboxItem>): import("react").JSX.Element;
export declare function MenubarRadioItem({ className, children, ...props }: React.ComponentProps<typeof MenubarPrimitive.RadioItem>): import("react").JSX.Element;
export declare function MenubarLabel({ className, inset, ...props }: React.ComponentProps<typeof MenubarPrimitive.Label> & {
    inset?: boolean;
}): import("react").JSX.Element;
export declare function MenubarSeparator({ className, ...props }: React.ComponentProps<typeof MenubarPrimitive.Separator>): import("react").JSX.Element;
export declare function MenubarShortcut({ className, ...props }: React.ComponentProps<'span'>): import("react").JSX.Element;
export declare function MenubarSubTrigger({ className, inset, children, ...props }: React.ComponentProps<typeof MenubarPrimitive.SubTrigger> & {
    inset?: boolean;
}): import("react").JSX.Element;
export declare function MenubarSubContent({ className, ...props }: React.ComponentProps<typeof MenubarPrimitive.SubContent>): import("react").JSX.Element;

// Defaults
// Menubar.bordered = true
// MenubarItem.tone = neutral
