// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/message-popup"

import type { ReactNode } from 'react';
import { PopoverContent, PopoverTrigger, type PopoverProps } from './popover';
export declare function MessagePopup(props: PopoverProps): import("react").JSX.Element;
export declare function MessagePopupTrigger({ asChild, ...props }: React.ComponentProps<typeof PopoverTrigger>): import("react").JSX.Element;
export interface MessagePopupContentProps extends Omit<React.ComponentProps<typeof PopoverContent>, 'title'> {
    title?: ReactNode;
    description?: ReactNode;
    showClose?: boolean;
}
export declare function MessagePopupContent({ className, title, description, showClose, side, align, sideOffset, children, ...props }: MessagePopupContentProps): import("react").JSX.Element;

// Defaults
// MessagePopupContent.showClose = true
