// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/message"

import type { ReactNode } from 'react';
export type MessageVariant = 'received' | 'sent';
export type MessageAppearance = 'filled' | 'tonal';
export interface MessageProps extends React.ComponentProps<'div'> {
    variant?: MessageVariant;
    appearance?: MessageAppearance;
    avatar?: ReactNode;
    author?: ReactNode;
    timestamp?: ReactNode;
}
export declare function Message({ className, variant, appearance, avatar, author, timestamp, children, ...props }: MessageProps): import("react").JSX.Element;

// Defaults
// Message.appearance = filled
// Message.variant = received
