// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/meter"

import type { ReactNode } from 'react';
export type MeterTone = 'primary' | 'success' | 'warning' | 'danger' | 'info';
export interface MeterProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    value: number;
    min?: number;
    max?: number;
    label?: ReactNode;
    format?: Intl.NumberFormatOptions;
    getValueLabel?: (formattedValue: string, value: number) => string;
    tone?: MeterTone;
    showValue?: boolean;
    segments?: number;
}
export declare function Meter({ value, min, max, label, format, getValueLabel, tone, showValue, segments, className, ...props }: MeterProps): import("react").JSX.Element;

// Defaults
// Meter.max = 100
// Meter.min = 0
// Meter.showValue = true
// Meter.tone = primary
