// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/metric"

import type { ReactNode } from 'react';
export interface MetricProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    icon?: ReactNode;
    value: ReactNode;
    label: string;
    description?: string;
    actions?: ReactNode;
}
export declare function Metric({ className, icon, value, label, description, actions, ...props }: MetricProps): import("react").JSX.Element;
