// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/navigation-menu"

import * as NavigationMenuPrimitive from '@radix-ui/react-navigation-menu';
export declare function NavigationMenu({ className, children, viewportClassName, ...props }: React.ComponentProps<typeof NavigationMenuPrimitive.Root> & {
    viewportClassName?: string;
}): import("react").JSX.Element;
export declare function NavigationMenuList({ className, ...props }: React.ComponentProps<typeof NavigationMenuPrimitive.List>): import("react").JSX.Element;
export declare const NavigationMenuItem: import("react").ForwardRefExoticComponent<NavigationMenuPrimitive.NavigationMenuItemProps & import("react").RefAttributes<HTMLLIElement>>;
export declare function NavigationMenuTrigger({ className, children, ...props }: React.ComponentProps<typeof NavigationMenuPrimitive.Trigger>): import("react").JSX.Element;
export declare function NavigationMenuContent({ className, ...props }: React.ComponentProps<typeof NavigationMenuPrimitive.Content>): import("react").JSX.Element;
export declare function NavigationMenuLink({ className, ...props }: React.ComponentProps<typeof NavigationMenuPrimitive.Link>): import("react").JSX.Element;
