// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/number-field"

declare const WIDTH_CLASSES: {
    readonly full: "w-full";
    readonly sm: "w-32";
    readonly md: "w-[var(--size-width-width-control-xl)] max-w-full";
    readonly lg: "w-[var(--size-width-width-control-2xl)] max-w-full";
    readonly xl: "w-[var(--size-width-width-control-3xl)] max-w-full";
};
export interface NumberFieldProps {
    value?: number;
    defaultValue?: number;
    onValueChange?: (value: number) => void;
    min?: number;
    max?: number;
    step?: number;
    disabled?: boolean;
    placeholder?: string;
    id?: string;
    className?: string;
    widthSize?: keyof typeof WIDTH_CLASSES;
    heightSize?: 'sm' | 'md';
    decrementLabel?: string;
    incrementLabel?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
}
export declare const NumberField: import("react").ForwardRefExoticComponent<NumberFieldProps & import("react").RefAttributes<HTMLInputElement>>;

// Defaults
// NumberField.decrementLabel = Decrease (localized: numberField.decrement)
// NumberField.heightSize = md
// NumberField.incrementLabel = Increase (localized: numberField.increment)
// NumberField.step = 1
// NumberField.widthSize = sm
