// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/option-card"

import type { ReactNode } from 'react';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
declare function OptionCardGroup({ className, ...props }: React.ComponentProps<typeof RadioGroupPrimitive.Root>): import("react").JSX.Element;
export interface OptionCardProps extends Omit<React.ComponentProps<typeof RadioGroupPrimitive.Item>, 'title' | 'children'> {
    title: string;
    description?: string;
    icon?: ReactNode;
    aside?: ReactNode;
}
declare function OptionCard({ className, value, title, description, icon, aside, ...props }: OptionCardProps): import("react").JSX.Element;
export { OptionCardGroup, OptionCard };
