// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/orbit-carousel"

export interface OrbitCarouselProps extends React.HTMLAttributes<HTMLDivElement> {
    shape?: 'drum' | 'wheel';
    itemWidth?: number;
    autoplay?: number;
    onIndexChange?: (index: number) => void;
}
export declare function OrbitCarousel({ shape, itemWidth, autoplay, onIndexChange, className, children, onKeyDown, ...props }: OrbitCarouselProps): import("react").JSX.Element | null;

// Defaults
// OrbitCarousel.itemWidth = 240
// OrbitCarousel.shape = drum
