// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/page-header"

import type { ReactNode } from 'react';
export interface PageHeaderProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    title: ReactNode;
    icon?: ReactNode;
    tags?: ReactNode;
    description?: ReactNode;
    breadcrumb?: ReactNode;
    actions?: ReactNode;
    contentActions?: ReactNode;
    as?: 'h1' | 'h2' | 'h3';
    children?: ReactNode;
}
export declare function PageHeader({ title, icon, tags, description, breadcrumb, actions, contentActions, as: Heading, className, children, ...props }: PageHeaderProps): import("react").JSX.Element;

// Defaults
// PageHeader.as = h1
