// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/pagination"

export declare function Pagination({ className, ...props }: React.ComponentProps<'nav'>): import("react").JSX.Element;
export declare function PaginationContent({ className, ...props }: React.ComponentProps<'ul'>): import("react").JSX.Element;
export declare function PaginationItem(props: React.ComponentProps<'li'>): import("react").JSX.Element;
export interface PaginationLinkProps extends React.ComponentProps<'a'> {
    isActive?: boolean;
    asChild?: boolean;
    disabled?: boolean;
}
export declare function PaginationLink({ className, isActive, wide, asChild, disabled, href, ...props }: PaginationLinkProps & {}): import("react").JSX.Element;
export declare function PaginationPrevious({ className, children, asChild, ...props }: PaginationLinkProps): import("react").JSX.Element;
export declare function PaginationNext({ className, children, asChild, ...props }: PaginationLinkProps): import("react").JSX.Element;
export declare function PaginationEllipsis({ className, ...props }: React.ComponentProps<'span'>): import("react").JSX.Element;

// Defaults
// PaginationLink.asChild = false
// PaginationLink.disabled = false
// PaginationLink.wide = false
