// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/password"

import { type TextFieldProps } from './text-field';
declare const WIDTH_SIZE_MAP: {
    readonly md: "md";
    readonly lg: "lg";
    readonly full: "full";
};
export interface PasswordProps extends Omit<TextFieldProps, 'type' | 'leftIcon' | 'rightIcon' | 'widthSize'> {
    widthSize?: keyof typeof WIDTH_SIZE_MAP;
}
export declare const Password: import("react").ForwardRefExoticComponent<PasswordProps & import("react").RefAttributes<HTMLInputElement>>;

// Defaults
// Password.widthSize = md
