// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/password-strength-meter"

import type { ReactNode } from 'react';
export interface PasswordStrengthRule {
    label: ReactNode;
    test: (value: string) => boolean;
}
export interface PasswordStrengthMeterProps {
    value: string;
    rules?: PasswordStrengthRule[];
    className?: string;
}
export declare function PasswordStrengthMeter({ value, rules: rulesProp, className }: PasswordStrengthMeterProps): import("react").JSX.Element;
