// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/phone-field"

import { type ReactNode } from 'react';
import { type CountryCode } from 'libphonenumber-js';
export type PhoneFieldSize = 'sm' | 'md';
export interface PhoneFieldChange {
    country: CountryCode;
    valid: boolean;
}
export interface PhoneFieldProps {
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string, details: PhoneFieldChange) => void;
    defaultCountry?: CountryCode;
    preferredCountries?: CountryCode[];
    label?: ReactNode;
    description?: ReactNode;
    error?: string;
    required?: boolean;
    optional?: boolean;
    heightSize?: PhoneFieldSize;
    disabled?: boolean;
    name?: string;
    id?: string;
    className?: string;
    locale?: string;
    'aria-label'?: string;
}
export declare function PhoneField({ value: valueProp, defaultValue, onValueChange, defaultCountry, preferredCountries, label, description, error: errorProp, required, optional, heightSize, disabled, name, id, className, locale: localeProp, 'aria-label': ariaLabel, }: PhoneFieldProps): import("react").JSX.Element;

// Defaults
// PhoneField.disabled = false
// PhoneField.heightSize = md
// PhoneField.preferredCountries = []
