// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/popover"

import * as PopoverPrimitive from '@radix-ui/react-popover';
declare const SheetContext: import("react").Context<boolean>;
export interface PopoverProps extends React.ComponentProps<typeof PopoverPrimitive.Root> {
    sheet?: boolean;
}
declare function Popover({ sheet, ...props }: PopoverProps): import("react").JSX.Element;
declare function PopoverTrigger({ id, ...props }: React.ComponentProps<typeof PopoverPrimitive.Trigger>): import("react").JSX.Element;
declare const PopoverAnchor: import("react").ForwardRefExoticComponent<Omit<PopoverPrimitive.PopoverAnchorProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("react").RefAttributes<HTMLDivElement>>;
declare const PopoverClose: import("react").ForwardRefExoticComponent<Omit<PopoverPrimitive.PopoverCloseProps & import("react").RefAttributes<HTMLButtonElement>, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;
export interface PopoverContentProps extends React.ComponentProps<typeof PopoverPrimitive.Content> {
    sheetTitle?: React.ReactNode;
    sheetClassName?: string;
}
declare function PopoverContent({ className, align, sideOffset, collisionPadding, sheetTitle, sheetClassName, ...props }: PopoverContentProps): import("react").JSX.Element;
export { Popover, PopoverTrigger, PopoverAnchor, PopoverClose, PopoverContent, SheetContext as PopoverSheetContext };

// Defaults
// Popover.sheet = false
