// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/price"

export type PriceSize = 'sm' | 'md' | 'lg' | 'xl';
export declare function formatPrice(amount: number, currency?: string, locale?: string): string;
export interface PriceProps extends Omit<React.ComponentProps<'span'>, 'children'> {
    amount: number;
    currency?: string;
    locale?: string;
    period?: string;
    compareAt?: number;
    showDiscount?: boolean;
    from?: boolean;
    superscript?: boolean;
    freeLabel?: string | null;
    size?: PriceSize;
}
export declare function Price({ amount, currency, locale: localeProp, period, compareAt, showDiscount, from, freeLabel, superscript, size, className, ...props }: PriceProps): import("react").JSX.Element;

// Defaults
// Price.currency = USD
// Price.freeLabel = Free (localized: price.free)
// Price.from = false
// Price.showDiscount = false
// Price.size = md
// Price.superscript = false
