// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/product-tour"

export type TourTarget = string | React.RefObject<HTMLElement | null> | (() => HTMLElement | null);
export interface TourStep {
    target?: TourTarget;
    title: React.ReactNode;
    content?: React.ReactNode;
    media?: React.ReactNode;
    side?: 'top' | 'right' | 'bottom' | 'left';
    align?: 'start' | 'center' | 'end';
    spotlightPadding?: number;
    interactive?: boolean;
}
export interface ProductTourLabels {
    next: string;
    back: string;
    done: string;
    skip: string;
    close: string;
    progress: (step: number, total: number) => string;
}
export interface ProductTourProps {
    steps: TourStep[];
    open: boolean;
    onOpenChange: (open: boolean) => void;
    step?: number;
    defaultStep?: number;
    onStepChange?: (step: number) => void;
    onComplete?: () => void;
    onSkip?: (step: number) => void;
    labels?: Partial<ProductTourLabels>;
    hideSkip?: boolean;
}
export declare function ProductTour({ steps, open, onOpenChange, step: stepProp, defaultStep, onStepChange, onComplete, onSkip, labels: labelsProp, hideSkip, }: ProductTourProps): import("react").JSX.Element | null;

// Defaults
// ProductTour.defaultStep = 0
// ProductTour.hideSkip = false
