// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/progress-ring"

import type { ReactNode } from 'react';
export type ProgressRingTone = 'primary' | 'success' | 'warning' | 'danger' | 'info';
export interface ProgressRingProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> {
    value: number;
    max?: number;
    label: string;
    size?: number;
    thickness?: number;
    tone?: ProgressRingTone;
    duration?: number;
    children?: ReactNode | ((shown: number) => ReactNode);
}
export declare function ProgressRing({ value, max, label, size, thickness, tone, duration, children, className, style, ...props }: ProgressRingProps): import("react").JSX.Element;

// Defaults
// ProgressRing.duration = 1200
// ProgressRing.max = 100
// ProgressRing.size = 120
// ProgressRing.thickness = 10
// ProgressRing.tone = primary
