// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/progress"

import * as ProgressPrimitive from '@radix-ui/react-progress';
export interface ProgressProps extends Omit<React.ComponentProps<typeof ProgressPrimitive.Root>, 'value'> {
    value?: number;
    indeterminate?: boolean;
    segments?: number;
}
export declare function Progress({ className, value, indeterminate, segments, ...props }: ProgressProps): import("react").JSX.Element;

// Defaults
// Progress.indeterminate = false
// Progress.value = 0
