// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/prompt-area"

import type { ReactNode } from 'react';
export interface PromptMenuItem {
    id: string;
    label: string;
    description?: string;
}
export interface PromptAreaProps extends Omit<React.ComponentProps<'div'>, 'onSubmit' | 'defaultValue' | 'value'> {
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    onSubmit?: (value: string) => void;
    onStop?: () => void;
    onEditLast?: () => void;
    placeholder?: string;
    disabled?: boolean;
    busy?: boolean;
    maxRows?: number;
    maxLength?: number;
    leading?: ReactNode;
    trailing?: ReactNode;
    attachments?: ReactNode;
    submitLabel?: string;
    stopLabel?: string;
    onFilesAdded?: (files: File[]) => void;
    accept?: string;
    maxFileSize?: number;
    onFileRejected?: (file: File, reason: 'type' | 'size') => void;
    mentions?: PromptMenuItem[];
    commands?: PromptMenuItem[];
    onMentionSelect?: (item: PromptMenuItem) => void;
    onCommandSelect?: (item: PromptMenuItem) => void;
}
declare function PromptArea({ className, value, defaultValue, onValueChange, onSubmit, onStop, onEditLast, placeholder, disabled, busy, maxRows, maxLength, leading, trailing, attachments, submitLabel, stopLabel, onFilesAdded, accept, maxFileSize, onFileRejected, mentions, commands, onMentionSelect, onCommandSelect, 'aria-label': ariaLabel, ...props }: PromptAreaProps): import("react").JSX.Element;
export { PromptArea };

// Defaults
// PromptArea.busy = false
// PromptArea.disabled = false
// PromptArea.maxRows = 8
// PromptArea.placeholder = Send a message… (localized: promptArea.placeholder)
// PromptArea.stopLabel = Stop generating (localized: promptArea.stop)
// PromptArea.submitLabel = Send (localized: promptArea.send)
