// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/prompt-suggestions"

import type { ReactNode } from 'react';
export interface PromptSuggestion {
    id: string;
    label: string;
    icon?: ReactNode;
}
export interface PromptSuggestionsProps extends Omit<React.ComponentProps<'div'>, 'onSelect'> {
    items: PromptSuggestion[];
    onSelect: (item: PromptSuggestion) => void;
}
declare function PromptSuggestions({ items, onSelect, className, ...props }: PromptSuggestionsProps): import("react").JSX.Element;
export { PromptSuggestions };
