// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/property-grid"

import type { ReactNode } from 'react';
export type PropertyValue = string | number | boolean;
export interface PropertyGridItem {
    name: string;
    label: ReactNode;
    type?: 'text' | 'number' | 'select' | 'switch' | 'textarea' | 'custom';
    options?: {
        value: string;
        label: string;
    }[];
    placeholder?: string;
    description?: ReactNode;
    readOnly?: boolean;
    render?: (props: {
        value: PropertyValue;
        onChange: (v: PropertyValue) => void;
        disabled?: boolean;
    }) => ReactNode;
}
export interface PropertyGridProps {
    items: PropertyGridItem[];
    defaultValues?: Record<string, PropertyValue>;
    values?: Record<string, PropertyValue>;
    onValueChange?: (name: string, value: PropertyValue) => void;
    onValuesChange?: (values: Record<string, PropertyValue>) => void;
    maxLabelWidth?: string;
    className?: string;
    id?: string;
}
export declare function PropertyGrid({ items, defaultValues, values, onValueChange, onValuesChange, maxLabelWidth, className, id, }: PropertyGridProps): import("react").JSX.Element;

// Defaults
// PropertyGrid.maxLabelWidth = 30ch
