// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/prose"

export type ProseSize = 'sm' | 'md' | 'lg';
export interface ProseProps extends React.ComponentProps<'div'> {
    size?: ProseSize;
    asChild?: boolean;
}
export declare function Prose({ className, size, asChild, ...props }: ProseProps): import("react").JSX.Element;

// Defaults
// Prose.asChild = false
// Prose.size = md
