// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/push-sheet"

export interface PushSheetProps extends React.ComponentProps<'div'> {
    open: boolean;
    onOpenChange?: (open: boolean) => void;
    side?: 'left' | 'right';
    width?: string;
}
export declare function PushSheet({ open, onOpenChange, side, width, className, style, children, ...props }: PushSheetProps): import("react").JSX.Element;
export declare function PushSheetHeader({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function PushSheetBody({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function PushSheetFooter({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function PushSheetTitle({ id, className, ...props }: React.ComponentProps<'h2'>): import("react").JSX.Element;
export declare function PushSheetDescription({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
export declare const PushSheetClose: import("react").ForwardRefExoticComponent<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & {
    asChild?: boolean;
} & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// PushSheet.side = right
// PushSheet.width = 22.5rem
