// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/qr-code"

import { type ReactNode } from 'react';
export type QrCodeSize = 'sm' | 'md' | 'lg';
export type QrCodeLevel = 'L' | 'M' | 'Q' | 'H';
export interface QrCodeProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    value?: string;
    size?: QrCodeSize;
    level?: QrCodeLevel;
    icon?: ReactNode;
    label?: string;
    loading?: boolean;
}
export declare function QrCode({ value, size, level, icon, label, loading, className, style, ...props }: QrCodeProps): import("react").JSX.Element;

// Defaults
// QrCode.label = QR code (localized: qrCode.label)
// QrCode.level = M
// QrCode.loading = false
// QrCode.size = md
