// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/query-builder"

import type { ReactNode } from 'react';
export type QueryField = {
    name: string;
    label: string;
    type: 'text' | 'number' | 'date' | 'boolean';
} | {
    name: string;
    label: string;
    type: 'select';
    options: {
        value: string;
        label: string;
    }[];
};
export interface QueryCondition {
    id: string;
    field: string;
    operator: string;
    value?: unknown;
}
export interface QueryValue {
    match: 'all' | 'any';
    conditions: QueryCondition[];
}
export interface QueryBuilderProps {
    fields: QueryField[];
    value?: QueryValue;
    defaultValue?: QueryValue;
    onChange?: (value: QueryValue) => void;
    addLabel?: string;
    maxConditions?: number;
    ariaLabel?: string;
    emptyMessage?: ReactNode;
    className?: string;
}
export declare function QueryBuilder({ fields, value, defaultValue, onChange, addLabel, maxConditions, ariaLabel, emptyMessage, className, }: QueryBuilderProps): import("react").JSX.Element;

// Defaults
// QueryBuilder.addLabel = Add condition (localized: queryBuilder.add)
// QueryBuilder.ariaLabel = Filter conditions (localized: queryBuilder.label)
// QueryBuilder.emptyMessage = No conditions yet. Add one to start filtering. (localized: queryBuilder.empty)
