// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/range-field"

import { type ReactNode } from 'react';
export type RangeValue = [number, number];
export interface RangeFieldProps {
    label: ReactNode;
    min: number;
    max: number;
    step?: number;
    value?: RangeValue;
    defaultValue?: RangeValue;
    onValueChange?: (value: RangeValue) => void;
    onValueCommit?: (value: RangeValue) => void;
    minDistance?: number;
    formatValue?: (value: number) => string;
    fromLabel?: string;
    toLabel?: string;
    histogram?: number[];
    description?: ReactNode;
    heightSize?: 'sm' | 'md';
    disabled?: boolean;
    className?: string;
}
export declare function RangeField({ label, min, max, step, value: valueProp, defaultValue, onValueChange, onValueCommit, minDistance, formatValue, fromLabel, toLabel, histogram, description, heightSize, disabled, className, }: RangeFieldProps): import("react").JSX.Element;

// Defaults
// RangeField.disabled = false
// RangeField.formatValue = (v) => String(v)
// RangeField.fromLabel = From (localized: rangeField.from)
// RangeField.heightSize = md
// RangeField.minDistance = 0
// RangeField.step = 1
// RangeField.toLabel = To (localized: rangeField.to)
