// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/rating"

import type { ComponentPropsWithoutRef } from 'react';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
type RatingSize = 'sm' | 'md';
export declare function RatingStar({ fill, size }: {
    fill: number;
    size: RatingSize;
}): import("react").JSX.Element;
type RootProps = Omit<ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>, 'value' | 'defaultValue' | 'onValueChange' | 'orientation' | 'dir'>;
export interface RatingProps extends RootProps {
    value?: number;
    defaultValue?: number;
    onValueChange?: (value: number) => void;
    max?: number;
    size?: RatingSize;
    readOnly?: boolean;
    clearable?: boolean;
    formatLabel?: (value: number, max: number) => string;
}
export declare const Rating: import("react").ForwardRefExoticComponent<RatingProps & import("react").RefAttributes<HTMLDivElement>>;

// Defaults
// Rating.clearable = false
// Rating.defaultValue = 0
// Rating.formatLabel = localized: rating.value
// Rating.max = 5
// Rating.readOnly = false
// Rating.size = md
// RatingStar.size = md
