// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/resizable"

import { Group, Panel, Separator } from 'react-resizable-panels';
export declare function ResizablePanelGroup({ className, orientation, style, ...props }: React.ComponentProps<typeof Group>): import("react").JSX.Element;
export declare function ResizablePanel({ ...props }: React.ComponentProps<typeof Panel>): import("react").JSX.Element;
export interface ResizableHandleProps extends React.ComponentProps<typeof Separator> {
    withHandle?: boolean;
}
export declare function ResizableHandle({ withHandle, className, 'aria-label': ariaLabel, ...props }: ResizableHandleProps): import("react").JSX.Element;

// Defaults
// ResizableHandle.withHandle = false
