// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/reveal"

import { type ReactNode } from 'react';
export type RevealEffect = 'rise' | 'fade' | 'scale' | 'blur';
interface RevealTriggerProps {
    effect?: RevealEffect;
    delay?: number;
    threshold?: number;
    once?: boolean;
}
export interface RevealProps extends RevealTriggerProps, React.HTMLAttributes<HTMLElement> {
    asChild?: boolean;
}
export declare function Reveal({ effect, delay, threshold, once, asChild, className, style, ...props }: RevealProps): import("react").JSX.Element;
export interface RevealGroupProps extends RevealTriggerProps, React.HTMLAttributes<HTMLDivElement> {
    stagger?: number;
    children?: ReactNode;
}
export declare function RevealGroup({ effect, delay, stagger, threshold, once, className, children, ...props }: RevealGroupProps): import("react").JSX.Element;

// Defaults
// Reveal.delay = 0
// Reveal.effect = rise
// Reveal.once = true
// Reveal.threshold = 0.2
// RevealGroup.delay = 0
// RevealGroup.effect = rise
// RevealGroup.once = true
// RevealGroup.stagger = 90
// RevealGroup.threshold = 0.2
