// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/rich-text-editor"

import { type Editor } from '@tiptap/react';
export type RichTextTool = 'textStyle' | 'bold' | 'italic' | 'underline' | 'strike' | 'code' | 'link' | 'bulletList' | 'orderedList' | 'blockquote' | 'codeBlock' | 'history';
export declare const RICH_TEXT_TOOLS_FULL: RichTextTool[];
export declare const RICH_TEXT_TOOLS_BASIC: RichTextTool[];
export interface RichTextEditorProps {
    value?: string;
    defaultValue?: string;
    onValueChange?: (html: string) => void;
    onEditorReady?: (editor: Editor) => void;
    label?: React.ReactNode;
    description?: React.ReactNode;
    error?: boolean | React.ReactNode;
    required?: boolean;
    placeholder?: string;
    disabled?: boolean;
    tools?: RichTextTool[];
    maxLength?: number;
    minHeight?: number | string;
    maxHeight?: number | string;
    name?: string;
    className?: string;
    'aria-label'?: string;
}
export declare function RichTextEditor({ value, defaultValue, onValueChange, onEditorReady, label, description, error, required, placeholder, disabled, tools, maxLength, minHeight, maxHeight, name, className, 'aria-label': ariaLabel, }: RichTextEditorProps): import("react").JSX.Element;

// Defaults
// RichTextEditor.defaultValue = 
// RichTextEditor.disabled = false
// RichTextEditor.minHeight = 160
// RichTextEditor.tools = ['textStyle', 'bold', 'italic', 'underline', 'strike', 'code', 'link', 'bulletList', 'orderedList', 'blockquote', 'codeBlock', 'history']
