// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/scheduler"

import type { StatusTone } from './status-dot';
export type SchedulerView = 'day' | 'week' | 'month';
export interface SchedulerEvent {
    id: string;
    title: string;
    start: Date;
    end: Date;
    allDay?: boolean;
    tone?: StatusTone;
    locked?: boolean;
}
export interface SchedulerProps extends Omit<React.ComponentProps<'div'>, 'onChange'> {
    events: SchedulerEvent[];
    view?: SchedulerView;
    defaultView?: SchedulerView;
    onViewChange?: (view: SchedulerView) => void;
    date?: Date;
    defaultDate?: Date;
    onDateChange?: (date: Date) => void;
    views?: SchedulerView[];
    onEventClick?: (event: SchedulerEvent) => void;
    onEventChange?: (event: SchedulerEvent, next: {
        start: Date;
        end: Date;
    }) => void;
    onSlotClick?: (range: {
        start: Date;
        end: Date;
        allDay: boolean;
    }) => void;
    locale?: string;
    weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    hourHeight?: number;
    scrollToHour?: number;
    maxEventsPerDay?: number;
    now?: Date;
}
export declare function Scheduler({ events, view: viewProp, defaultView, onViewChange, date: dateProp, defaultDate, onDateChange, views, onEventClick, onEventChange, onSlotClick, locale: localeProp, weekStartsOn, hourHeight, scrollToHour, maxEventsPerDay, now: nowProp, className, ...props }: SchedulerProps): import("react").JSX.Element;

// Defaults
// Scheduler.hourHeight = 48
// Scheduler.maxEventsPerDay = 3
// Scheduler.scrollToHour = 8
// Scheduler.views = ['day', 'week', 'month']
// Scheduler.weekStartsOn = 1
