// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/scroll-area"

import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
export interface ScrollAreaProps extends React.ComponentProps<typeof ScrollAreaPrimitive.Root> {
    focusable?: boolean;
    viewportRef?: React.Ref<HTMLDivElement>;
    viewportClassName?: string;
}
export declare function ScrollArea({ className, children, type, scrollHideDelay, focusable, viewportRef, viewportClassName, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, ...props }: ScrollAreaProps): import("react").JSX.Element;
export declare function ScrollBar({ className, orientation, ...props }: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>): import("react").JSX.Element;

// Defaults
// ScrollArea.focusable = true
