// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/secret-field"

export interface SecretFieldProps {
    value: string;
    defaultRevealed?: boolean;
    revealable?: boolean;
    label?: string;
    copyToastTitle?: string;
    className?: string;
}
declare function SecretField({ value, defaultRevealed, revealable, label, copyToastTitle, className, }: SecretFieldProps): import("react").JSX.Element;
export { SecretField };

// Defaults
// SecretField.copyToastTitle = Copied (localized: secretField.copied)
// SecretField.defaultRevealed = false
// SecretField.label = Value (localized: secretField.label)
// SecretField.revealable = true
