// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/select"

import * as SelectPrimitive from '@radix-ui/react-select';
import { type StatusTone } from './status-dot';
import { type BadgeTone } from './badge';
declare const WIDTH_CLASSES: {
    readonly full: "w-full";
    readonly sm: "w-[var(--size-width-width-control-sm)]";
    readonly md: "w-[var(--size-width-width-control-xl)] max-w-full";
    readonly lg: "w-[var(--size-width-width-control-2xl)] max-w-full";
    readonly xl: "w-[var(--size-width-width-control-3xl)] max-w-full";
};
declare const SelectGroup: import("react").ForwardRefExoticComponent<SelectPrimitive.SelectGroupProps & import("react").RefAttributes<HTMLDivElement>>;
declare function SelectValue({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Value>): import("react").JSX.Element;
declare function Select({ heightSize, children, ...props }: React.ComponentProps<typeof SelectPrimitive.Root> & {
    heightSize?: 'sm' | 'md' | 'lg';
}): import("react").JSX.Element;
export interface SelectTriggerProps extends React.ComponentProps<typeof SelectPrimitive.Trigger> {
    widthSize?: keyof typeof WIDTH_CLASSES;
    error?: boolean;
}
declare function SelectTrigger({ className, widthSize, error, children, ...props }: SelectTriggerProps): import("react").JSX.Element;
declare function SelectContent({ className, children, position, sideOffset, ...props }: React.ComponentProps<typeof SelectPrimitive.Content>): import("react").JSX.Element;
declare function SelectLabel({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>): import("react").JSX.Element;
export interface SelectItemProps extends React.ComponentProps<typeof SelectPrimitive.Item> {
    icon?: React.ReactNode;
    iconSize?: 'sm' | 'lg';
    tone?: StatusTone;
    badge?: {
        label: React.ReactNode;
        tone?: BadgeTone;
    };
    description?: React.ReactNode;
}
declare function SelectItem({ className, children, icon, iconSize, tone, badge, description, ...props }: SelectItemProps): import("react").JSX.Element;
declare function SelectSeparator({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Separator>): import("react").JSX.Element;
declare function SelectScrollUpButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>): import("react").JSX.Element;
declare function SelectScrollDownButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>): import("react").JSX.Element;
export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton, };

// Defaults
// Select.heightSize = md
// SelectItem.iconSize = sm
// SelectTrigger.widthSize = md
