// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/separator"

import * as SeparatorPrimitive from '@radix-ui/react-separator';
export type SeparatorEmphasis = 'subtle' | 'strong';
export interface SeparatorProps extends React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root> {
    emphasis?: SeparatorEmphasis;
}
export declare const Separator: import("react").ForwardRefExoticComponent<SeparatorProps & import("react").RefAttributes<HTMLDivElement>>;

// Defaults
// Separator.emphasis = subtle
