// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/sidebar"

import type { ReactNode } from 'react';
import type { StatusTone } from './status-dot';
interface SidebarContextValue {
    collapsed: boolean;
    setCollapsed: (v: boolean | ((p: boolean) => boolean)) => void;
    mobileOpen: boolean;
    setMobileOpen: (v: boolean) => void;
}
export declare function useSidebar(): SidebarContextValue;
export declare function SidebarProvider({ defaultCollapsed, children }: {
    defaultCollapsed?: boolean;
    children: ReactNode;
}): import("react").JSX.Element;
export interface SidebarProps extends React.ComponentProps<'aside'> {
    inverse?: boolean;
}
export declare function Sidebar({ inverse, className, children, ...props }: SidebarProps): import("react").JSX.Element;
export declare function SidebarHeader({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare function SidebarBrand({ className, children, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
export declare const SidebarCollapse: import("react").ForwardRefExoticComponent<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;
export declare function SidebarNav({ className, 'aria-label': ariaLabel, ...props }: React.ComponentProps<'nav'>): import("react").JSX.Element;
export declare function SidebarSection({ label, action, className, children, ...props }: React.ComponentProps<'div'> & {
    label?: string;
    action?: ReactNode;
}): import("react").JSX.Element;
export interface SidebarItemProps extends React.ComponentProps<'a'> {
    icon?: ReactNode;
    badge?: ReactNode;
    badgeTone?: StatusTone;
    actions?: ReactNode;
    active?: boolean;
}
export declare function SidebarItem({ icon, badge, badgeTone, actions, active, className, children, onClick, ...props }: SidebarItemProps): import("react").JSX.Element;
export declare function SidebarFooter({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;

// Defaults
// SidebarItem.badgeTone = neutral
// SidebarProvider.defaultCollapsed = false
