// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/skeleton"

export declare function Skeleton({ className, ...props }: React.ComponentProps<'div'>): import("react").JSX.Element;
