// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/slider"

import * as SliderPrimitive from '@radix-ui/react-slider';
export interface SliderProps extends Omit<React.ComponentProps<typeof SliderPrimitive.Root>, 'value' | 'defaultValue' | 'onValueChange'> {
    value?: number[];
    defaultValue?: number[];
    onValueChange?: (value: number[]) => void;
    formatValue?: (value: number, index: number) => string;
    invalid?: boolean;
    'aria-label'?: string;
    'aria-describedby'?: string;
}
declare function Slider({ className, defaultValue, value, min, max, formatValue, invalid, 'aria-label': ariaLabel, 'aria-describedby': ariaDescribedby, onValueChange, onValueCommit, onKeyDown, minStepsBetweenThumbs, step, ...props }: SliderProps): import("react").JSX.Element;
export { Slider };

// Defaults
// Slider.invalid = false
