// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/sonner"

import type { ReactNode } from 'react';
import { toast as sonnerToast, type ExternalToast, type ToasterProps } from 'sonner';
export interface DsToasterProps extends ToasterProps {
    dark?: boolean;
}
export declare function Toaster({ closeButton, dark, position, toastOptions, icons, ...props }: DsToasterProps): import("react").JSX.Element;
export type ProgressToastData = Omit<ExternalToast, 'description'> & {
    value: number;
    description?: ReactNode;
};
type ToastApi = typeof sonnerToast & {
    progress: (message: Parameters<typeof sonnerToast>[0], data: ProgressToastData) => ReturnType<typeof sonnerToast>;
    accent: (message: Parameters<typeof sonnerToast>[0], data?: ExternalToast) => ReturnType<typeof sonnerToast>;
};
export declare const toast: ToastApi;

// Defaults
// Toaster.dark = false
