// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/sparkline"

export type SparklineTone = 'brand' | 'success' | 'warning' | 'danger' | 'info' | 'muted';
export interface SparklineProps {
    data: number[];
    tone?: SparklineTone;
    area?: boolean;
    showLast?: boolean;
    height?: number;
    width?: number;
    ariaLabel?: string;
    className?: string;
}
export declare function Sparkline({ data, tone, area, showLast, height, width, ariaLabel, className }: SparklineProps): import("react").JSX.Element;

// Defaults
// Sparkline.area = false
// Sparkline.height = 32
// Sparkline.showLast = true
// Sparkline.tone = brand
