// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/spinner"

export declare function Spinner({ className, ...props }: React.ComponentProps<'svg'>): import("react").JSX.Element;
