// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/split-button"

import type { ReactNode } from 'react';
import { type ButtonProps } from './button';
export interface SplitButtonProps extends Omit<ButtonProps, 'children' | 'iconOnly' | 'asChild'> {
    children: ReactNode;
    onMainClick?: () => void;
    menuContent: ReactNode;
    menuLabel?: string;
}
export declare function SplitButton({ children, onMainClick, menuContent, menuLabel, appearance, tone, size, disabled, className, ...props }: SplitButtonProps): import("react").JSX.Element;

// Defaults
// SplitButton.appearance = filled
// SplitButton.menuLabel = More actions (localized: splitButton.menu)
// SplitButton.size = lg
// SplitButton.tone = primary
