// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/stat"

import type { ReactNode } from 'react';
import { type StatusTone } from './status-dot';
export type StatTone = StatusTone;
export interface StatDelta {
    value: string;
    direction: 'up' | 'down' | 'flat';
}
export interface StatProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    label: string;
    value: ReactNode;
    icon?: ReactNode;
    tone?: StatTone;
    toneLabel?: string;
    toneIcon?: boolean;
    delta?: StatDelta;
    variant?: 'card' | 'plain';
}
export declare function Stat({ className, variant, label, value, icon, tone, toneLabel, toneIcon, delta, ...props }: StatProps): import("react").JSX.Element;

// Defaults
// Stat.toneIcon = false
// Stat.variant = card
