// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/status-dot"

export type StatusTone = 'success' | 'warning' | 'danger' | 'neutral' | 'primary' | 'info';
export interface StatusDotProps extends Omit<React.ComponentProps<'span'>, 'children'> {
    tone?: StatusTone;
    inverse?: boolean;
}
export declare function StatusDot({ className, tone, inverse, ...props }: StatusDotProps): import("react").JSX.Element;

// Defaults
// StatusDot.inverse = false
// StatusDot.tone = neutral
