// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/stepper"

import { type ReactNode } from 'react';
export interface StepperStep {
    label: ReactNode;
    description?: ReactNode;
}
export interface StepperProps extends Omit<React.ComponentProps<'ol'>, 'children'> {
    steps: StepperStep[];
    current: number;
    orientation?: 'horizontal' | 'vertical';
    labelAlign?: 'start' | 'center';
    onStepClick?: (index: number) => void;
}
export declare function Stepper({ className, steps, current, orientation, labelAlign, onStepClick, 'aria-label': ariaLabel, ...props }: StepperProps): import("react").JSX.Element;

// Defaults
// Stepper.labelAlign = start
// Stepper.orientation = horizontal
