// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/sticky-action-bar"

import { type ReactNode } from 'react';
export type StickyActionBarVariant = 'bar' | 'floating';
export interface StickyActionBarProps extends Omit<React.ComponentProps<'div'>, 'role'> {
    open?: boolean;
    variant?: StickyActionBarVariant;
    message?: ReactNode;
    position?: 'sticky' | 'fixed';
    onClose?: () => void;
    closeLabel?: string;
    'aria-label'?: string;
}
export declare function StickyActionBar({ open, variant, message, position, onClose, closeLabel, className, children, 'aria-label': ariaLabel, ...props }: StickyActionBarProps): import("react").JSX.Element | null;

// Defaults
// StickyActionBar.closeLabel = Close (localized: common.close)
// StickyActionBar.open = true
// StickyActionBar.position = sticky
// StickyActionBar.variant = bar
