// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/success-check"

export declare function SuccessCheck({ className, ...props }: React.ComponentProps<'svg'>): import("react").JSX.Element;
