// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/surface-effect"

export type SurfaceEffectKind = 'spotlight' | 'beam' | 'tilt' | 'shine' | 'lift';
export interface SurfaceEffectProps extends React.HTMLAttributes<HTMLDivElement> {
    effect: SurfaceEffectKind;
}
export declare function SurfaceEffect({ effect, className, children, onPointerMove, onPointerLeave, ...props }: SurfaceEffectProps): import("react").JSX.Element;
export declare function Aurora({ intensity, className, ...props }: React.HTMLAttributes<HTMLDivElement> & {
    intensity?: 'subtle' | 'vivid';
}): import("react").JSX.Element;

// Defaults
// Aurora.intensity = subtle
