// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/swatch-picker"

import { type VariantProps } from 'class-variance-authority';
export interface SwatchOption {
    value: string;
    label: string;
    color?: string;
    colors?: string[];
    image?: string;
    unavailable?: boolean;
    disabled?: boolean;
}
declare const itemVariants: (props?: ({
    size?: "sm" | "md" | "lg" | null | undefined;
    shape?: "circle" | "square" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
interface SwatchPickerBaseProps extends VariantProps<typeof itemVariants> {
    options: SwatchOption[];
    legend?: React.ReactNode;
    hideValueLabel?: boolean;
    tooltips?: boolean;
    unavailableLabel?: string;
    max?: number;
    className?: string;
    disabled?: boolean;
    'aria-label'?: string;
}
export interface SwatchPickerSingleProps extends SwatchPickerBaseProps {
    type?: 'single';
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    name?: string;
    required?: boolean;
}
export interface SwatchPickerMultipleProps extends SwatchPickerBaseProps {
    type: 'multiple';
    value?: string[];
    defaultValue?: string[];
    onValueChange?: (value: string[]) => void;
}
export type SwatchPickerProps = SwatchPickerSingleProps | SwatchPickerMultipleProps;
export declare function SwatchPicker(props: SwatchPickerProps): import("react").JSX.Element;

// Defaults
// SwatchPicker.unavailableLabel = out of stock (localized: swatchPicker.unavailable)
