// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/swipe-deck"

import type { ReactNode } from 'react';
export type SwipeDirection = 'left' | 'right';
export interface SwipeDeckProps<T> extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> {
    items: T[];
    getKey: (item: T) => string;
    renderCard: (item: T) => ReactNode;
    onSwipe?: (item: T, direction: SwipeDirection) => void;
    empty?: ReactNode;
    depth?: number;
    skipLabel?: string;
    keepLabel?: string;
    hideButtons?: boolean;
}
export declare function SwipeDeck<T>({ items, getKey, renderCard, onSwipe, empty, depth, skipLabel, keepLabel, hideButtons, className, onKeyDown, ...props }: SwipeDeckProps<T>): import("react").JSX.Element;

// Defaults
// SwipeDeck.depth = 2
// SwipeDeck.hideButtons = false
