// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/switch"

import type { ComponentPropsWithoutRef, ReactNode } from 'react';
import * as SwitchPrimitive from '@radix-ui/react-switch';
import { type VariantProps } from 'class-variance-authority';
declare const switchVariants: (props?: ({
    tone?: "warning" | "danger" | "primary" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface SwitchProps extends ComponentPropsWithoutRef<typeof SwitchPrimitive.Root>, VariantProps<typeof switchVariants> {
    label?: ReactNode;
    description?: ReactNode;
    checkIcon?: boolean;
}
export declare const Switch: import("react").ForwardRefExoticComponent<SwitchProps & import("react").RefAttributes<HTMLButtonElement>>;

// Defaults
// Switch.checkIcon = true
// Switch.tone = primary
