// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/table"

type TableProps = React.ComponentProps<'table'> & {
    containerLabel?: string;
    mobileLayout?: 'stack' | 'paged' | 'scroll';
    columnsPerPage?: number;
    stickyFirstColumn?: boolean;
};
export declare function Table({ className, containerLabel, mobileLayout, columnsPerPage, stickyFirstColumn, ...props }: TableProps): import("react").JSX.Element;
export declare function TableHeader({ className, ...props }: React.ComponentProps<'thead'>): import("react").JSX.Element;
export declare function TableBody({ className, ...props }: React.ComponentProps<'tbody'>): import("react").JSX.Element;
export declare function TableRow({ className, ...props }: React.ComponentProps<'tr'>): import("react").JSX.Element;
export declare function TableHead({ className, ...props }: React.ComponentProps<'th'>): import("react").JSX.Element;
type TableCellProps = React.ComponentProps<'td'> & {
    label?: string | false;
    stackAction?: boolean;
};
export declare function TableCell({ className, label, stackAction, ...props }: TableCellProps): import("react").JSX.Element;
export declare function TableCaption({ className, ...props }: React.ComponentProps<'caption'>): import("react").JSX.Element;

// Defaults
// Table.columnsPerPage = 2
// Table.mobileLayout = stack
// Table.stickyFirstColumn = false
