// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/table-skeleton"

export declare function useFirstLoad(delay?: number): boolean;
export interface SkeletonCol {
    align?: 'right';
    width?: string;
    control?: boolean;
}
export declare function TableSkeletonRows({ rows, columns }: {
    rows?: number;
    columns: number | SkeletonCol[];
}): import("react").JSX.Element;

// Defaults
// TableSkeletonRows.rows = 6
