// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/tabs"

import { type ReactNode } from 'react';
import * as TabsPrimitive from '@radix-ui/react-tabs';
export declare const Tabs: import("react").ForwardRefExoticComponent<TabsPrimitive.TabsProps & import("react").RefAttributes<HTMLDivElement>>;
export interface TabsListProps extends React.ComponentProps<typeof TabsPrimitive.List> {
    variant?: 'underline' | 'chips';
}
export declare function TabsList({ className, children, variant, onPointerOver, onPointerLeave, ...props }: TabsListProps): import("react").JSX.Element;
export interface TabsTriggerProps extends React.ComponentProps<typeof TabsPrimitive.Trigger> {
    icon?: ReactNode;
    onClose?: (event: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => void;
    closeLabel?: string;
}
export declare function TabsTrigger({ className, icon, onClose, closeLabel, children, onKeyDown, ...props }: TabsTriggerProps): import("react").JSX.Element;
export declare function TabsContent({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>): import("react").JSX.Element;

// Defaults
// TabsList.variant = underline
