// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/tag-input"

import { type ReactNode } from 'react';
export type TagInputSize = 'sm' | 'md';
export interface TagInputProps {
    value?: string[];
    defaultValue?: string[];
    onValueChange?: (value: string[]) => void;
    validate?: (tag: string) => string | undefined;
    transform?: (tag: string) => string;
    delimiters?: string[];
    max?: number;
    placeholder?: string;
    description?: ReactNode;
    error?: string;
    heightSize?: TagInputSize;
    disabled?: boolean;
    readOnly?: boolean;
    id?: string;
    name?: string;
    className?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
}
export declare function TagInput({ value: valueProp, defaultValue, onValueChange, validate, transform, delimiters, max, placeholder, description, error, heightSize, disabled, readOnly, id, name, className, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, }: TagInputProps): import("react").JSX.Element;

// Defaults
// TagInput.defaultValue = []
// TagInput.delimiters = ['Enter', ',', ';']
// TagInput.disabled = false
// TagInput.heightSize = md
// TagInput.placeholder = Type and press Enter (localized: tagInput.placeholder)
// TagInput.readOnly = false
