// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/terminal"

import type { ReactNode } from 'react';
export type TerminalLevel = 'cmd' | 'ok' | 'success' | 'warn' | 'warning' | 'err' | 'error' | 'info' | 'dim' | 'muted';
export interface TerminalLineData {
    id?: string;
    text: string;
    level?: TerminalLevel;
}
export type TerminalConnection = 'connected' | 'connecting' | 'down';
export interface TerminalProps extends React.ComponentProps<'div'> {
    lines?: TerminalLineData[];
    user?: string;
    host?: string;
    connection?: TerminalConnection;
    status?: string;
    tools?: ReactNode;
    hideHeader?: boolean;
    bodyClassName?: string;
    ariaLabel?: string;
    live?: 'polite' | 'off';
    inverse?: boolean;
    children?: ReactNode;
}
export declare function Terminal({ className, lines, user, host, connection, status, tools, hideHeader, bodyClassName, ariaLabel, live, inverse, children, ...props }: TerminalProps): import("react").JSX.Element;
export interface TerminalHeaderProps extends React.ComponentProps<'div'> {
    user?: string;
    host?: string;
    connection?: TerminalConnection;
    status?: string;
    inverse?: boolean;
}
export declare function TerminalHeader({ className, user, host, connection, status, inverse, children, ...props }: TerminalHeaderProps): import("react").JSX.Element;
export interface TerminalBodyProps extends React.ComponentProps<'div'> {
    lines?: TerminalLineData[];
    ariaLabel?: string;
    live?: 'polite' | 'off';
    inverse?: boolean;
}
export declare function TerminalBody({ className, lines, ariaLabel, live, inverse, children, ...props }: TerminalBodyProps): import("react").JSX.Element;
export interface TerminalLineProps extends React.ComponentProps<'div'> {
    level?: TerminalLevel;
    inverse?: boolean;
}
export declare function TerminalLine({ className, level, inverse, children, ...props }: TerminalLineProps): import("react").JSX.Element;

// Defaults
// Terminal.ariaLabel = Terminal output (localized: terminal.output)
// Terminal.connection = connected
// Terminal.inverse = true
// Terminal.live = polite
// TerminalBody.ariaLabel = Terminal output (localized: terminal.output)
// TerminalBody.inverse = false
// TerminalBody.live = polite
// TerminalHeader.connection = connected
// TerminalHeader.inverse = false
// TerminalLine.inverse = false
