// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/textarea"

import type { TextareaHTMLAttributes, ReactNode } from 'react';
import { type VariantProps } from 'class-variance-authority';
declare const textareaVariants: (props?: ({
    error?: boolean | null | undefined;
    widthSize?: "sm" | "md" | "lg" | "xl" | "full" | null | undefined;
    heightSize?: "sm" | "md" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface TextAreaProps extends TextareaHTMLAttributes<HTMLTextAreaElement>, Omit<VariantProps<typeof textareaVariants>, 'error'> {
    label?: ReactNode;
    required?: boolean;
    optional?: boolean;
    description?: ReactNode;
    error?: boolean | ReactNode;
    labelPosition?: 'top' | 'left';
}
export declare const TextArea: import("react").ForwardRefExoticComponent<TextAreaProps & import("react").RefAttributes<HTMLTextAreaElement>>;

// Defaults
// TextArea.heightSize = md
// TextArea.labelPosition = top
// TextArea.widthSize = full
