// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/text-field"

import type { ReactNode } from 'react';
import { type TextFieldProps as BaseTextFieldProps } from './text-field-variants';
declare const WIDTH_CLASSES: {
    readonly full: "w-full";
    readonly sm: "w-[var(--size-width-width-control-sm)]";
    readonly md: "w-[var(--size-width-width-control-xl)] max-w-full";
    readonly lg: "w-[var(--size-width-width-control-2xl)] max-w-full";
    readonly xl: "w-[var(--size-width-width-control-3xl)] max-w-full";
};
export interface TextFieldProps extends BaseTextFieldProps {
    leftIcon?: ReactNode;
    rightIcon?: ReactNode;
    widthSize?: keyof typeof WIDTH_CLASSES;
    labelPosition?: 'top' | 'left';
}
export declare const TextField: import("react").ForwardRefExoticComponent<TextFieldProps & import("react").RefAttributes<HTMLInputElement>>;

// Defaults
// TextField.heightSize = md
// TextField.labelPosition = top
// TextField.widthSize = md
