// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/text-field-variants"

import { type VariantProps } from 'class-variance-authority';
import type { InputHTMLAttributes, ReactNode } from 'react';
export declare const textFieldVariants: (props?: ({
    error?: boolean | null | undefined;
    success?: boolean | null | undefined;
    heightSize?: "sm" | "md" | "lg" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface TextFieldProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'>, Omit<VariantProps<typeof textFieldVariants>, 'error' | 'success'> {
    label?: ReactNode;
    required?: boolean;
    optional?: boolean;
    description?: ReactNode;
    error?: boolean | ReactNode;
    success?: boolean | ReactNode;
}
