// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/text-effect"

import { type ElementType } from 'react';
export type TextEffectKind = 'split' | 'scramble' | 'shimmer' | 'typewriter';
export interface TextEffectProps extends Omit<React.HTMLAttributes<HTMLElement>, 'children'> {
    effect: TextEffectKind;
    children?: string;
    phrases?: string[];
    trigger?: 'view' | 'hover' | 'mount';
    as?: ElementType;
}
export declare function TextEffect({ effect, children, phrases, trigger, as: Tag, className, ...props }: TextEffectProps): import("react").JSX.Element;

// Defaults
// TextEffect.as = span
// TextEffect.children = 
// TextEffect.trigger = view
