// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/ticker-list"

export interface TickerListProps extends React.HTMLAttributes<HTMLDivElement> {
    visible?: number;
    interval?: number;
    hidePause?: boolean;
}
export declare function TickerList({ visible, interval, hidePause, className, children, onPointerEnter, onPointerLeave, onFocus, onBlur, 'aria-label': ariaLabel, ...props }: TickerListProps): import("react").JSX.Element;

// Defaults
// TickerList.hidePause = false
// TickerList.interval = 2500
// TickerList.visible = 3
