// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/time-field"

export declare function formatTime(value: string, hourCycle: 12 | 24): string;
export interface TimeFieldProps {
    value?: string;
    defaultValue?: string;
    onChange?: (value: string) => void;
    step?: number;
    min?: string;
    max?: string;
    hourCycle?: 12 | 24;
    placeholder?: string;
    disabled?: boolean;
    id?: string;
    className?: string;
    contentClassName?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-invalid'?: boolean | 'true' | 'false';
    'aria-describedby'?: string;
}
export declare function TimeField({ value, defaultValue, onChange, step, min, max, hourCycle, placeholder, disabled, id, className, contentClassName, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, 'aria-invalid': ariaInvalid, 'aria-describedby': ariaDescribedby, }: TimeFieldProps): import("react").JSX.Element;

// Defaults
// TimeField.hourCycle = 12
// TimeField.max = 23:59
// TimeField.min = 00:00
// TimeField.placeholder = Select time (localized: timeField.placeholder)
// TimeField.step = 30
