// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/timeline"

import type { ReactNode } from 'react';
export type TimelineTone = 'neutral' | 'success' | 'warning' | 'danger' | 'info' | 'primary';
export declare function Timeline({ className, ...props }: React.ComponentProps<'ol'>): import("react").JSX.Element;
export interface TimelineItemProps extends React.ComponentProps<'li'> {
    tone?: TimelineTone;
    icon?: ReactNode;
    time?: ReactNode;
    toneLabel?: string;
}
export declare function TimelineItem({ className, tone, icon, time, toneLabel, children, ...props }: TimelineItemProps): import("react").JSX.Element;
export declare function TimelineTitle({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
export declare function TimelineDescription({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;
export declare function TimelineTime({ className, ...props }: React.ComponentProps<'p'>): import("react").JSX.Element;

// Defaults
// TimelineItem.tone = neutral
