// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/time-range-picker"

export type TimeRange = {
    start?: string;
    end?: string;
};
export interface TimeRangePickerProps {
    value?: TimeRange;
    defaultValue?: TimeRange;
    onChange?: (value: TimeRange) => void;
    step?: number;
    hourCycle?: 12 | 24;
    min?: string;
    max?: string;
    disabled?: boolean;
    startLabel?: string;
    endLabel?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    className?: string;
}
export declare function TimeRangePicker({ value, defaultValue, onChange, step, hourCycle, min, max, disabled, startLabel, endLabel, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, className, }: TimeRangePickerProps): import("react").JSX.Element;

// Defaults
// TimeRangePicker.endLabel = End time (localized: timeRangePicker.end)
// TimeRangePicker.hourCycle = 12
// TimeRangePicker.max = 23:59
// TimeRangePicker.min = 00:00
// TimeRangePicker.startLabel = Start time (localized: timeRangePicker.start)
// TimeRangePicker.step = 30
