// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/toggle"

import * as TogglePrimitive from '@radix-ui/react-toggle';
import { type VariantProps } from 'class-variance-authority';
declare const toggleVariants: (props?: ({
    appearance?: "outlined" | "tonal" | "ghost" | null | undefined;
    size?: "sm" | "md" | "lg" | null | undefined;
    iconOnly?: boolean | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
export interface ToggleProps extends React.ComponentProps<typeof TogglePrimitive.Root>, Omit<VariantProps<typeof toggleVariants>, 'iconOnly'> {
    iconOnly?: boolean;
}
declare function Toggle({ className, appearance, size, iconOnly, children, ...props }: ToggleProps): import("react").JSX.Element;
export { Toggle, toggleVariants };
