// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/toggle-group"

import * as ToggleGroupPrimitive from '@radix-ui/react-toggle-group';
import type { VariantProps } from 'class-variance-authority';
import { toggleVariants } from './toggle';
export type ToggleGroupProps = React.ComponentProps<typeof ToggleGroupPrimitive.Root> & Omit<VariantProps<typeof toggleVariants>, 'iconOnly'>;
declare function ToggleGroup({ className, appearance, size, children, ...props }: ToggleGroupProps): import("react").JSX.Element;
export interface ToggleGroupItemProps extends React.ComponentProps<typeof ToggleGroupPrimitive.Item>, Omit<VariantProps<typeof toggleVariants>, 'iconOnly'> {
    iconOnly?: boolean;
}
declare function ToggleGroupItem({ className, children, appearance, size, iconOnly, ...props }: ToggleGroupItemProps): import("react").JSX.Element;
export { ToggleGroup, ToggleGroupItem };

// Defaults
// ToggleGroup.appearance = ghost
