// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/tone-icon"

import type { ReactNode } from 'react';
import type { StatusTone } from './status-dot';
export interface ToneIconProps extends Omit<React.ComponentProps<'span'>, 'children'> {
    tone: StatusTone;
    shape?: 'circle' | 'square';
    size?: 'sm' | 'md' | 'lg';
    icon?: ReactNode;
}
export declare function ToneIcon({ className, tone, shape, size, icon, ...props }: ToneIconProps): import("react").JSX.Element;

// Defaults
// ToneIcon.shape = circle
// ToneIcon.size = md
