// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/toolbar"

import * as ToolbarPrimitive from '@radix-ui/react-toolbar';
import type { VariantProps } from 'class-variance-authority';
import { buttonVariants } from './button';
export declare const Toolbar: import("react").ForwardRefExoticComponent<Omit<ToolbarPrimitive.ToolbarProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("react").RefAttributes<HTMLDivElement>>;
export type ToolbarButtonProps = Omit<React.ComponentProps<typeof ToolbarPrimitive.Button>, 'type'> & VariantProps<typeof buttonVariants> & {
    appearance?: VariantProps<typeof buttonVariants>['appearance'];
};
export declare const ToolbarButton: import("react").ForwardRefExoticComponent<Omit<ToolbarButtonProps, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;
export type ToolbarGroupProps = Omit<React.ComponentProps<typeof ToolbarPrimitive.ToggleGroup>, 'type'> & {
    type?: 'single' | 'multiple';
};
export declare function ToolbarGroup({ className, type, ...props }: ToolbarGroupProps): import("react").JSX.Element;
export declare function ToolbarSeparator({ className, ...props }: React.ComponentProps<typeof ToolbarPrimitive.Separator>): import("react").JSX.Element;
export declare function ToolbarLink({ className, ...props }: React.ComponentProps<typeof ToolbarPrimitive.Link>): import("react").JSX.Element;

// Defaults
// ToolbarButton.appearance = ghost
// ToolbarButton.size = lg
// ToolbarButton.tone = neutral
