// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/tooltip"

import * as TooltipPrimitive from '@radix-ui/react-tooltip';
export declare function TooltipProvider({ delayDuration, ...props }: React.ComponentProps<typeof TooltipPrimitive.Provider>): import("react").JSX.Element;
export declare function Tooltip(props: React.ComponentProps<typeof TooltipPrimitive.Root>): import("react").JSX.Element;
export declare const TooltipTrigger: import("react").ForwardRefExoticComponent<TooltipPrimitive.TooltipTriggerProps & import("react").RefAttributes<HTMLButtonElement>>;
export type TooltipTone = 'neutral' | 'success' | 'danger';
export declare function TooltipContent({ className, sideOffset, collisionPadding, showArrow, tone, children, ...props }: React.ComponentProps<typeof TooltipPrimitive.Content> & {
    showArrow?: boolean;
    tone?: TooltipTone;
}): import("react").JSX.Element;

// Defaults
// TooltipContent.showArrow = true
// TooltipContent.tone = neutral
