// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/topbar"

import type { ReactNode } from 'react';
export type TopbarOrientation = 'horizontal' | 'vertical';
export interface TopbarProps extends React.ComponentProps<'header'> {
    orientation?: TopbarOrientation;
}
export declare function Topbar({ className, orientation, children, ...props }: TopbarProps): import("react").JSX.Element;
export declare const TopbarMenu: import("react").ForwardRefExoticComponent<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & import("react").RefAttributes<HTMLButtonElement>>;
export interface TopbarSearchProps extends Omit<React.ComponentProps<'input'>, 'value' | 'onChange' | 'defaultValue'> {
    placeholder?: string;
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (open: boolean) => void;
    children?: ReactNode;
}
export declare function TopbarSearch({ className, placeholder, value, defaultValue, onValueChange, open, defaultOpen, onOpenChange, children, ...props }: TopbarSearchProps): import("react").JSX.Element;
export declare function TopbarSpacer(): import("react").JSX.Element;
export interface TopbarActionProps extends React.ComponentProps<'button'> {
    badge?: boolean;
}
export declare function TopbarAction({ className, badge, 'aria-label': ariaLabel, ...props }: TopbarActionProps): import("react").JSX.Element;

// Defaults
// Topbar.orientation = horizontal
// TopbarSearch.placeholder = Search sites, servers, users… (localized: topbar.searchPlaceholder)
