// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/tree"

import type { ReactNode } from 'react';
export interface TreeNode {
    id: string;
    label: ReactNode;
    icon?: ReactNode;
    children?: TreeNode[];
    disabled?: boolean;
    textValue?: string;
}
export interface TreeProps extends Omit<React.ComponentProps<'ul'>, 'onSelect'> {
    items: TreeNode[];
    defaultExpandedIds?: string[];
    expandedIds?: string[];
    onExpandedChange?: (ids: string[]) => void;
    defaultSelectedId?: string;
    selectedId?: string;
    onSelect?: (id: string, node: TreeNode) => void;
}
export declare function Tree({ className, items, defaultExpandedIds, expandedIds, onExpandedChange, defaultSelectedId, selectedId, onSelect, ...props }: TreeProps): import("react").JSX.Element;
