// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/undo-toast"

import type { ReactNode } from 'react';
export interface UndoToastOptions {
    title: string;
    description?: string;
    duration?: number;
    undoLabel?: string;
    icon?: ReactNode;
    onUndo?: () => void;
    onCommit?: () => void;
}
export declare function undoToast({ title, description, duration, undoLabel, icon, onUndo, onCommit }: UndoToastOptions): string | number;
