// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/url-tabs"

import { Tabs } from './tabs';
export type UrlTabsNavigate = (url: string) => void;
export declare function useUrlTabs(param?: string, defaultValue?: string, navigate?: UrlTabsNavigate, values?: readonly string[]): {
    value: string;
    onValueChange: (next: string) => void;
};
export declare function UrlTabs({ param, defaultValue, navigate, values, ...props }: Omit<React.ComponentProps<typeof Tabs>, 'value' | 'onValueChange'> & {
    param?: string;
    navigate?: UrlTabsNavigate;
    values?: readonly string[];
}): import("react").JSX.Element;

// Defaults
// UrlTabs.param = tab
