// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/usage-bar"

export interface UsageSegment {
    label: string;
    value: number;
    colorVar?: string;
}
export interface UsageBarProps extends Omit<React.ComponentProps<'div'>, 'children'> {
    segments: UsageSegment[];
    total?: number;
    showLegend?: boolean;
    formatValue?: (n: number) => string;
}
export declare function UsageBar({ className, segments, total, showLegend, formatValue, ...props }: UsageBarProps): import("react").JSX.Element;

// Defaults
// UsageBar.formatValue = (n) => String(n)
// UsageBar.showLegend = true
