// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/use-theme"

export type Theme = 'light' | 'dark';
export declare function useTheme(): {
    resolvedTheme: Theme;
    setTheme: (theme: Theme) => void;
};
