// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/use-density"

export type Density = 'compact' | 'default' | 'comfortable';
export declare function useDensity(): {
    density: Density;
    setDensity: (next: Density) => void;
};
