// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/ui/wheel-picker"

export interface WheelPickerOption {
    value: string;
    label: string;
}
export interface WheelPickerProps extends Omit<React.ComponentProps<'div'>, 'onChange' | 'defaultValue'> {
    options: WheelPickerOption[];
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    rows?: 3 | 5;
    disabled?: boolean;
}
export declare function WheelPicker({ options, value, defaultValue, onValueChange, rows, disabled, className, 'aria-label': ariaLabel, ...props }: WheelPickerProps): import("react").JSX.Element;

// Defaults
// WheelPicker.disabled = false
// WheelPicker.rows = 3
