// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/search/demo-data"

import type { SearchItem } from './types';
export declare const DEMO_INDEX: SearchItem[];
export declare const DEMO_RECENT: string[];
export declare const DEMO_POPULAR: SearchItem[];
