// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/search/types"

export type SearchType = 'domain' | 'database' | 'project' | 'user' | 'setting' | 'article';
export interface SearchItem {
    id: string;
    type: SearchType;
    title: string;
    context?: string;
    snippet?: string;
    meta?: string;
    href: string;
}
