#!/usr/bin/env node
/**
 * Public API report for @theya/shadcn — one declaration file per entry
 * point in package.json `exports`, written to `api/`, plus the props'
 * default values (which declarations can't show) from the generated spec.
 *
 * Why: an app breaks when an export, a prop, a prop value or a default
 * changes. Committing the report makes every such change show up as a
 * diff in review, and `--check` fails until the report is updated — the
 * moment to add a changeset (see RELEASING.md).
 *
 *   pnpm api         regenerate api/
 *   pnpm api:check   exit 1 if api/ is stale; lists removed/changed lines
 *
 * Comments are stripped, so editing a JSDoc doesn't count as an API change.
 * Run `pnpm spec` first: defaults are read from spec/components.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'api');
const CHECK = process.argv.includes('--check');
const PKG = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const NOT_API = /\.(stories|guidelines|test)\.tsx?$/;

/** package.json exports → { key: 'ui/button', file: absolute source path }. */
function entries() {
  const list = new Map();
  for (const [key, target] of Object.entries(PKG.exports)) {
    if (typeof target !== 'string' || !/\.tsx?$/.test(target) && !target.includes('*')) continue;
    if (!key.includes('*')) {
      if (/\.tsx?$/.test(target)) list.set(key.replace(/^\.\//, ''), path.join(ROOT, target));
      continue;
    }
    // "./ui/*": "./src/components/ui/*.tsx" — every matching file directly in that folder.
    const [dirPart, extPart] = target.split('*');
    const dir = path.join(ROOT, dirPart);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      // Only TypeScript entries have an API to report (styles/* is CSS).
      if (!f.endsWith(extPart) || !/\.tsx?$/.test(f) || NOT_API.test(f)) continue;
      const name = f.slice(0, -extPart.length);
      list.set(key.replace(/^\.\//, '').replace('*', name), path.join(dir, f));
    }
  }
  return [...list].map(([key, file]) => ({ key, file })).sort((a, b) => a.key.localeCompare(b.key));
}

function emitDeclarations(files) {
  const configPath = path.join(ROOT, 'tsconfig.json');
  const cfg = ts.parseJsonConfigFileContent(ts.readConfigFile(configPath, ts.sys.readFile).config, ts.sys, ROOT);
  const options = {
    ...cfg.options,
    noEmit: false,
    declaration: true,
    emitDeclarationOnly: true,
    removeComments: true,
    stripInternal: true,
    rootDir: ROOT,
    outDir: '/__api__',
    incremental: false,
  };
  const program = ts.createProgram(files, options);
  const wanted = new Set(files.map((f) => path.relative(ROOT, f).replace(/\.tsx?$/, '.d.ts')));
  const out = new Map();
  const { diagnostics } = program.emit(undefined, (fileName, data) => {
    const rel = path.relative('/__api__', fileName);
    if (wanted.has(rel)) out.set(rel, data);
  });
  const problems = diagnostics.filter((d) => d.category === ts.DiagnosticCategory.Error);
  for (const d of problems.slice(0, 10)) {
    const where = d.file ? `${path.relative(ROOT, d.file.fileName)}: ` : '';
    console.warn(`declaration warning — ${where}${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`);
  }
  return out;
}

/** Default values of props, which a .d.ts can't express. */
function defaultsFor(key) {
  if (!key.startsWith('ui/')) return [];
  const dir = path.join(ROOT, 'spec/components');
  const base = key.slice(3);
  const lines = [];
  for (const f of fs.existsSync(dir) ? fs.readdirSync(dir) : []) {
    if (f !== `${base}.json` && !f.startsWith(`${base}.`)) continue;
    const rec = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
    for (const c of rec.components ?? []) for (const p of c.props) if (p.default !== undefined) lines.push(`${c.name}.${p.name} = ${p.default}`);
  }
  return lines.sort();
}

const HEADER = '// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.\n';

function build() {
  const list = entries();
  const dts = emitDeclarations(list.map((e) => e.file));
  const files = new Map();
  for (const { key, file } of list) {
    const rel = path.relative(ROOT, file).replace(/\.tsx?$/, '.d.ts');
    let body = dts.get(rel);
    if (body === undefined) body = '// (no declarations emitted)\n';
    // An empty `export {}` marker adds nothing to the report.
    body = body.replace(/^export \{\};\n?/m, '');
    const defaults = defaultsFor(key);
    const tail = defaults.length ? `\n// Defaults\n${defaults.map((l) => `// ${l}`).join('\n')}\n` : '';
    files.set(`${key}.d.ts`, `${HEADER}// import from "${PKG.name}/${key}"\n\n${body.trimEnd()}\n${tail}`);
  }
  return files;
}

/** Lines in `a` that are not in `b` — enough to show what was removed or changed. */
const missing = (a, b) => {
  const set = new Set(b.split('\n'));
  // Header lines aside, comments here are the `// Component.prop = default` list — keep those.
  return a.split('\n').filter((l) => l.trim() && !/^\/\/ (Public API|import from|Defaults$)/.test(l) && !set.has(l));
};

const files = build();
let changed = 0;
const report = [];
for (const [rel, content] of files) {
  const abs = path.join(OUT, rel);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (current === content) continue;
  changed++;
  if (CHECK) {
    if (current === null) report.push(`+ new entry ${rel}`);
    else {
      for (const l of missing(current, content)) report.push(`- ${rel}: ${l.trim()}`);
      for (const l of missing(content, current)) report.push(`+ ${rel}: ${l.trim()}`);
    }
  } else {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
}
// Entries that no longer exist.
const walk = (d) => (fs.existsSync(d) ? fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])) : []);
for (const abs of walk(OUT)) {
  const rel = path.relative(OUT, abs);
  if (files.has(rel)) continue;
  changed++;
  if (CHECK) report.push(`- removed entry ${rel}`);
  else fs.rmSync(abs, { force: true });
}

if (CHECK && changed) {
  console.error(`Public API changed in ${changed} entr${changed === 1 ? 'y' : 'ies'}:\n`);
  console.error(report.slice(0, 80).join('\n') + (report.length > 80 ? `\n… ${report.length - 80} more` : ''));
  console.error(
    `\nRun \`pnpm api\`, review the diff in api/ and add a changeset in the same commit.` +
      `\nLines marked "-" were removed or changed: while versions are 0.x that is a minor (breaking) change — see RELEASING.md.`,
  );
  process.exit(1);
}
console.log(`${files.size} entries · ${changed} ${CHECK ? 'stale' : 'written'}`);
