// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/catalog/demo-data"

import type { CatalogItem } from './types';
import type { Review } from './reviews';
import type { SpecGroup } from './spec-sheet';
import type { CategoryTile, CuratedPick } from './category-landing';
export declare const DEMO_ITEMS: CatalogItem[];
export declare const DEMO_ITEM: CatalogItem;
export declare const DEMO_IMAGES: {
    src: string;
    alt: string;
}[];
export declare const DEMO_HIGHLIGHTS: string[];
export declare const DEMO_DESCRIPTION: ({
    body: string;
    title?: undefined;
} | {
    title: string;
    body: string;
})[];
export declare const DEMO_SPECS: SpecGroup[];
export declare const DEMO_REVIEWS: Review[];
export declare const DEMO_REVIEW_SUMMARY: {
    readonly average: 4.6;
    readonly count: 640;
    readonly distribution: {
        readonly 5: 452;
        readonly 4: 118;
        readonly 3: 38;
        readonly 2: 17;
        readonly 1: 15;
    };
};
export declare const DEMO_CATEGORIES: CategoryTile[];
export declare const DEMO_POPULAR: {
    category: string;
    items: CatalogItem[];
    total: number;
    href: string;
};
export declare const DEMO_PICKS: CuratedPick[];
export declare const DEMO_HARDWARE: (CatalogItem & {
    image: string;
})[];
export declare const DEMO_SCREENSHOTS: string[];
