// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/catalog/types"

export type CatalogIconKey = 'shield' | 'backup' | 'search' | 'speed' | 'mail' | 'code' | 'stats' | 'language' | 'bug' | 'cloud';
export interface CatalogItem {
    id: string;
    name: string;
    vendor: string;
    category: string;
    icon: CatalogIconKey;
    summary: string;
    rating: number;
    reviewCount: number;
    installs: number;
    price: number;
    compatibility: string[];
    added: string;
}
