// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/a11y-dev"

export declare function useMissingNameWarning(component: string, id: string): void;
