// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/accept"

export declare function matchesAccept(file: File, accept: string | undefined): boolean;
