// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/chart-summary"

export declare function seriesRange(points: ReadonlyArray<{
    label: string | number;
    value: unknown;
}>, fmt: (v: number) => string, range: (first: string, last: string, peak: string, peakLabel: string) => string): string | null;
