// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/deprecation"

export declare function warnDeprecated(key: string, message: string): void;
