// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/i18n"

import { type ReactNode } from 'react';
import type { Locale as DateFnsLocale } from 'date-fns';
import { en, type TheyaMessages } from './locale-en';
export type { TheyaMessages };
export { en };
type DeepPartial<T> = {
    [K in keyof T]?: T[K] extends (...args: never[]) => unknown ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};
export type TheyaMessagesOverride = DeepPartial<TheyaMessages>;
export interface TheyaI18n {
    locale: string;
    dateLocale?: DateFnsLocale;
    t: TheyaMessages;
}
export interface TheyaLocaleBundle {
    locale: string;
    messages: TheyaMessagesOverride;
    dateLocale?: DateFnsLocale;
    dir: 'ltr' | 'rtl';
}
export declare function getTheyaMessages(): TheyaMessages;
export interface TheyaLocaleProviderProps {
    locale: string;
    messages?: TheyaMessagesOverride;
    dateLocale?: DateFnsLocale;
    dir?: 'ltr' | 'rtl';
    syncDocument?: boolean;
    children?: ReactNode;
}
export declare function TheyaLocaleProvider({ locale, messages, dateLocale, dir, syncDocument, children }: TheyaLocaleProviderProps): import("react").FunctionComponentElement<import("react").ProviderProps<TheyaI18n>>;
export declare function useTheyaI18n(): TheyaI18n;
export declare function pseudoLocalize<T>(messages: T): T;
