// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/icon-only"

export declare function isIconOnlyContent(children: React.ReactNode): boolean;
