// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/locale-zh"

import type { TheyaLocaleBundle } from './i18n';
import type { TheyaMessages } from './locale-en';
export declare const zh: TheyaMessages;
export declare const zhLocale: TheyaLocaleBundle;
