// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/locale-de"

import type { TheyaLocaleBundle } from './i18n';
import type { TheyaMessages } from './locale-en';
export declare const de: TheyaMessages;
export declare const deLocale: TheyaLocaleBundle;
