// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/locale-ar"

import type { TheyaLocaleBundle } from './i18n';
import type { TheyaMessages } from './locale-en';
export declare const ar: TheyaMessages;
export declare const arLocale: TheyaLocaleBundle;
