// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/locale-en"

import { type ReactNode } from 'react';
export declare const en: {
    common: {
        close: string;
        clear: string;
        cancel: string;
        loading: string;
        noResults: string;
        copied: string;
        copyFailed: string;
        remove: (name: string) => string;
        more: (n: number) => string;
    };
    alert: {
        dismiss: string;
    };
    announcementBar: {
        dismiss: string;
        label: string;
    };
    autocomplete: {
        suggestions: string;
    };
    breadcrumb: {
        label: string;
        more: string;
        showMore: (n: number) => string;
    };
    carousel: {
        label: string;
        previous: string;
        next: string;
        slides: string;
        goTo: (n: number) => string;
    };
    chart: {
        trend: (points: number) => string;
        seriesTrend: (names: string, points: number) => string;
        range: (first: string, last: string, peak: string, peakLabel: string) => string;
        comparison: (count: number, label: string, value: string) => string;
        noData: string;
        total: string;
    };
    chartRangeSelection: {
        label: string;
        roleDescription: string;
        selected: (from: string, to: string) => string;
        cleared: string;
        help: string;
    };
    chat: {
        conversation: string;
        typing: string;
    };
    holdToTalk: {
        label: string;
        release: string;
    };
    speedDial: {
        open: string;
        close: string;
    };
    codeBlock: {
        copy: string;
    };
    codeEditor: {
        label: string;
    };
    combobox: {
        placeholder: string;
        create: (query: string) => string;
        clear: string;
        open: string;
        options: string;
    };
    command: {
        title: string;
        description: string;
        navigate: string;
        select: string;
    };
    confirmDialog: {
        confirm: string;
        typeToConfirm: (value: ReactNode) => ReactNode;
    };
    copyButton: {
        copy: string;
        copied: string;
        announced: string;
    };
    dataTableCell: {
        unlimited: string;
        badges: (n: number) => string;
    };
    table: {
        columnPages: string;
        showColumns: (from: number, to: number, total: number) => string;
    };
    marquee: {
        pause: string;
        play: string;
    };
    dataTable: {
        selectAll: string;
        selectAllTooltip: string;
        selectAllOnPage: string;
        clearSelection: string;
        selected: string;
        bulkActions: string;
        moreBulkActions: string;
        loadingMore: string;
        rowActions: string;
        actionsColumn: string;
        selectColumn: string;
        selectRow: (label?: string) => string;
        viewDetails: (label?: string) => string;
        previous: string;
        next: string;
        goToPage: (n: number) => string;
    };
    datePicker: {
        placeholder: string;
        clear: string;
    };
    dateRangePicker: {
        placeholder: string;
        clear: string;
    };
    timeField: {
        placeholder: string;
        time: string;
        timeOf: (label: string) => string;
        noMatch: string;
    };
    diffViewer: {
        expand: (n: number) => string;
        empty: string;
        changes: string;
        changesIn: (file: string) => string;
        renamedTo: string;
        stats: (added: number, removed: number) => string;
        view: string;
        unified: string;
        split: string;
    };
    dropzone: {
        uploading: string;
        uploadedOn: (date: string) => string;
        error: string;
        drag: string;
        or: string;
        browse: string;
        staged: string;
    };
    feedbackWidget: {
        question: string;
        yes: string;
        no: string;
        thanks: string;
        whatWentWrong: string;
        whatWorked: string;
        anythingElse: string;
        commentPlaceholder: string;
        send: string;
        skip: string;
    };
    file: {
        pick: string;
        replace: string;
    };
    filterField: {
        placeholder: string;
        add: string;
        attribute: string;
        noAttributes: string;
        searchFor: string;
        apply: string;
        removeSearch: (value: string) => string;
        removeFilter: (label: string) => string;
        selectedHint: (n: number) => string;
        none: string;
        applied: (n: number) => string;
        back: string;
        operator: (label: string) => string;
        contains: string;
        equals: string;
        isPresent: string;
        isMissing: string;
        valuePlaceholder: string;
        containsPlaceholder: string;
        search: (label: string) => string;
        noOptions: string;
        min: string;
        max: string;
        minimum: (label: string) => string;
        maximum: (label: string) => string;
        decreaseMin: (label: string) => string;
        increaseMin: (label: string) => string;
        decreaseMax: (label: string) => string;
        increaseMax: (label: string) => string;
    };
    filter: {
        countSelected: (label: string, n: number) => string;
        searchPlaceholder: (label: string) => string;
        search: (label: string) => string;
        noOptions: string;
        clearSelected: (n: number) => string;
    };
    helpIcon: {
        label: string;
    };
    imageCropper: {
        label: string;
        roleDescription: string;
        zoomOut: string;
        zoom: string;
        zoomIn: string;
        rotate: string;
    };
    inlineEdit: {
        placeholder: string;
        saveFailed: string;
        hint: (mod: string) => string;
        save: (label: string) => string;
        edit: (label: string) => string;
    };
    kanban: {
        label: string;
        empty: string;
        overLimit: (limit: number) => string;
        position: (column: string, index: number, total: number) => string;
        pickedUp: (item: string, position: string) => string;
        movedTo: (item: string, position: string) => string;
        droppedIn: (item: string, position: string) => string;
        dropped: (item: string) => string;
        cancelled: (item: string) => string;
    };
    keyboardShortcuts: {
        title: string;
        then: string;
    };
    label: {
        optional: string;
    };
    lightbox: {
        title: string;
        position: (n: number, count: number, alt: string) => string;
        zoomIn: string;
        zoomOut: string;
        previous: string;
        next: string;
        thumbnails: string;
        show: (n: number, alt: string) => string;
    };
    numberField: {
        decrement: string;
        increment: string;
    };
    pagination: {
        label: string;
        previous: string;
        previousPage: string;
        next: string;
        nextPage: string;
        more: string;
    };
    password: {
        show: string;
        rules: {
            length: string;
            upper: string;
            lower: string;
            number: string;
            symbol: string;
        };
        weak: string;
        good: string;
        strong: string;
        strength: string;
        empty: string;
        strengthIs: (status: string) => string;
        met: string;
        notMet: string;
    };
    phoneField: {
        tooShort: (country: string) => string;
        tooLong: (country: string) => string;
        digitsOnly: string;
        invalidLength: (country: string) => string;
        countryCode: (country: string, code: string) => string;
        chooseCountry: string;
        countries: string;
        search: string;
        noMatch: string;
        all: string;
        label: string;
    };
    price: {
        free: string;
        from: string;
        per: (period: string) => string;
        was: (price: string) => string;
        off: (percent: number) => string;
    };
    promptArea: {
        placeholder: string;
        send: string;
        stop: string;
        label: string;
        mentions: string;
        commands: string;
        tooLong: (max: number, length: number) => string;
    };
    qrCode: {
        label: string;
        loading: string;
        tooMuchLabel: string;
        tooMuch: string;
    };
    queryBuilder: {
        add: string;
        label: string;
        empty: string;
        match: string;
        matchType: string;
        all: string;
        any: string;
        ofTheFollowing: string;
        field: string;
        fieldFallback: string;
        condition: (field: string) => string;
        removeCondition: (field: string) => string;
        value: string;
        min: string;
        max: string;
        and: string;
        from: (name: string) => string;
        to: (name: string) => string;
        startDate: string;
        endDate: string;
        select: string;
        selectValues: string;
        operators: {
            text: {
                contains: string;
                not_contains: string;
                equals: string;
                not_equals: string;
                starts_with: string;
                ends_with: string;
                is_empty: string;
                is_not_empty: string;
            };
            number: {
                equals: string;
                not_equals: string;
                gt: string;
                gte: string;
                lt: string;
                lte: string;
                between: string;
            };
            date: {
                on: string;
                before: string;
                after: string;
                between: string;
            };
            select: {
                is: string;
                is_not: string;
                is_any_of: string;
                is_none_of: string;
            };
            boolean: {
                is_true: string;
                is_false: string;
            };
        };
    };
    rangeField: {
        from: string;
        to: string;
        any: string;
        label: string;
    };
    resizable: {
        handle: string;
    };
    richTextEditor: {
        link: string;
        linkShortcut: string;
        url: string;
        removeLink: string;
        update: string;
        addLink: string;
        paragraph: string;
        heading2: string;
        heading3: string;
        textStyle: (style: string) => string;
        bold: string;
        italic: string;
        underline: string;
        strikethrough: string;
        inlineCode: string;
        bulletedList: string;
        numberedList: string;
        quote: string;
        codeBlock: string;
        undo: string;
        redo: string;
        formatting: string;
        characters: string;
    };
    scheduler: {
        previous: {
            day: string;
            week: string;
            month: string;
        };
        next: {
            day: string;
            week: string;
            month: string;
        };
        today: string;
        view: string;
        views: {
            day: string;
            week: string;
            month: string;
        };
        dayLabel: (day: string, isToday: boolean) => string;
        allDay: string;
        allDayEvent: (title: string) => string;
        eventLabel: (title: string, time: string) => string;
        more: (n: number) => string;
        moreOn: (day: string) => string;
        noEvents: string;
    };
    secretField: {
        label: string;
        copied: string;
        copiedHint: string;
        hidden: (label: string, tail?: string) => string;
        show: (label: string) => string;
        copy: (label: string) => string;
        copyFailed: string;
        copyManually: string;
        insecure: string;
    };
    sidebar: {
        navigation: string;
        expand: string;
        collapse: string;
        main: string;
        moreActions: string;
    };
    toaster: {
        progress: string;
    };
    splitButton: {
        menu: string;
    };
    stepper: {
        label: string;
        step: (n: number, total: number, status: "complete" | "current" | "upcoming") => string;
        goBack: string;
    };
    stickyActionBar: {
        label: string;
    };
    swatchPicker: {
        unavailable: string;
        more: string;
    };
    tagInput: {
        placeholder: string;
        added: (values: string[]) => string;
        removed: (value: string) => string;
        count: (n: number, max: number) => string;
        invalid: string;
    };
    terminal: {
        output: string;
        connecting: string;
        disconnected: string;
        connected: string;
        error: string;
        warning: string;
    };
    textField: {
        clear: string;
    };
    themeToggle: {
        toLight: string;
        toDark: string;
    };
    densityToggle: {
        label: string;
        compact: string;
        default: string;
        comfortable: string;
    };
    timeRangePicker: {
        start: string;
        end: string;
        to: string;
    };
    topbar: {
        openMenu: string;
        searchPlaceholder: string;
        search: string;
        unread: (label: string) => string;
    };
    undoToast: {
        undo: string;
    };
    countdown: {
        unitWord: (unit: "days" | "hours" | "minutes" | "seconds", n: number) => string;
        short: {
            days: string;
            hours: string;
            minutes: string;
            seconds: string;
        };
        left: (time: string) => string;
    };
    rating: {
        value: (value: number, max: number) => string;
    };
    productTour: {
        next: string;
        back: string;
        done: string;
        skip: string;
        close: string;
        progress: (step: number, total: number) => string;
    };
    slider: {
        minimum: (label: string) => string;
        maximum: (label: string) => string;
        value: (label: string, n: number) => string;
    };
    usageBar: {
        label: (summary: string) => string;
    };
    cardDeck: {
        skip: string;
        keep: string;
        remaining: (n: number) => string;
        pause: string;
        play: string;
        next: string;
    };
    colorPicker: {
        area: string;
        areaValue: (s: number, v: number) => string;
        changePhoto: string;
        hex: string;
        format: string;
        opacityPercent: string;
        noColor: string;
        eyedropper: string;
        hue: string;
        degrees: (n: number) => string;
        opacity: string;
        uploadPhoto: string;
        open: string;
        label: string;
    };
};
export type TheyaMessages = typeof en;
export declare const enLocale: {
    locale: string;
    messages: {
        common: {
            close: string;
            clear: string;
            cancel: string;
            loading: string;
            noResults: string;
            copied: string;
            copyFailed: string;
            remove: (name: string) => string;
            more: (n: number) => string;
        };
        alert: {
            dismiss: string;
        };
        announcementBar: {
            dismiss: string;
            label: string;
        };
        autocomplete: {
            suggestions: string;
        };
        breadcrumb: {
            label: string;
            more: string;
            showMore: (n: number) => string;
        };
        carousel: {
            label: string;
            previous: string;
            next: string;
            slides: string;
            goTo: (n: number) => string;
        };
        chart: {
            trend: (points: number) => string;
            seriesTrend: (names: string, points: number) => string;
            range: (first: string, last: string, peak: string, peakLabel: string) => string;
            comparison: (count: number, label: string, value: string) => string;
            noData: string;
            total: string;
        };
        chartRangeSelection: {
            label: string;
            roleDescription: string;
            selected: (from: string, to: string) => string;
            cleared: string;
            help: string;
        };
        chat: {
            conversation: string;
            typing: string;
        };
        holdToTalk: {
            label: string;
            release: string;
        };
        speedDial: {
            open: string;
            close: string;
        };
        codeBlock: {
            copy: string;
        };
        codeEditor: {
            label: string;
        };
        combobox: {
            placeholder: string;
            create: (query: string) => string;
            clear: string;
            open: string;
            options: string;
        };
        command: {
            title: string;
            description: string;
            navigate: string;
            select: string;
        };
        confirmDialog: {
            confirm: string;
            typeToConfirm: (value: ReactNode) => ReactNode;
        };
        copyButton: {
            copy: string;
            copied: string;
            announced: string;
        };
        dataTableCell: {
            unlimited: string;
            badges: (n: number) => string;
        };
        table: {
            columnPages: string;
            showColumns: (from: number, to: number, total: number) => string;
        };
        marquee: {
            pause: string;
            play: string;
        };
        dataTable: {
            selectAll: string;
            selectAllTooltip: string;
            selectAllOnPage: string;
            clearSelection: string;
            selected: string;
            bulkActions: string;
            moreBulkActions: string;
            loadingMore: string;
            rowActions: string;
            actionsColumn: string;
            selectColumn: string;
            selectRow: (label?: string) => string;
            viewDetails: (label?: string) => string;
            previous: string;
            next: string;
            goToPage: (n: number) => string;
        };
        datePicker: {
            placeholder: string;
            clear: string;
        };
        dateRangePicker: {
            placeholder: string;
            clear: string;
        };
        timeField: {
            placeholder: string;
            time: string;
            timeOf: (label: string) => string;
            noMatch: string;
        };
        diffViewer: {
            expand: (n: number) => string;
            empty: string;
            changes: string;
            changesIn: (file: string) => string;
            renamedTo: string;
            stats: (added: number, removed: number) => string;
            view: string;
            unified: string;
            split: string;
        };
        dropzone: {
            uploading: string;
            uploadedOn: (date: string) => string;
            error: string;
            drag: string;
            or: string;
            browse: string;
            staged: string;
        };
        feedbackWidget: {
            question: string;
            yes: string;
            no: string;
            thanks: string;
            whatWentWrong: string;
            whatWorked: string;
            anythingElse: string;
            commentPlaceholder: string;
            send: string;
            skip: string;
        };
        file: {
            pick: string;
            replace: string;
        };
        filterField: {
            placeholder: string;
            add: string;
            attribute: string;
            noAttributes: string;
            searchFor: string;
            apply: string;
            removeSearch: (value: string) => string;
            removeFilter: (label: string) => string;
            selectedHint: (n: number) => string;
            none: string;
            applied: (n: number) => string;
            back: string;
            operator: (label: string) => string;
            contains: string;
            equals: string;
            isPresent: string;
            isMissing: string;
            valuePlaceholder: string;
            containsPlaceholder: string;
            search: (label: string) => string;
            noOptions: string;
            min: string;
            max: string;
            minimum: (label: string) => string;
            maximum: (label: string) => string;
            decreaseMin: (label: string) => string;
            increaseMin: (label: string) => string;
            decreaseMax: (label: string) => string;
            increaseMax: (label: string) => string;
        };
        filter: {
            countSelected: (label: string, n: number) => string;
            searchPlaceholder: (label: string) => string;
            search: (label: string) => string;
            noOptions: string;
            clearSelected: (n: number) => string;
        };
        helpIcon: {
            label: string;
        };
        imageCropper: {
            label: string;
            roleDescription: string;
            zoomOut: string;
            zoom: string;
            zoomIn: string;
            rotate: string;
        };
        inlineEdit: {
            placeholder: string;
            saveFailed: string;
            hint: (mod: string) => string;
            save: (label: string) => string;
            edit: (label: string) => string;
        };
        kanban: {
            label: string;
            empty: string;
            overLimit: (limit: number) => string;
            position: (column: string, index: number, total: number) => string;
            pickedUp: (item: string, position: string) => string;
            movedTo: (item: string, position: string) => string;
            droppedIn: (item: string, position: string) => string;
            dropped: (item: string) => string;
            cancelled: (item: string) => string;
        };
        keyboardShortcuts: {
            title: string;
            then: string;
        };
        label: {
            optional: string;
        };
        lightbox: {
            title: string;
            position: (n: number, count: number, alt: string) => string;
            zoomIn: string;
            zoomOut: string;
            previous: string;
            next: string;
            thumbnails: string;
            show: (n: number, alt: string) => string;
        };
        numberField: {
            decrement: string;
            increment: string;
        };
        pagination: {
            label: string;
            previous: string;
            previousPage: string;
            next: string;
            nextPage: string;
            more: string;
        };
        password: {
            show: string;
            rules: {
                length: string;
                upper: string;
                lower: string;
                number: string;
                symbol: string;
            };
            weak: string;
            good: string;
            strong: string;
            strength: string;
            empty: string;
            strengthIs: (status: string) => string;
            met: string;
            notMet: string;
        };
        phoneField: {
            tooShort: (country: string) => string;
            tooLong: (country: string) => string;
            digitsOnly: string;
            invalidLength: (country: string) => string;
            countryCode: (country: string, code: string) => string;
            chooseCountry: string;
            countries: string;
            search: string;
            noMatch: string;
            all: string;
            label: string;
        };
        price: {
            free: string;
            from: string;
            per: (period: string) => string;
            was: (price: string) => string;
            off: (percent: number) => string;
        };
        promptArea: {
            placeholder: string;
            send: string;
            stop: string;
            label: string;
            mentions: string;
            commands: string;
            tooLong: (max: number, length: number) => string;
        };
        qrCode: {
            label: string;
            loading: string;
            tooMuchLabel: string;
            tooMuch: string;
        };
        queryBuilder: {
            add: string;
            label: string;
            empty: string;
            match: string;
            matchType: string;
            all: string;
            any: string;
            ofTheFollowing: string;
            field: string;
            fieldFallback: string;
            condition: (field: string) => string;
            removeCondition: (field: string) => string;
            value: string;
            min: string;
            max: string;
            and: string;
            from: (name: string) => string;
            to: (name: string) => string;
            startDate: string;
            endDate: string;
            select: string;
            selectValues: string;
            operators: {
                text: {
                    contains: string;
                    not_contains: string;
                    equals: string;
                    not_equals: string;
                    starts_with: string;
                    ends_with: string;
                    is_empty: string;
                    is_not_empty: string;
                };
                number: {
                    equals: string;
                    not_equals: string;
                    gt: string;
                    gte: string;
                    lt: string;
                    lte: string;
                    between: string;
                };
                date: {
                    on: string;
                    before: string;
                    after: string;
                    between: string;
                };
                select: {
                    is: string;
                    is_not: string;
                    is_any_of: string;
                    is_none_of: string;
                };
                boolean: {
                    is_true: string;
                    is_false: string;
                };
            };
        };
        rangeField: {
            from: string;
            to: string;
            any: string;
            label: string;
        };
        resizable: {
            handle: string;
        };
        richTextEditor: {
            link: string;
            linkShortcut: string;
            url: string;
            removeLink: string;
            update: string;
            addLink: string;
            paragraph: string;
            heading2: string;
            heading3: string;
            textStyle: (style: string) => string;
            bold: string;
            italic: string;
            underline: string;
            strikethrough: string;
            inlineCode: string;
            bulletedList: string;
            numberedList: string;
            quote: string;
            codeBlock: string;
            undo: string;
            redo: string;
            formatting: string;
            characters: string;
        };
        scheduler: {
            previous: {
                day: string;
                week: string;
                month: string;
            };
            next: {
                day: string;
                week: string;
                month: string;
            };
            today: string;
            view: string;
            views: {
                day: string;
                week: string;
                month: string;
            };
            dayLabel: (day: string, isToday: boolean) => string;
            allDay: string;
            allDayEvent: (title: string) => string;
            eventLabel: (title: string, time: string) => string;
            more: (n: number) => string;
            moreOn: (day: string) => string;
            noEvents: string;
        };
        secretField: {
            label: string;
            copied: string;
            copiedHint: string;
            hidden: (label: string, tail?: string) => string;
            show: (label: string) => string;
            copy: (label: string) => string;
            copyFailed: string;
            copyManually: string;
            insecure: string;
        };
        sidebar: {
            navigation: string;
            expand: string;
            collapse: string;
            main: string;
            moreActions: string;
        };
        toaster: {
            progress: string;
        };
        splitButton: {
            menu: string;
        };
        stepper: {
            label: string;
            step: (n: number, total: number, status: "complete" | "current" | "upcoming") => string;
            goBack: string;
        };
        stickyActionBar: {
            label: string;
        };
        swatchPicker: {
            unavailable: string;
            more: string;
        };
        tagInput: {
            placeholder: string;
            added: (values: string[]) => string;
            removed: (value: string) => string;
            count: (n: number, max: number) => string;
            invalid: string;
        };
        terminal: {
            output: string;
            connecting: string;
            disconnected: string;
            connected: string;
            error: string;
            warning: string;
        };
        textField: {
            clear: string;
        };
        themeToggle: {
            toLight: string;
            toDark: string;
        };
        densityToggle: {
            label: string;
            compact: string;
            default: string;
            comfortable: string;
        };
        timeRangePicker: {
            start: string;
            end: string;
            to: string;
        };
        topbar: {
            openMenu: string;
            searchPlaceholder: string;
            search: string;
            unread: (label: string) => string;
        };
        undoToast: {
            undo: string;
        };
        countdown: {
            unitWord: (unit: "days" | "hours" | "minutes" | "seconds", n: number) => string;
            short: {
                days: string;
                hours: string;
                minutes: string;
                seconds: string;
            };
            left: (time: string) => string;
        };
        rating: {
            value: (value: number, max: number) => string;
        };
        productTour: {
            next: string;
            back: string;
            done: string;
            skip: string;
            close: string;
            progress: (step: number, total: number) => string;
        };
        slider: {
            minimum: (label: string) => string;
            maximum: (label: string) => string;
            value: (label: string, n: number) => string;
        };
        usageBar: {
            label: (summary: string) => string;
        };
        cardDeck: {
            skip: string;
            keep: string;
            remaining: (n: number) => string;
            pause: string;
            play: string;
            next: string;
        };
        colorPicker: {
            area: string;
            areaValue: (s: number, v: number) => string;
            changePhoto: string;
            hex: string;
            format: string;
            opacityPercent: string;
            noColor: string;
            eyedropper: string;
            hue: string;
            degrees: (n: number) => string;
            opacity: string;
            uploadPhoto: string;
            open: string;
            label: string;
        };
    };
    dir: "ltr";
};
