// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/lib/utils"

import { type ClassValue } from 'clsx';
export declare function cn(...inputs: ClassValue[]): string;
