// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/access-tokens"

import type { ReactNode } from 'react';
export interface AccessToken {
    id: string;
    name: string;
    maskedValue: string;
    createdAt: string;
    lastUsedAt?: string | null;
}
export interface AccessTokensProps {
    title?: string;
    description?: ReactNode;
    keys?: AccessToken[];
    onCreate?: (name: string) => string | Promise<string>;
    onRevoke?: (key: AccessToken) => void;
}
export declare function AccessTokens({ title, description, keys: keysProp, onCreate, onRevoke }: AccessTokensProps): import("react").JSX.Element;
