// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/audit-log"

import type { ReactNode } from 'react';
import { type BadgeTone } from '../ui/badge';
export interface AuditEvent {
    id: string;
    at: string;
    action: string;
    category: string;
    actor: string;
    target?: string;
    ip?: string;
}
export interface AuditCategoryMeta {
    value: string;
    label: string;
    tone?: BadgeTone;
    icon?: ReactNode;
}
export interface AuditLogProps {
    title?: string;
    description?: ReactNode;
    events?: AuditEvent[];
    categories?: AuditCategoryMeta[];
    loading?: boolean;
    searchPlaceholder?: string;
}
export declare function AuditLog({ title, description, events: eventsProp, categories, loading, searchPlaceholder, }: AuditLogProps): import("react").JSX.Element;
