// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/billing-usage"

import { type BadgeTone } from '../ui/badge';
import { type StatTone } from '../ui/stat';
import { type UsageSegment } from '../ui/usage-bar';
export interface BillingPlan {
    name: string;
    price?: string;
    renewal?: string;
    tone?: BadgeTone;
}
export interface BillingStat {
    label: string;
    value: string | number;
    hint?: string;
    tone?: StatTone;
    toneLabel?: string;
}
export interface BillingQuota {
    label: string;
    used: number;
    total: number;
    unit?: string;
}
export interface BillingInvoice {
    id: string;
    date: string;
    amount: string;
    status: 'paid' | 'due' | 'failed';
}
export interface BillingUsageProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    title?: string;
    plan?: BillingPlan;
    stats?: BillingStat[];
    quotas?: BillingQuota[];
    storageBreakdown?: UsageSegment[];
    storageTotal?: number;
    storageUnit?: string;
    invoices?: BillingInvoice[];
    onUpgrade?: () => void;
    upgradeLabel?: string;
}
export declare function BillingUsage({ className, title, plan, stats, quotas, storageBreakdown, storageTotal, storageUnit, invoices, onUpgrade, upgradeLabel, ...props }: BillingUsageProps): import("react").JSX.Element;
