// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/dashboard-overview"

import type { ReactNode } from 'react';
import { type StatusTone } from '../ui/status-dot';
import { type StatTone, type StatDelta } from '../ui/stat';
import { type AreaChartPoint } from '../ui/area-chart';
import { type UsageSegment } from '../ui/usage-bar';
export type AttentionTone = 'warning' | 'danger';
export interface AttentionItem {
    id: string;
    tone: AttentionTone;
    severity: string;
    reason: string;
    actionLabel: string;
}
export interface DashboardStat {
    label: string;
    value: string | number;
    icon?: ReactNode;
    tone?: StatTone;
    toneLabel?: string;
    delta?: StatDelta;
}
export interface ActivityItem {
    tone: StatusTone;
    icon: ReactNode;
    time: string;
    title: string;
    description: ReactNode;
}
export interface DashboardQuota {
    label: string;
    used: number;
    total: number;
    unit?: string;
}
export interface DashboardOverviewProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    title?: string;
    summary?: ReactNode;
    attention?: AttentionItem[];
    attentionTotal?: number;
    stats?: DashboardStat[];
    requests?: AreaChartPoint[];
    requestsAriaLabel?: string;
    quotas?: DashboardQuota[];
    capacity?: UsageSegment[];
    capacityTotal?: number;
    capacityFormat?: (n: number) => string;
    activity?: ActivityItem[];
    onAttentionAction?: (item: AttentionItem) => void;
    onViewAll?: () => void;
    viewAllHref?: string;
}
export declare function DashboardOverview({ className, title, summary, attention, attentionTotal, stats, requests, requestsAriaLabel, quotas, capacity, capacityTotal, capacityFormat, activity, onAttentionAction, onViewAll, viewAllHref, ...props }: DashboardOverviewProps): import("react").JSX.Element;
