// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/details"

import type { ReactNode } from 'react';
import { type StatusTone } from '../ui/status-dot';
import { type StatTone } from '../ui/stat';
export type DetailStatusTone = StatusTone;
export interface DetailStatus {
    tone: DetailStatusTone;
    label: string;
}
export interface DetailStat {
    label: string;
    value: ReactNode;
    hint?: string;
    tone?: StatTone;
    toneLabel?: string;
}
export interface DetailsProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    title: string;
    status?: DetailStatus;
    meta?: ReactNode[];
    actions?: ReactNode;
    stats?: DetailStat[];
}
export declare function Details({ className, title, status, meta, actions, stats, children, ...props }: DetailsProps): import("react").JSX.Element;
