// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/list-view"

import type { ReactNode } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { type DataTableBulkAction } from '../ui/data-table-toolbar';
export type ListFacet = {
    key: string;
    label: string;
    type: 'select';
    options: {
        value: string;
        label: string;
    }[];
    searchable?: boolean;
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'text';
    placeholder?: string;
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'number';
    icon?: ReactNode;
} | {
    key: string;
    label: string;
    type: 'date';
    range?: boolean;
    icon?: ReactNode;
};
export interface ListRowAction<Row> {
    label: string;
    icon?: ReactNode;
    tone?: 'neutral' | 'danger';
    separatorBefore?: boolean;
    onSelect?: (row: Row) => void;
    confirm?: {
        title: (row: Row) => ReactNode;
        description?: (row: Row) => ReactNode;
        typeToConfirm?: (row: Row) => string;
        confirmLabel?: string;
        cancelLabel?: string;
        confirmIcon?: ReactNode;
        onConfirm?: (row: Row) => void;
        undo?: {
            title: (row: Row) => string;
            description?: (row: Row) => string;
            icon?: ReactNode;
            onUndo?: (row: Row) => void;
        };
    };
}
export interface ListViewProps<Row> {
    columns?: ColumnDef<Row, unknown>[];
    data?: Row[];
    primaryKey?: string;
    searchPlaceholder?: string;
    facets?: ListFacet[];
    bulkActions?: DataTableBulkAction<Row>[];
    rowActions?: ListRowAction<Row>[] | ((row: Row) => ListRowAction<Row>[]);
    getRowId?: (row: Row) => string;
    getRowLabel?: (row: Row) => string;
    noun?: {
        one: string;
        many: string;
    };
    loading?: boolean;
    emptyMessage?: ReactNode;
    ariaLabel?: string;
    getRowHref?: (row: Row) => string;
}
interface SeededUser {
    [key: string]: unknown;
    id: string;
    name: string;
    email: string;
    role: string;
    status: 'active' | 'suspended' | 'invited';
}
export declare function ListView<Row extends Record<string, unknown> = SeededUser>(props?: ListViewProps<Row>): import("react").JSX.Element;
