// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/login-form"

import type { ComponentProps, FormEventHandler, ReactNode } from 'react';
export interface LoginFormProps extends Omit<ComponentProps<'div'>, 'onSubmit'> {
    onSubmit?: FormEventHandler<HTMLFormElement>;
    appName?: string;
    forgotHref?: string;
    signupHref?: string;
    showSso?: boolean;
    onSso?: () => void;
    card?: boolean;
    loading?: boolean;
    error?: ReactNode;
}
export declare function LoginForm({ className, onSubmit, appName, forgotHref, signupHref, showSso, onSso, card, loading, error, ...props }: LoginFormProps): import("react").JSX.Element;
