// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/login-form-split"

import type { ReactNode } from 'react';
import { type LoginFormProps } from './login-form';
export interface LoginFormSplitSlide {
    src: string;
    alt?: string;
}
export interface LoginFormSplitProps extends LoginFormProps {
    slides: LoginFormSplitSlide[];
    tagline?: ReactNode;
    logo?: ReactNode;
    backHref?: string;
    backLabel?: string;
    autoplayInterval?: number | false;
}
export declare function LoginFormSplit({ slides, tagline, logo, backHref, backLabel, autoplayInterval, appName, className, ...loginFormProps }: LoginFormSplitProps): import("react").JSX.Element;
