// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/notifications-inbox"

import type { ReactNode } from 'react';
import { type FilterOption } from '../ui/filter';
export type NotificationTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type InboxNotification = {
    id: string;
    title: string;
    description?: string;
    time: string;
    group?: string;
    tone?: NotificationTone;
    icon?: ReactNode;
    read?: boolean;
    href?: string;
    object?: string;
};
export type NotificationsInboxProps = {
    title?: string;
    description?: ReactNode;
    notifications?: InboxNotification[];
    onMarkAllRead?: () => void;
    onNotificationRead?: (notification: InboxNotification) => void;
    onNotificationUnread?: (notification: InboxNotification) => void;
    onDismiss?: (notification: InboxNotification) => void;
    onOpenSettings?: () => void;
    onClose?: () => void;
    bordered?: boolean;
    showStatusFilter?: boolean;
    objectFilterLabel?: string;
    objectOptions?: FilterOption[];
    defaultObjectFilter?: string[];
};
export declare function NotificationsInbox({ title, description, notifications: notificationsProp, onMarkAllRead, onNotificationRead, onNotificationUnread, onDismiss, onOpenSettings, onClose, bordered, showStatusFilter, objectFilterLabel, objectOptions, defaultObjectFilter, }: NotificationsInboxProps): import("react").JSX.Element;
