// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/onboarding-wizard"

import type { ReactNode } from 'react';
export interface WizardStep {
    id?: string;
    label: string;
    description?: string;
    content?: ReactNode;
    validate?: () => boolean | Promise<boolean>;
}
interface WizardContextValue {
    goTo: (step: number | string) => void;
    next: () => void;
}
export declare function useWizard(): WizardContextValue;
export interface OnboardingWizardProps {
    title?: string;
    description?: string;
    steps?: WizardStep[];
    current?: number;
    onStepChange?: (index: number) => void;
    onComplete?: () => void;
    completeLabel?: string;
    backLabel?: string;
    nextLabel?: string;
    orientation?: 'horizontal' | 'vertical';
    completing?: boolean;
    className?: string;
}
export declare function OnboardingWizard({ title, description, steps: stepsProp, current: controlledCurrent, onStepChange, onComplete, completeLabel, backLabel, nextLabel, orientation, completing, className, }: OnboardingWizardProps): import("react").JSX.Element;
