// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/preferences"

import type { FormEventHandler } from 'react';
export interface SettingsAccount {
    fullName: string;
    email: string;
}
export interface SettingsNotification {
    id: string;
    label: string;
    helper: string;
    defaultChecked: boolean;
}
export interface PreferencesProps extends Omit<React.ComponentProps<'div'>, 'title'> {
    account?: SettingsAccount;
    recoveryCode?: string;
    twoFactorEnabled?: boolean;
    onRegenerateRecoveryCode?: () => string | Promise<string>;
    notifications?: SettingsNotification[];
    onSaveProfile?: FormEventHandler<HTMLFormElement>;
    onChangePassword?: FormEventHandler<HTMLFormElement>;
    onEnableTwoFactor?: (code: string) => void;
    onNotificationChange?: (id: string, checked: boolean) => void;
    onDeleteAccount?: () => void;
    idPrefix?: string;
    navLabel?: string;
}
export declare function Preferences({ className, account, recoveryCode, notifications, onSaveProfile, onChangePassword, onEnableTwoFactor, twoFactorEnabled, onRegenerateRecoveryCode, onNotificationChange, onDeleteAccount, idPrefix, navLabel, ...props }: PreferencesProps): import("react").JSX.Element;
