// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/resource-form"

import type { ReactNode } from 'react';
export type ResourceFieldKind = 'text' | 'email' | 'password' | 'textarea' | 'number' | 'select' | 'checkbox' | 'switch';
export interface ResourceFieldOption {
    value: string;
    label: string;
}
export interface ResourceFieldConfig {
    name: string;
    label: string;
    kind?: ResourceFieldKind;
    description?: ReactNode;
    placeholder?: string;
    required?: boolean;
    options?: ResourceFieldOption[];
    min?: number;
    max?: number;
    step?: number;
    rows?: number;
    mono?: boolean;
    defaultValue?: string | number | boolean;
}
export interface ResourceFormSection {
    title?: string;
    description?: ReactNode;
    fields: ResourceFieldConfig[];
}
export type ResourceFormValues = Record<string, string | number | boolean>;
export interface ResourceFormProps {
    title?: string;
    description?: ReactNode;
    sections: ResourceFormSection[];
    onSubmit: (values: ResourceFormValues) => void | Promise<void>;
    onCancel?: () => void;
    submitLabel?: string;
    cancelLabel?: string;
    className?: string;
}
export declare function ResourceForm({ title, description, sections, onSubmit, onCancel, submitLabel, cancelLabel, className }: ResourceFormProps): import("react").JSX.Element;
