// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/team-members"

import { type ReactNode } from 'react';
import { type BadgeTone } from '../ui/badge';
export interface TeamRoleOption {
    value: string;
    label: string;
    description?: string;
    tone?: BadgeTone;
}
export interface TeamMember {
    id: string;
    name: string;
    email: string;
    role: string;
    lastActiveMins?: number | null;
    initials?: string;
}
export interface TeamInvite {
    id: string;
    email: string;
    role: string;
    invitedAgo?: string;
}
export interface TeamMembersProps {
    title?: string;
    description?: ReactNode;
    members?: TeamMember[];
    invites?: TeamInvite[];
    roles?: TeamRoleOption[];
    currentUserId?: string;
    onInvite?: (email: string, role: string) => void;
    onChangeRole?: (member: TeamMember, role: string) => void;
    onRemoveMember?: (member: TeamMember) => void;
    onResendInvite?: (invite: TeamInvite) => void;
    onRevokeInvite?: (invite: TeamInvite) => void;
}
export declare function TeamMembers({ title, description, members: membersProp, invites: invitesProp, roles, currentUserId, onInvite, onChangeRole, onRemoveMember, onResendInvite, onRevokeInvite, }: TeamMembersProps): import("react").JSX.Element;
