// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/workspace-layout"

import type { ReactNode } from 'react';
export interface WorkspaceLayoutNavItem {
    label: string;
    href?: string;
    icon?: ReactNode;
    badge?: ReactNode;
    active?: boolean;
    onSelect?: () => void;
}
export interface WorkspaceLayoutNavGroup {
    label?: string;
    items: WorkspaceLayoutNavItem[];
}
export interface WorkspaceLayoutCrumb {
    label: string;
    href?: string;
}
export interface WorkspaceLayoutProps {
    brand?: ReactNode;
    nav?: WorkspaceLayoutNavGroup[];
    breadcrumbs?: WorkspaceLayoutCrumb[];
    showBreadcrumbs?: boolean;
    actions?: ReactNode;
    user?: {
        name: string;
        org?: string;
        initials?: string;
    };
    searchPlaceholder?: string;
    onOpenNotifications?: () => void;
    unreadNotifications?: boolean;
    onOpenHelp?: () => void;
    onSearch?: () => void;
    defaultCollapsed?: boolean;
    children: ReactNode;
}
export declare function WorkspaceLayout({ brand, nav, breadcrumbs, showBreadcrumbs, actions, user, searchPlaceholder, onSearch, onOpenNotifications, unreadNotifications, onOpenHelp, defaultCollapsed, children, }: WorkspaceLayoutProps): import("react").JSX.Element;
