// Public API of @theya/shadcn — generated by scripts/build-api.mjs, do not edit.
// import from "@theya/shadcn/blocks/commerce/demo-data"

import type { ComparedFeature, ComparedPlan } from './plan-comparison';
import type { CartLine } from './cart';
export declare const DEMO_PLANS: ComparedPlan[];
export declare const DEMO_FEATURES: ComparedFeature[];
export declare const DEMO_CART: CartLine[];
export declare const DEMO_SAVED: CartLine[];
